### ISSUE TITLE
AutoValue 1.8 breaks gradle incremental compilation

### ISSUE THREAD

**Issue by aurelien-minvielle** [google/auto#1071]
Hello.
Since updating from AutoValue 1.7.5 to 1.8, using Gradle 6.8.3, it seems incremental compilation is broken.
I get the following log in info level after a single test file update:

```
> Task :xxx:compileTestJava
...
Task ':xxx:compileTestJava' is not up-to-date because:
  Input property 'stableSources' file xxx/JavaScriptInvocableFactoryTest.java has changed.
...
Full recompilation is required because com.google.auto.value.processor.AutoValueProcessor is not incremental. Analysis took 0.046 secs.
...
```

**Comment by tbroyer** [comment]
It looks like incap-processor is no longer run, due to https://github.com/google/auto/commit/a2f647f9d44174f502fb2f8a89a6c3a887ef14fe

**Comment by eamonnmcmanus** [comment]
Hmm, I suppose it needs to be in the `<annotationProcessorPath>`. Unfortunately we don't have tests for Gradle incremental compilation.

**Comment by eamonnmcmanus** [comment]
How does https://github.com/google/auto/pull/1072 look?

**Comment by tbroyer** [comment]
Fwiw, AutoFactory has the same issue, looking at its POM

**Comment by aurelien-minvielle** [comment]
I tried using autovalue version `HEAD-SNAPSHOT` to check the fix but still get the same behaviour and gradle log : a full recompilation is triggered after a single file update.
Am I doing something wrong ?

**Comment by tbroyer** [comment]
Ha, no, the processor was moved to the wrong `annotationProcessorPath` (the one for `compiler:testCompile`)

**Comment by eamonnmcmanus** [comment]
D'oh! So much for quick fixes.

**Comment by aurelien-minvielle** [comment]
Now works for me with your latest patch 👍 
Thanks for your quick response.
