### ISSUE TITLE
AutoBuilder?

### ISSUE THREAD

**Issue by ooxi** [google/auto#111]
Hi,

is there something like an `AutoBuilder` planned? Looking at the following class

```
@AutoValue
public abstract class MyValue {
    public abstract String getFirst();
    public abstract String getSecond();
}
```

it would be great if I could do the following

```
MyValue value = MyValue.builder()
    .withFirst("hello")
    .withSecond("world")
.build();
```

Or are there compelling reasons against? I know of auto factories but they serve another purpose.

-- ooxi

**Comment by felipecsl** [comment]
Looks like this has been just added a few days ago https://github.com/google/auto/pull/175

**Comment by ooxi** [comment]
@felipecsl Looks great, is there any documentation on how to use this?

**Comment by tbroyer** [comment]
@ooxi Have a look at the javadoc, there's a new `@AutoValue.Builder` annotation.

**Comment by eamonnmcmanus** [comment]
Yes, there are a few final improvements and a documentation change in the pipeline and they should show up at the next sync from Google's internal branch. Feel free to experiment; the javadoc should be enough to get the gist.

**Comment by ooxi** [comment]
:+1: great improvement :)

**Comment by h908714124** [comment]
AutoBuilder? Yes! https://github.com/h908714124/auto-builder
