### ISSUE TITLE
Annotate constructor parameters with `@Nullable` where relevant

### ISSUE THREAD

**Issue by desseim** [google/auto#116]
This was already raised in the discussion of #73 , but what is the state of making the constructor arguments nullable for properties which getters are annotated with `@Nullable` ?
This makes total sense from a user standpoint IMO (e.g. for static analysis), and wouldn't present as many tricky decisions as `equals()` would: simply annotate the parameter with the annotation the getter was annotated with (and no new dependency pulled either).

**Comment by sarod** [comment]
+1 here.

**Comment by eamonnmcmanus** [comment]
This issue was fixed last year but we neglected to close it.
