### ISSUE TITLE
META-INF/services not generated

### ISSUE THREAD

**Issue by adam-bialas** [google/auto#1163]
I am trying to integrate BlockHound (https://github.com/reactor/BlockHound) in my project. I need a custom config registered with the service. I added class in the test sources:

```
@AutoService(BlockHoundIntegration.class)
public class BlockHoundSecureRandom implements BlockHoundIntegration {

  @Override
  public void applyTo(Builder builder) {
    builder.allowBlockingCallsInside("java.security.SecureRandom", "next");
  }
}
```
and in the build.gradle file I added the following dependencies:

```
testImplementation 'org.junit.platform:junit-platform-launcher'
testImplementation 'com.google.auto.service:auto-service-annotations:1.0'
testAnnotationProcessor 'com.google.auto.service:auto-service:1.0'
testImplementation 'io.projectreactor.tools:blockhound-junit-platform:1.0.6.RELEASE'
```
I expect to have a file generated for the service under META-INF/services directory. However, nothing is generated. Am I missing something?

Edit:
File is generated but under wrong directory for gradle project

**Comment by amalloy** [comment]
Sounds like an issue with Gradle, or with your Gradle build config? We don't maintain any Gradle plugin, so if it works in Maven it's working in all the cases we have any control over.
