### ISSUE TITLE
add option to generate jakarta @Inject in generated factory

### ISSUE THREAD

**Issue by h908714124** [google/auto#1184]
Currently, the classes generated from `@AutoFactory` will have a  `javax.inject.Inject` annotation, which makes them incompatible with tools that use jakarta annotations. Please add some option, or alternative annotation, so users can choose to have a `jakarta.inject.Inject` annotation in the generated code instead.

**Comment by eamonnmcmanus** [comment]
Could you say some more about these tools? `javax.inject.Inject` has been the standard since JSR 330 was finalized in 2009. It seems surprising that tools would not understand it.

**Comment by eamonnmcmanus** [comment]
Closing due to lack of response.

**Comment by anuragagarwal561994** [comment]
@eamonnmcmanus this issue should be opened again, the standards have changed and even guice has now adopted to produce jakarta annotations in their latest versions 7.x and 6.x

Tomcat 10.x has also migrated to jakarta annotations as it has been finalised it to be the standard.

**Comment by eamonnmcmanus** [comment]
Agreed, with Guice moving to `jakarta.*` we should support this at least optionally.
