### ISSUE TITLE
AutoValue generates invalid code, constructor not validated

### ISSUE THREAD

**Issue by h908714124** [google/auto#1209]
Consider the following class

```java
@AutoValue
abstract class Foo {
    Foo(String bar) {
    }
    abstract String hello();
}
```

AutoValue should validate this class and fail with an error message. Instead it generates the following invalid constructor:

```java
  AutoValue_Foo(
      String hello) {
    if (hello == null) {
      throw new NullPointerException("Null hello");
    }
    this.hello = hello;
  }
```

This is a compile error. The constructor is invalid because `AutoValue_Foo` extends `Foo`, and there is no default constructor in `Foo`.

**Comment by cpovirk** [comment]
This seems like the kind of thing that @eamonnmcmanus often fixes instantly, but let's see what he thinks :)

**Comment by kosai576** [comment]
Hi
