### ISSUE TITLE
Should not extend final class

### ISSUE THREAD

**Issue by h908714124** [google/auto#1215]
AutoValue can't extend a final class but apparently it does, which leads to a compile error:

```java
@AutoValue
final class Foo {
}
```

```java
@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_Foo extends Foo {
// ... doesn't compile
}
```

**Comment by lowasser** [comment]
What do you expect to happen instead?  This looks like it _should_ end up with a compilation error.

**Comment by h908714124** [comment]
lowasser, annotation processors should validate their input _before_ they generate code. They should never generate invalid code.

**Comment by cpovirk** [comment]
Similar in that respect to https://github.com/google/auto/issues/1209. We'll see how highly Éamonn would like to prioritize this one, maybe based on his sense of how often it comes up.

**Comment by eamonnmcmanus** [comment]
> annotation processors should validate their input before they generate code

True, though in some cases the compilation error should be sufficiently clear that that isn't _really_ necessary.
