### ISSUE TITLE
AutoValue: (Optionally) Add private no-arg constructor to generated classes

### ISSUE THREAD

**Issue by talpr** [google/auto#122]
Some libraries require classes to have a private no-arg constructor, but there is currently no way of providing one for AutoValue's generated classes.

In my case, I am using Kryo (https://github.com/EsotericSoftware/kryo) to serialize/deserialize objects, and it requires that they have a no-arg constructor for deserialization. This means that currently I can't use AutoValue for classes that I intend to serialize.

Ideally, this should be configurable (provide a parameter to that annotation?).

**Comment by alfonsomunozpomer** [comment]
Seeing that this issue is still open, I just wanted to contribute by saying that you can create seralizers for your AutoValue classes. An example follows:

```java
public class OntologyTermSerializer extends Serializer<OntologyTerm>  {
    public OntologyTermSerializer() {
        super();
    }

    @Override
    public void write(Kryo kryo, Output output, OntologyTerm ontologyTerm) {
        kryo.writeObject(output, ontologyTerm.id());
        kryo.writeObjectOrNull(output, ontologyTerm.source(), String.class);
    }

    @Override
    public OntologyTerm read(Kryo kryo, Input input, Class<OntologyTerm> aClass) {
        return OntologyTerm.create(kryo.readObject(input, String.class), kryo.readObjectOrNull(input, String.class));
    }

    public static void registerSerializers(final Kryo kryo) {
        final OntologyTermSerializer serializer = new OntologyTermSerializer();
        kryo.register(OntologyTerm.create("").getClass(), serializer);
    }
}
```

Where OntologyTerm is:
```java
@AutoValue
public abstract class OntologyTerm {

    public abstract String id();

    @Nullable
    public abstract String source();

    public static OntologyTerm create(String id) {
        return create(id, null);
    }

    public static OntologyTerm create(String id, String source) {
        return new AutoValue_OntologyTerm(id, source);
    }
    ...
}
```

**Comment by eamonnmcmanus** [comment]
Thanks, that's a very helpful tip for people running into this problem!

**Comment by alfonsomunozpomer** [comment]
No problem. The “magic” and where I stumbled a bit until I figured it out is the line:

    kryo.register(OntologyTerm.create("").getClass(), serializer);

That links the actual AutoValue class to the abstract class.

**Comment by cgruber** [comment]
I was looking at the auto project overall, and thinking about a
documentation refresh, and this seems like a good candidate for a "tips and
tricks" page for auto-value.

**Comment by tuna-einstein** [comment]
An auto generated builder can be used.  Because, the generated builder class will have zero argument constructor with setter and getter methods. For example,

```
@AutoValue
public abstract class MyInfo {
    public MyInfo() {}
    public abstract String getUserName();
    public abstract String getPassword();
    public static Builder builder() {
        return new AutoValue_MyInfo.Builder();
    }

    public static Class<? extends Builder> builderClass() {
        return AutoValue_MyInfo.Builder.class;
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setUserName(String value);
        public abstract Builder setPassword(String value); 

        public abstract String getUserName();
        public abstract String getPassword();

        public abstract AccountInfo build();
        public abstract Builder toBuilder();
    }
}

```

**Comment by pabloem** [comment]
I'd just like to throw my hat in and comment that I ran into the same issue using Avro for serialization.
