### ISSUE TITLE
Could not find method compileOnlyApi()

### ISSUE THREAD

**Issue by chronvas** [google/auto#1220]
I get the error
```
> Could not find method compileOnlyApi() for arguments [com.google.auto.value:auto-value-annotations:1.8.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
While using:
```
    def auto_value_version = '1.8.2'
    compileOnlyApi "com.google.auto.value:auto-value-annotations:${auto_value_version}"
    annotationProcessor "com.google.auto.value:auto-value:${auto_value_version}"
```
On an Android project, using gradle 7.3.1 

Doc instructions followed: https://github.com/google/auto/blob/master/value/userguide/index.md#with-gradle

**Comment by chaoren** [comment]
You need to use `api` instead of `compileOnlyApi` for Android projects.

See https://developer.android.com/studio/build/dependencies#dependency_configurations

`compileOnlyApi` is only for `java-library` projects. I'll clarify the documentation.
