### ISSUE TITLE
AutoFactory / Dagger integration requires fully qualified types

### ISSUE THREAD

**Issue by amchang** [google/auto#124]
I found another strange issue but it seems there is a problem with dagger / autofactory integration.

I always always have to end up tying out the fully qualified so that dagger can find the factory at annotation / compile time.

@Inject
com.company.FooFactory

instead of being able to do

@Inject
FooFactory

I'm not sure if it's the way I'm compiling my projects also but wanted to track it here and see if you guys think it's a Dagger issue or an Auto issues, either way even if it's my environment it should try to be fixed from somewhere to prevent the issue from happening again in the future from the library side of things.

**Comment by svenjacobs** [comment]
I have a similar problem when trying to create a factory that contains another generated factory as a provided dependency. 

```java
@AutoFactory
public class SomeClass {

  SomeClass(@Provided AnotherClassFactory anotherClassFactory,
            @Provided SomeDependency someDependency,
            int someValue) {
    ...
  }
}
```

Given that `AnotherClass` is placed in a different package, the generated `SomeClassFactory` does not import `com.example.another.AnotherClassFactory` and compilation fails. If I use the fully qualified type of `AnotherClassFactory` in the constructor of `SomeClass` compilation works.

**Comment by ben-manes** [comment]
Just ran into this too. Usually works great, but refactoring of the package structure triggered this bug. The workaround is okay, but annoyingly verbose.

**Comment by gg7** [comment]
To anyone googling for "`error: cannot find symbol`", "`Note: Generating a Provider for`", "`Prefer to run the dagger processor over that class instead`": using fully qualified types solved the issue for me.

**Comment by dbarwacz** [comment]
So, in short, for some reason, factory fails at using dependencies that are yet to be generated by autofactory itself. Looks like code gen does not include import for those dependencies. I might find some time to look at this. Is it currently being worked on and are contributions welcome?

**Comment by Dondump** [comment]
Any news on this issue? I just run into it and it will be great to get it fixed.

**Comment by ronshapiro** [comment]
Let's merge this into #297, I think it's two sides of the same coin
