### ISSUE TITLE
Change retention of AutoAnnotation to CLASS to make it compatible with Gradle incremental compiler

### ISSUE THREAD

**Issue by asodja** [google/auto#1251]
We got a report that "isolating" processors might not produce correct results when combined with "aggregating" processors with the Gradle incremental compilation. In case the "isolating" processor and "aggregating" processor work on the same type, then all annotations have to have `CLASS` or `RUNTIME` retention, and not just `SOURCE`. This is a rare case that was forgotten when documentation was written.  Check for details: https://github.com/gradle/gradle/issues/19366.

We noticed that one of your annotations is using `SOURCE` retention:
https://github.com/google/auto/blob/9f01954e13ff67caeacf5681e741c58bc3f50dee/value/src/main/java/com/google/auto/value/AutoAnnotation.java#L109-L111

So to be 100% compatible with the Gradle incremental compilation, you should change that to `CLASS` retention.

**Comment by eamonnmcmanus** [comment]
This looks like an oversight. The other annotations in the same package have all moved from `SOURCE` to `CLASS` retention over time, but this one was missed.
