### ISSUE TITLE
[AutoFactory] nested factories break code generation

### ISSUE THREAD

**Issue by filipkowicz** [google/auto#1288]
in some cases (probably bc of order of code generation of autofactories) build fails (without proper message)
so if another factory is "provided" kapt phase of build (for android) fails with Dagger error that states `AppComponent because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.`

Workaround - hide nested factory behind interface and bind it in Dagger Module

**Comment by netdpb** [comment]
I'm not sure what you're asking about. If there is a case where AutoFactory breaks but it should not, can you give a small reproducing code snippet so we can understand the problem case?

**Comment by cpovirk** [comment]
Closing for now, but please reopen if you are able to produce a code snippet that demonstrates the problem that you can share.
