### ISSUE TITLE
AutoFactory: Lazy Fields in Parents

### ISSUE THREAD

**Issue by amchang** [google/auto#129]
http://stackoverflow.com/questions/25539899/dagger-google-auto-factory-deal-with-mix-of-lazy-and-provided-fields

Hey there I posted this question in StackOverflow but it seems like a big oversight or an explanation is needed, here's the example again.

```
public class Person {

   @Lazy<Foo> protected mLazyFoo;

}

@AutoFactory(
   className = "ManFactory"
)
public class Man extends Person {

    Private Hammer mHammer;

    Man(@Provided Hammer hammer) {
       mHammer = hammer;
    }

}

// mLazyFoo is null!!!!!
Man man = ManFactory.create();
```

How exactly would you deal with the problem of mLazyFoo being null? Adding a another provided to add Foo will not work at all as it will then be not be lazy then. The only valid method I could think about is the injector needs to inject fields onto the man object, then call the provided constructor.

Structurally I could add another mLazyFoo on the Man, but then we're going to get into duplicate field names then for every subclass (which is sort of code smelly).

**Comment by confile** [comment]
@amchang See this answer here: http://stackoverflow.com/a/29186106/1055664

**Comment by ronshapiro** [comment]
AutoFactory doesn't perform injection, it only constructs instances of the class and the _factory is injected_. This is working as intended
