### ISSUE TITLE
autovalue loads annotations too aggressively

### ISSUE THREAD

**Issue by pburka** [google/auto#1379]
My existing code fails to compile when I add autovalue to the processorpath. The code uses Guava, which is marked up with error-prone annotations. If I don't include the error-prone annotations on the classpath, autovalue causes javac to fail with the following error:

```
error: cannot access CanIgnoreReturnValue
  class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found
1 error
```

### Expected behavior

Adding autovalue to the processorpath should not affect existing programs.

### Actual behavior

autovalue changes the behavior of javac, even when no autovalue classes are present.

### Test case

```
$ cat Foo.java
import com.google.common.util.concurrent.ForwardingBlockingQueue;

public abstract class Foo<T> extends ForwardingBlockingQueue<T> {
}

$ javac -version
javac 17.0.4.1

$ javac -classpath guava-31.1-jre.jar Foo.java

$ javac -classpath guava-31.1-jre.jar -processorpath auto-value-1.10.jar Foo.java
error: cannot access CanIgnoreReturnValue
  class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found
1 error
```

The behavior is the same on Java 8, Java 11 and Java 17.

**Comment by eamonnmcmanus** [comment]
This doesn't seem to be a problem with AutoValue specifically. If I create an annotation processor that does nothing whatsoever and use it in place of `auto-value-1.10.jar` in the above command, I get the same error. You might want to log a bug against javac. This looks similar to but not the same as some existing bugs, such as [this one](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8162711).
