### ISSUE TITLE
AutoValue with Jackson deserialization

### ISSUE THREAD

**Issue by haocheng** [google/auto#138]
Hi, 

I was using AutoValue with Jackson. It works for serialization if I add @JsonProperty on all abstract methods. However, for deserialization, it will throw error like:

```
Can not construct instance of com.example.AccountDto, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
```

I can write custom Jackson deserializer to fix it, but it's a lot of work if I need to write custom deserializer for each value object that I need. Is there a better way to handle this issue?

Thank you!

**Comment by artem-zinnatullin** [comment]
Little example of AutoValue + Jackson https://github.com/artem-zinnatullin/AutoJackson with builder pattern

**Comment by vdelricco** [comment]
This solution was bothering me because it required you to either:

**A)** Move your builder method within the static build class. This means the consumer of your class was forced to access it like `AutoValueClass.Builder.builder()`.

**B)** In an effort to fix the above, you can create another builder method at the top level that references the static inner class builder method. This is the option the above example chose to take.

You can avoid having to deal with this by defining the `AutoValue_*` implemented class as the `@JsonDeserialize` `builder` argument. The following is an illustration which uses @artem-zinnatullin's example of a `Tweet` class.

```
@AutoValue
@JsonSerizalize(as = Tweet.class)
@JsonDeserialize(builder = AutoValue_Tweet.Builder.class)
public abstract class Tweet {

  @NotNull
  public static Builder builder() {
    return new AutoValue_Tweet.Builder();
  }

  @NotNull
  @JsonProperty("author")
  public abstract String author();

  @NotNull
  @JsonProperty("content")
  public abstract String content();

  @AutoValue.Builder
  public static abstract class Builder {
    @NotNull
    @JsonProperty("author")
    public abstract Builder author(@NotNull String author);

    @NotNull
    @JsonProperty("content")
    public abstract Builder content(@NotNull String content);

    @NotNull
    public abstract Tweet build();
  }
}
```

**Comment by hotzen** [comment]
> According to Jackson docs (i.e. I haven't tested it), you should annotate your static factory method with `@JsonCreator` and each argument with `@JsonProperty` to tell Jackson which property name corresponds to each argument.
> 
> ```java
> @JsonCreator public AccountDto create(@JsonProperty("id") String id, @JsonProperty("name") String name) {
>   return new AutoValue_AccountDto(id, name);
> }
> ```

this only works if you want to deserialize `AccountDto.class`
if the actual type `AutoValue_AccountDto` is sent over the wire (e.g. Spring AMQP) and jackson is told to deserialize into that type, it is not able to do so:

- autovalue class & constructor is package private
- @JsonCreator at the `AccountDto` is (obviously) not used for the requested type

thus I found no way to integrate AutoValue with Jackson :(
(other then to write an extension which also requires the @AutoService dependency to setup the ServiceLocator automatically....)

**Comment by feinstein** [comment]
> ```
> @AutoValue
> @JsonSerizalize(as = Tweet.class)
> @JsonDeserialize(builder = AutoValue_Tweet.Builder.class)
> public abstract class Tweet {
>   }
> ```

Small typo at `@JsonSerizalize` though, should be `@JsonSerialize`.

**Comment by vdelricco** [comment]
Nope, I don't believe so. That was just an artifact of the original example by @artem-zinnatullin, which I altered.

**Comment by feinstein** [comment]
Actually, I think this is the bare minimum necessary:

```java
@AutoValue
@JsonDeserialize(builder = AutoValue_Tweet.Builder.class)
public abstract class Tweet {

  public static Builder builder() {
    return new AutoValue_Tweet.Builder();
  }

  @JsonProperty("author")
  public abstract String author();

  @JsonProperty("content")
  public abstract String content();

  @AutoValue.Builder
  @JsonPOJOBuilder(withPrefix = "")
  public static abstract class Builder {
    public abstract Builder author(String author);
    public abstract Builder content(String content);
    public abstract Tweet build();
  }
}
```

Observations:

- We need `@JsonPOJOBuilder(withPrefix = "")` because Jackson looks for `with` as prefix for setters in builders, so we need to change it to no prefix instead (and AutoValue doesn't accept builder setters with the `with` prefix, but accepts `set` as a prefix if you want).
- We need `@JsonProperty("author")` if we are using getters with no `get` prefix. If you instead change your getter to `getAuthor()`, you can remove the `@JsonProperty("author")`.

**Comment by harishkannarao** [comment]
I got the following example which uses very few annotation from Jackson library.
It has example of optional field, collection field along with the builder methods for the same.

```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.google.auto.value.AutoValue;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@AutoValue
@JsonDeserialize(builder = AutoValue_ExampleModel.Builder.class)
public abstract class ExampleModel {

    public abstract UUID getId();
    public abstract Optional<String> getTitle();
    public abstract String getName();
    public abstract OffsetDateTime getDateTime();
    @JsonProperty("long")
    public abstract Optional<Long> getLongField();
    public abstract boolean isEligible();
    public abstract List<String> getFavouritePlaces();

    public abstract Builder toBuilder();

    public static Builder builder() {
        return new AutoValue_ExampleModel.Builder();
    }

    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
    @AutoValue.Builder
    @JsonPOJOBuilder(withPrefix = "")
    public static abstract class Builder {
        public abstract Builder id(UUID value);
        public abstract Builder title(Optional<String> value);
        public abstract Builder name(String value);
        public abstract Builder dateTime(OffsetDateTime value);
        @JsonProperty("long")
        public abstract Builder longField(Optional<Long> value);
        public abstract Builder eligible(boolean value);
        public abstract Builder favouritePlaces(List<String> values);
        public abstract ExampleModel build();
    }
}
```
