### ISSUE TITLE
Figure out a better solution to SuperficialValidator's handling of <error> nodes. 

### ISSUE THREAD

**Issue by cgruber** [google/auto#141]
The problem is that types which have not yet been generated, yet used as class literals in annotation values may return <error> nodes.  Detecting this as distinct from a case where Foo.class simply isn't on the classpath is not trivial, and a different solution may be necessary.

For now, this is simply commented out (in pull request #142) until we can figure out something more robust.

One option may be returning bad state in some sort of validation report so that calling code can decide if it wants to bail or keep going. Distinguishing, for instance, missing class literals from other problems may be worthwhile.  Another option may be to simply leave SuperficialValidator as even more superficial, with lots of good notes and practices on how to cope with its limitations - which may, sadly, include littering a lot of NPE and ClassCastException checks around one's processors, in order to avoid crashing the compiler.

**Comment by ronshapiro** [comment]
I'm not sure I understand what this is about/how we would ever distinguish about a type-not-yet-generated and a type that's missing from the classpath. That seems likely to be arbitrary, at best heuristic based?

But given that the commented out code that @cgruber mentioned is no longer commented out, and that this is 4.5 years old with no updates, I'm going to close, and we can reopen it if it is in fact still relevant
