### ISSUE TITLE
@AutoService should have a retention of SOURCE

### ISSUE THREAD

**Issue by dmlloyd** [google/auto#143]
...else things that look for it reflectively will fail.

**Comment by arend-von-reinersdorff** [comment]
@AutoValue already has retention policy SOURCE
https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/AutoValue.java

@AutoFactory has no retention policy
Similar to @eamonnmcmanus last comment, I think it should also be SUORCE.
https://github.com/google/auto/blob/master/factory/src/main/java/com/google/auto/factory/AutoFactory.java

**Comment by adriancole** [comment]
I think this was sorted a year ago or so. Any chance of an auto-service release?

**Comment by ronshapiro** [comment]
`Just released 1.0-rc3`

**Comment by SerialVelocity** [comment]
@ronshapiro I think you may have not pushed the tag up. It's not visible in the repo.

**Comment by ronshapiro** [comment]
Once #433 is merged I will push a tag off of the right commit. The version is live in maven central though.

**Comment by adriancole** [comment]
thanks!

**Comment by ctubbsii** [comment]
@ronshapiro #433 is merged, and the tag still hasn't been made. I realize rc4 is out, but it's still useful to have all the tags, for completion. It's helpful to see the differences between each version using git diff.

**Comment by ronshapiro** [comment]
@ctubbsii I just tried to push again but it seems to already be there? Maybe you need to fetch the tags?

**Comment by tbroyer** [comment]
Fwiw, I confirm the tag is here since Feb 9 (at least, according to GitHub): https://github.com/google/auto/releases/tag/auto-service-1.0-rc4

**Comment by ctubbsii** [comment]
@tbroyer rc3 is the missing tag that needs to be pushed, not rc4.

**Comment by tbroyer** [comment]
Ah, sorry; then I confirm there's no `auto-service-1.0-rc3` tag: https://github.com/google/auto/releases/tag/auto-service-1.0-rc3

```
$ git fetch upstream --tags
$ git tag -l auto-service-*
auto-service-1.0-rc1
auto-service-1.0-rc2
auto-service-1.0-rc4
```
