### ISSUE TITLE
Renaming build()?

### ISSUE THREAD

**Issue by daniel-mezo** [google/auto#1430]
Hi there, 

I am using AutoValue with the Builder pattern it provides with `@AutoValue.Builder`.

I found this comment on the howto page:

> ... use different names besides builder()/Builder/build()?
> Use whichever names you like; AutoValue doesn't actually care.

However, if I try to rename my `build()` in the builder class, AutoValue starts complaining.

```Example code
@AutoValue
abstract class MyClass {
    abstract String stuff();
    
    @AutoValue.Builder
    abstract static class Builder {
        public abstract Builder stuff(String stuff);
        public abstract MyClass generate();
    }
}
```
> error: [AutoValueBuilderNoArg] Method without arguments should be a build method returning com.stuff.MyClass, or a getter method with the same name and type as a property method of com.stuff.MyClass, or fooBuilder() where foo() or getFoo() is a property method of com.stuff.MyClass 
> public abstract MyClass generate();

Do I misunderstood the comment, or did I took it somehow out of context or is it just wrong?

**Comment by eamonnmcmanus** [comment]
Hi, I'm unable to reproduce your problem. If I paste that exact code into `MyClass.java`, insert an appropriate `package` declaration, and compile, it works fine. Could you give some more details?

- Which version of AutoValue.
- Which version of Java.
- How you are building it.

**Comment by eamonnmcmanus** [comment]
Closing due to lack of response. Feel free to reopen with the details requested.
