### ISSUE TITLE
AutoFactory checkNotNull index in error message is 1-indexed, despite java being 0-indexed

### ISSUE THREAD

**Issue by mhansen** [google/auto#1495]
AutoFactory gives an error message 

```
@AutoFactory method argument is null but is not marked @Nullable. Argument index 1
```

I wasn't sure if this meant the first or second element, as java is 0-indexed. IndexOutOfBoundsException is 0-indexed. But in AutoFactory this turns out to be 1-indexed.

It's a bit confusing.

The problem starts here where we start the loop at 1:

https://github.com/google/auto/blob/75ef346ccd9a8b6b00f38b6e1d7cfaddb0ba896b/factory/src/main/java/com/google/auto/factory/processor/FactoryWriter.java#L162:

```
      for (int argumentIndex = 1; parameters.hasNext(); argumentIndex++) {
```

Options:
1. Change to 0-indexed? Optionally, also make clear that it's 0-indexed.
2. Make clear in the error message you mean it's 1-indexed?
3. Put the argument name (text) in the error message? It's what AutoValue does, I think. Neatly sidesteps this issue and does not require users to count.

Thoughts?

**Comment by eamonnmcmanus** [comment]
Probably just saying "Argument number 1" rather than "Argument index 1" would be enough for the rewording? We often index from 0, but we don't usually number things from 0.

[I'm trying not to be bothered by the wording of the rest of the message. The argument is null, but it's the _parameter_ that is `@Nullable`.]

**Comment by mhansen** [comment]
I think number 1 sounds great! I think that is a clever way to avoid
confusion

**Comment by ronshapiro** [comment]
I think "number 1" is also probably a source of confusion, though possibly less. I vote for adding the start index/number is best. Or something like argument 1 of 7

**Comment by mhansen** [comment]
I think its a good idea to include the total even if it just helps users
count back from the end sometimes. “1 of 7” sounds pretty clear to me
