### ISSUE TITLE
noSuchElementException

### ISSUE THREAD

**Issue by SJLBenjamin** [google/auto#1520]
![image](https://github.com/google/auto/assets/34360323/2ced1809-649d-4550-8aa3-930e42521147)

**Comment by eamonnmcmanus** [comment]
I think we need a bit more context on what it is you are trying to do. I'm guessing this is an Android app, and if you are able to reproduce the problem in a version that is not obfuscated that would make it easier to understand what's going on. However I see `kotlin.coroutines` in the stack trace and my suspicion is that you are running into a concurrency issue. `ServiceLoader` is not designed to be thread-safe ([link](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html#:~:text=privileged%20security%20context.-,Concurrency,-Instances%20of%20this)).

**Comment by SJLBenjamin** [comment]
> I think we need a bit more context on what it is you are trying to do. I'm guessing this is an Android app, and if you are able to reproduce the problem in a version that is not obfuscated that would make it easier to understand what's going on. However I see `kotlin.coroutines` in the stack trace and my suspicion is that you are running into a concurrency issue. `ServiceLoader` is not designed to be thread-safe ([link](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html#:~:text=privileged%20security%20context.-,Concurrency,-Instances%20of%20this)).

But when I loaded it, it was thread safe, and I don't know why there was this error again
the code:
object PCManager {
    private var mCapabilityList = ServiceLoader.load(ICapabilityInitHelper::class.java, this.javaClass.classLoader)
}

When using:
 GlobalScope.launch { 
                  mCapabilityList.forEach {
                     it.clearInterceptor()
                }
  }

**Comment by eamonnmcmanus** [comment]
This is a question about using `ServiceLoader` rather than about AutoService, so it's not really appropriate here. I believe your best bet is to copy the values returned by `ServiceLoader` into a list, which will then not change subsequently. You can probably just add `.toList()`:
```kotlin
private var mCapabilityList = ServiceLoader.load(...).toList()
```
