### ISSUE TITLE
AutoService breaks with Immutables

### ISSUE THREAD

**Issue by mswintermeyer** [google/auto#1523]
We often use `@AutoService` with `@Value.Immutable`, and that workflow has broken with https://github.com/google/auto/commit/591731c32a6b425a43023335fb062c247fd65e63. An example of such a file is here: https://github.com/palantir/atlasdb/blob/3f5847c30c2cd0fed823af2a401bc2159a2e2178/atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceConfig.java#L38. Is it possible to remove that restriction, or make it less strict, when there are abstract or interface classes that actually are valid to use with `@AutoService`?

**Comment by tbroyer** [comment]
That class cannot be used with `ServiceLoader` AFAICT. Pass `-Averify=false` as a compiler argument to disable those checks?

**Comment by mswintermeyer** [comment]
Thanks, I'll SuppressWarnings for now, but it'd be great to not have such strong validation when there are libraries that actually are compatible with AutoService on interfaces/abstract classes.

I'm not sure how @Value.Immutable works under the hood. Not sure if that's info that'd be easy to find in their docs https://immutables.github.io/

**Comment by eamonnmcmanus** [comment]
Well, can you say why you have `@AutoService` in the first place? What happens if you don't have it?

I was also unable to see anything in the Immutables documentation about `META-INF/services`.

**Comment by SentryMan** [comment]
I'd imagine it's because Immutables can copy annotations on the abstract class to the generated class. So in the second round of AP, an auto service is generated for the generated implementation.

**Comment by tbroyer** [comment]
Still, the generated class won't have a zero-argument constructor so it won't be compatible with ServiceLoader. And the abstract class is still processed as well.
Looking briefly at the code, ServiceLoader isn't used for the linked class's type, and there's no mention of META-INF/services either. There's a possibility this is being done by a library though, but maybe there's just no reason for that class to be annotated with `@AutoService`.

**Comment by eamonnmcmanus** [comment]
Thanks for the additional details!

I guess my inclination is to say that what you are doing is outside the [documented](https://javadoc.io/doc/com.google.auto.service/auto-service-annotations/latest/com/google/auto/service/AutoService.html) main purpose of AutoService:

> An annotation for service providers as described in `ServiceLoader`. The annotation processor generates the configuration files that allow the annotated class to be loaded with [`ServiceLoader.load(Class)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/ServiceLoader.html#load(java.lang.Class)).
>
> The annotated class must conform to the service provider specification. Specifically, it must:
>
> * be a non-inner, non-anonymous, concrete class
> * have a publicly accessible no-arg constructor
> * implement the interface type returned by `value()`

Clearly the types you are applying `@AutoService` to don't meet these criteria. We're not really rigid about it, and that's part of the reason why we _don't_ require a publicly-accessible no-arg constructor. But we do still assume that you are trying to say that _this class_ is a way to get an implementation of the given interface.

If there were now _no way_ to achieve what you are doing then I think the new checks would be unduly restrictive. But you can probably just compile with `-Averify=false` and the problem will go away?
