### ISSUE TITLE
Eventually remove Eclipse order hack

### ISSUE THREAD

**Issue by stephenh** [google/auto#159]
This is not really an issue, per se, but if you haven't seen it,supposedly the "source order not respected" bug in Eclipse has been fixed:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=300408

It might be interesting to see if auto would work, sans the current Eclipse hack, in this fixed version of Eclipse; and if not, perhaps you could report back any issues on that bug so that it could be fixed while the Eclipse contributors are thinking about it. Just make to sure it really is fixed.

I also understand that until this version of Eclipse (4.5) is very widespread, you'll have to keep the order hack. But, hey, eventually anyway.

**Comment by eamonnmcmanus** [comment]
I actually removed the code in April 2017 but forgot to update this issue.
