### ISSUE TITLE
Is cross-process support available?

### ISSUE THREAD

**Issue by zuilintan** [google/auto#1624]
It is not mentioned in REDME.txt

**Comment by eamonnmcmanus** [comment]
I'm not sure what you're referring to. Could you clarify?

**Comment by zuilintan** [comment]
Does AutoService Support Inter-Process Communication (IPC)?

Hello,

I'm currently using Google's AutoService in my project and I'm wondering if it supports inter-process communication (IPC). Specifically, I'm interested in knowing whether services generated with AutoService can communicate across different processes.

Could you please provide some information on this?

Thank you for your time and assistance.

Best regards

**Comment by eamonnmcmanus** [comment]
I think the short answer is no. AutoService can't supply services to other processes. You might use it perhaps to provide an implementation of some service that other processes can invoke through RPC, but all it can do is to make that implementation available to an RPC framework that uses [`ServiceLoader`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html) to find RPC service implementations.

The [example](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html) from the documentation is really all that AutoService does.
