### ISSUE TITLE
@Provided primitives are not supported

### ISSUE THREAD

**Issue by theangrydev** [google/auto#164]
For example, attempting to use
```java
@Provided @Named int something
``` 
leads to a compilation failure because the generated factory includes
```java
private final Provider<int>
```

**Comment by tbroyer** [comment]
Fixed in https://github.com/google/auto/commit/0c10bc7dd72b3db59bf232a2f267408e34f00d21

**Comment by eamonnmcmanus** [comment]
Thanks for these cleanups!
