### ISSUE TITLE
Annotation Processor output is not deterministic

### ISSUE THREAD

**Issue by hendrikebbers** [google/auto#1656]
Hi,

the AutoService annotation processor uses a `Writer` for creating the `META-INF/service/` files. Here the `writer.newLine()` method is used to create the newlines in the file (see https://github.com/google/auto/blob/83b16dded09d864fbe2161d30c6b27f13a0883c3/service/processor/src/main/java/com/google/auto/service/processor/ServicesFiles.java#L87).

Sadly the method uses the os specific char for newline and therefore produces **non-deterministic builds**. 
Changing that would be an easy fix and I would be happy to provide a PR if you are interested in that.

**Comment by kluever** [comment]
Sounds reasonable...what do you think @eamonnmcmanus ?

**Comment by eamonnmcmanus** [comment]
Thanks for pointing this out! Yeah, just writing a `'\n'` should be fine and would remove the dependency on the line separator. A PR would be appreciated.

**Comment by hendrikebbers** [comment]
Will do it once I'm back from holiday break
