### ISSUE TITLE
Publish annotation APIs in separate artefacts

### ISSUE THREAD

**Issue by jbgi** [google/auto#167]
I would really like having a jar containing only the annotations and not the processors implementations: this would prevent accidental use of the processors implementation classes/dependencies in production code.
In particular, now that that guava dep is shadowed in autovalue, I can easily use autovalue.shaded.com.google.common.common.* classes by mistake, which will fail at runtime.

Note that it would only be useful if annotation processing is run in a separate phase (eg. via maven-processor-plugin)

**Comment by jbgi** [comment]
in the wait for a better solution, could we, at least, use a package prefix that would be further down the alphabetical order? 'autovalue.shaded' classes appear at the top of auto-completion lists...

**Comment by jbgi** [comment]
@eamonnmcmanus if we can't introduce the '$' sign before class names how about the prefixing the package instead? using
```<shadedPattern>\$autovalue.shaded.com.google.common</shadedPattern> ```
would work fine and would be a great usability improvement.

**Comment by tbroyer** [comment]
@eamonnmcmanus @jbgi The guys at ImmutablesOrg have forked maven-shade-plugin specifically for that: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22maven-shade-plugin%22

See https://github.com/immutables/tools#1-relocation-with--uglyfication

> Allows class relocation patterns to contain `$` sign. If pattern ends with `$` sign, the dollar sign will be prepended in front of class names. This effectively prevents clashed during code completion.

**Comment by cgruber** [comment]
Ooh! Thanks for the pointer, @tbroyer.

**Comment by jbgi** [comment]
closing in favor of #263
