### ISSUE TITLE
Drop support for running generated code under Java 7

### ISSUE THREAD

**Issue by cpovirk** [google/auto#1683]
I don't know whether it's worth doing this yet. I'm filing this issue because I'm looking at adding `Truth.assertThat(Stream)` and `Truth.assertThat(Optional)` and, when I do so, I see `AutoValueTest` and `AutoAnnotationTest` start to fail to compile under our (internal?) `--release 7` tests. I see some existing commentary in the `BUILD` file about avoiding deps that use Java 8 on pain of cryptic error, and I notice that the code already depends on our Android copy of com.google.common, which already has some Java 8 usages in it (albeit ones that don't trigger the `Symbol$CompletionFailure` we were apparently seeing there before).

I can plug on with migrating that test's assertions to use JUnit.

Or I can see if that test might be able to get away with `-source 7 -target 7` instead of `--release 7`. I see that it used `-source 7 -target 7` back when it used the Java 7 toolchain, and I'm not sure if the switch to `--release` was necessary at that point or not. Hmm, it looks like the same CL that moved it off the Java 7 toolchain actually removed the test that the code _runs_ under Java 7, leaving only the test that it _compiles_ with `--release 7`. I guess that `--release` is better at that sort of test than `-source 7 -target 7`, so it makes sense. (This was cl/231288987.)

Or maybe we're at the point that we can drop Java 7 support?

**Comment by cpovirk** [comment]
OK, `AutoAnnotationTest` wasn't too bad to port, but `AutoValueTest` is quite a bit longer... :) I will hold off to hear your thoughts on this.

**Comment by eamonnmcmanus** [comment]
We're fast approaching the 10th anniversary of the release of Java 8, so I think it would be fair to drop any form of Java 7 support now. People who still need it can always continue using older Auto versions.
