### ISSUE TITLE
AutoValue: Use qualified access everywhere

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#171]
I'm wondering if it would be possible to use qualified access (`this.property`) everywhere in generated `@AutoValue` classes. I am trying to enforce this on my projects, but generated classes will not compile with that option on. If it is not something to be added here, I am okay with making my own fork for it.

**Comment by kevinb9n** [comment]
Does it make sense to try to enforce your own local style rules on
third-party *generated* code? Is that really worth forking a project over?
It's your call, but I certainly don't see any valid reason to do this in
AutoValue.




On Thu, Jan 8, 2015 at 11:53 AM, Kenzie Togami <notifications@github.com>
wrote:

> I'm wondering if it would be possible to use qualified access (
> this.property) everywhere in generated @AutoValue classes. I am trying to
> enforce this on my projects, but generated classes will not compile with
> that option on. If it is not something to be added here, I am okay with
> making my own fork for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/171>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kenzierocks** [comment]
It is worth forking the project over, because otherwise I can't enforce that rule unless I abandon AutoValue. Small eclipse thing that I don't think is fixable, but I might bring up with the Eclipse team as well. It already partially happens anyways (in the constructor and `equals()`), I just need it to be everywhere. I would fork the project over this.

**Comment by JakeWharton** [comment]
It seems like a forever losing strategy. You artificially inhibit the usage of third party tools because they have to comply to your arbitrary internal style guides. What happens when you want to enforce hungarian notation or tabs? Does every tool need to comply? What if I'm enforcing that using redundant `this.` qualifiers is not present.

Your auditing strategy should be augmented to ignore generated code from third party tools. We do this for things like jOOQ for which we actually commit the generated sources into our source tree.

**Comment by kenzierocks** [comment]
Eclipse has no option to exclude generated code from the compile rule set, at least none that I can see. I suppose this is something for the Eclipse team then.

**Comment by eamonnmcmanus** [comment]
I believe it is possible to turn off warnings for generated code using
Project Properties > Java Build Path > Source > [project name]/.src_generated > Ignore Optional Compile Problems
Thanks to @cjp39 for this tip.

**Comment by kenzierocks** [comment]
Oh, I wonder why that didn't show up in my search for this. Thanks!
