### ISSUE TITLE
AutoFactory depends on Dagger 1, compilation fails with Dagger 2

### ISSUE THREAD

**Issue by cypressious** [google/auto#173]
When building with AutoFactory and Dagger 2, the build fails with the message ```java.lang.NoClassDefFoundError: dagger/ObjectGraph```. In my build I specifically excluded the Dagger 1 dependency from AutoFactory. Here's an extract from my build configuration:

```Groovy
dependencies {
    compile 'com.google.dagger:dagger:2.0-SNAPSHOT'
    compile 'javax.annotation:jsr250-api:1.0'
    compile ('com.google.auto.factory:auto-factory:0.1-beta1') {
        exclude module: 'dagger'
    }
    apt ('com.google.auto.factory:auto-factory:0.1-beta1') {
        exclude module: 'dagger'
    }
    apt 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT'
    provided 'org.glassfish:javax.annotation:10.0-b28'
}
```

I don't mind AutoFactory depending on Dagger 1 as long as it doesn't interfer with my build. Maybe the Dagger 1 dependency could be repackaged?

**Comment by cgruber** [comment]
#230 removes use of dagger in any capacity within the processor itself, leaving only support for JSR-330 usage in client code.
