### ISSUE TITLE
AutoFactory doesn't support Named dependecies

### ISSUE THREAD

**Issue by novemberox** [google/auto#174]
For example test class:

			@AutoFactory
			final class SomeClass {
			    private final String providedDepA;
			    private final String depB;

			    SomeClass(@Provided @Named("test") String providedDepA, String depB) {
				this.providedDepA = providedDepA;
				this.depB = depB;
			    }

			    // …
			}

I'm getting: 

			@Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
			final class SomeClassFactory {
			  private final Provider<String> providedDepAProvider;
			  @Inject
			  SomeClassFactory(@javax.inject.Named Provider<String> providedDepAProvider) {
			    this.providedDepAProvider = providedDepAProvider;
			  }
			  SomeClass create(String depB) {
			    return new SomeClass(providedDepAProvider.get(), depB);
			  }
			}

As you see value passed in `Named` annotation is not replicated in factory class

**Comment by confile** [comment]
+1 I have the same problem. @novemberox  Did you find any solution?

**Comment by novemberox** [comment]
Nope

**Comment by cgruber** [comment]
As mentioned in the other thread, the developers associated with AutoFactory are just coming off different leaves, and we should have some love for AutoFactory over the next month.

**Comment by cgruber** [comment]
The fix for this is in our internal repository as of today and I'll try to
get it out to a snapshot in the next day or two.  We have a few fixes and
I'll likely roll another pre-release next week.

**Comment by confile** [comment]
that is great. Thanks

**Comment by nuxusr** [comment]
Any update here?

**Comment by tbroyer** [comment]
Fixed in https://github.com/google/auto/commit/72ee7552cf2b734d3e7193c1915faaf1ff012f1b (released in 1.0-beta3)
