### ISSUE TITLE
Sonatype and Javadoc snapshots both failing since recently

### ISSUE THREAD

**Issue by cpovirk** [google/auto#1832]
[Sonatype](https://github.com/google/auto/actions/runs/10427644159/job/28882681916)

```
Failed to deploy artifacts: Could not transfer artifact com.google.auto:auto-common:jar:HEAD-20240816.234909-593 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): authentication failed for https://oss.sonatype.org/content/repositories/snapshots/com/google/auto/auto-common/HEAD-SNAPSHOT/auto-common-HEAD-20240816.234909-593.jar, status: 401 Content access is protected by token
```

That appears to have started with https://github.com/google/auto/commit/98c8ec71ca1693e96b3497f0c32a3801fbd281cd, but I assume it's a result of some credentials expiring or being regenerated or having access cut off. I reported a similar problem recently with Guava as internal bug 360518509, and it turned out to be simple to fix

> I'm going to try [looking up my Sonatype User Token](https://oss.sonatype.org/index.html#profile;User%20Token) and plugging it into [our repository secrets](https://github.com/google/guava/settings/secrets/actions). I don't know if the old one (last updated Aug 31, 2021) expired or what.

---

[Javadoc](https://github.com/google/auto/actions/runs/10579839621/job/29313375166)

```
mv: cannot stat '/home/runner/work/auto/auto/target/site/apidocs': No such file or directory
```

(Or at least I'm guessing that that's the problem.)

That appears to have started with either https://github.com/google/auto/commit/8a9bd4f927a6449dc3fbe5883c00908d6c344c51 or https://github.com/google/auto/commit/a161323372bbfdcb7af491c92ed9b1f1a87ee92e. It's hard to be sure which because the submission of the one cancelled the CI for the other.

**Comment by cpovirk** [comment]
I updated the Auto Sonatype secret to use my user token after [doing the same for Truth](https://github.com/google/truth/issues/1343). It was kind of a pain, but I think it's done.

That leaves only Javadoc. I may report progress on a similar problem with Truth for _that_, too.

**Comment by cpovirk** [comment]
I have a fix out for the Truth Javadoc problem, and it looks like the same fix will work here.

**Comment by cpovirk** [comment]
Javadoc is fixed. 

Sonatype snapshots are not fixed. I assume that I don't personally have the necessary permissions to publish for auto. We'll need someone who does have permissions to follow the instructions above.

**Comment by eamonnmcmanus** [comment]
Thanks for the detailed instructions! I've done that, and it looks like the Publish Snapshot action is working now.

**Comment by cpovirk** [comment]
Oh, nice, I'd forgotten that you can manually trigger reruns!
