### ISSUE TITLE
How do we tell Auto to add a `@Nullable` annotation to the equals method parameter in the class which implements an Annotation?

### ISSUE THREAD

**Issue by RamAnvesh** [google/auto#1869]
Similar to #612 but for `@AutoAnnotation` instead of `@AutoValue`

Declaring an abstract equals method is unfortunately not possible in case of annotation

**Comment by eamonnmcmanus** [comment]
I believe if you have [`JSpecify`](https://mvnrepository.com/artifact/org.jspecify/jspecify/1.0.0) in your classpath, then you should see `equals(@Nullable Object)` using `org.jspecify.annotations.Nullable`, in the code generated by AutoAnnotation. Alternatively if you compile with `-Acom.google.auto.value.NullableTypeAnnotation=some.other.package.Nullable` then it should use that `@Nullable` instead. Please let me know if neither of these works for you.
