### ISSUE TITLE
Propagate @GwtIncompatible to @AutoValue types, as is done for @GwtCompatible

### ISSUE THREAD

**Issue by cpovirk** [google/auto#187]
Motivation: [Truth defines an `AutoValue` type that doesn't work under GWT.](https://github.com/google/truth/blob/3f974942eecfb0318740c0bce8bd50395a9db001/core/src/main/java/com/google/common/truth/Expect.java#L52) But the AutoValue processor still runs, and it still generates the implementation. The implementation refers to the `@GwtIncompatible` superclass, and we get compile errors:

    [ERROR] Line 46: Expect.ExpectationFailure cannot be resolved to a type
    [ERROR] Line 23: The method message() of type AutoValue_Expect_ExpectationFailure must override or implement a supertype method
    [ERROR] Line 29: The method cause() of type AutoValue_Expect_ExpectationFailure must override or implement a supertype method
    [ERROR] Line 47: Expect.ExpectationFailure cannot be resolved to a type
    [ERROR] Line 7: Expect.ExpectationFailure cannot be resolved to a type

(I haven't managed to reproduce this with Truth's own GWT tests. I'm currently seeing it only when I modify our Guava build, which currently does its own `@GwtIncompatible` stripping, to rely on the GWT compiler's new automatic stripping. [Update: Truth's tests do catch it after all. I just hadn't run them *after* switching to the GWT compiler's stripping.])

I propose that AutoValue copy the `@GwtIncompatible` annotation just as it does the `@GwtCompatible` annotation, with one small twist: We should also copy the annotation from enclosing types, since the GWT compiler treats it as applying to enclosed types.

I'm working on an internal CL now, so if all this sounds reasonable, I'll send it for review when it's ready.

**Comment by eamonnmcmanus** [comment]
We copy annotations from abstract property methods to their generated implementations. Perhaps we should also copy them from the `@AutoValue` class to its implementation. I'm skeptical about the need to copy them from enclosing classes. If users have to add an otherwise-redundant `@GwtIncompatible` to their nested `@AutoValue` class I don't think that's the end of the world, and the alternative starts to look like quite complicated behaviour.

**Comment by cpovirk** [comment]
This is an interesting one.

Other annotations appearing on `@AutoValue` classes:

- `@Immutable`, `@ThreadSafe`
- `@VisibleForTesting`
- `@GwtCompatible` (of course)
- [`@AutoGson`](https://gist.github.com/JakeWharton/0d67d01badcee0ae7bc9)
- [`@JsExport`, `@JsType`](http://www.gwtproject.org/javadoc/latest/com/google/gwt/core/client/js/package-summary.html)
- some Google-internal stuff: [Full results for Éamonn and others at Google.](http://go/other-annotations-on-autovalue)

What would happen if we were to copy those to the generated types? I guess we'd have to try. I do have some fear that, even if it's safe for these annotations, it might not be safe for some future annotation. And if it's not, I'm not sure what the affected users would do for a workaround.

If we were to restrict this behavior to `@GwtIncompatible`, is that better or worse? On the one hand, it's yet another special case for GWT. On the other hand, it would avoid the hypothesized problems from copying other annotations. Plus, as a special case, it could get special treatment, specifically the copying from nested classes (which I agree would be unlikely to be the right thing for other annotations). I understand the argument that this is added complexity, but I think it's the best kind, the kind that users never think about because it always does what they want. (I hesitate a little to ever make that claim, but I do think it's true here: If the `@AutoValue` type is `@GwtIncompatible`, then generating its implementation will never work under GWT, and users would never be able to use it even if it did, since the superclass that provides access won't exist there.)

**Comment by adriancole** [comment]
AutoGson, huh? That sounds handy!

**Comment by cpovirk** [comment]
I'm running into a similar problem with Dagger: https://github.com/google/dagger/issues/121

This may be a common challenge for code generators.

**Comment by cgrushko** [comment]
Chris, I didn't understand what are the plans for this issue. 
I'm particularly interested in transferring over Bazel's @ThreadSafety.Immutable annotation.
(https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/concurrent/ThreadSafety.java)

**Comment by cpovirk** [comment]
I am personally still a fan of special handling for `@GwtIncompatible` (which involves looking at enclosing classes). This is probably mostly because it solves *my* problem :)

I do think that there's at least some reason to be concerned about copying *all* annotations from the abstract class. For example, if we copy `@AutoGson`, will the `@AutoGson` processor try to process both the abstract class and its concrete extension? (Presumably the `@AutoGson` processor could be modified to avoid this, but how many such consumers would need to be updated?)

But is it even possible to design a reasonable API for *user-specified* propagation of annotations? If not, do we program a set of "known good" names into AutoValue (presumably including `javax.annotation.concurrent.ThreadSafe` and thus, if we match by simple name, Bazel's version)?

I haven't pushed Éamonn further for special `@GwtIncompatible` handling (CL 85748721! :)), since it hasn't become a blocker for us just yet. I probably won't ever be pushing him for *general* handling of annotations, so you or someone else may need to champion that cause.

**Comment by cgrushko** [comment]
As usual, I worked around the problem in Bazel by getting rid of the annotation.
I imagine we can add a "propagated_annotations" attribute to @AutoValue.
If this seems clean enough, I'll keep this in mind next time I run into this, and might actually send a patch :)

**Comment by cgrushko** [comment]
This has come up again in Bazel - classes marked with @AutoValue cannot be exposed to Skylark using @SkylarkModule, because the latter doesn't end up on the generated class.

We could modify Bazel to look at the superclass (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/syntax/EvalUtils.java#L165) but seems very ad-hoc.

Are you open to the idea of a "propagated_annotations" or "annotations_to_copy" field of type list-of-string?

**Comment by eamonnmcmanus** [comment]
You know, even though we're very conservative about API changes, I think there's enough demand here that we should really do something. Perhaps `@AutoValue(copyAnnotations = {Foo.class, Bar.class})`, or perhaps `@AutoValue @AutoValue.CopyAnnotations({Foo.class, Bar.class})`. It would apply to both class and method annotations. We might deprecate the current behaviour of always copying method annotations.

I'm interested in @kevinb9n's opinion, though I think he's unavailable right now.

**Comment by cgrushko** [comment]
I believe this is now available internally?

**Comment by eamonnmcmanus** [comment]
Yes. I don't expect it to be in the 1.3 release but we should push it out shortly.

**Comment by cgrushko** [comment]
I finally have a use case for this in Bazel :)
I didn't see this in the sources for 1.4RC1 - what's the timeline for releasing this?

**Comment by eamonnmcmanus** [comment]
@cgrushko, your code for this *is* in 1.4-rc1. Is it not working for some reason?

**Comment by cgrushko** [comment]
Er... never mind, mis-read. Forget it :)
