### ISSUE TITLE
Add optional BeanInfo generation to support introspection

### ISSUE THREAD

**Issue by akanter** [google/auto#201]
It would be wonderful if AutoValue classes supported Java Bean introspection (http://www-inf.int-evry.fr/cours/java/javatutorial/javabeans/introspection/index.html).

My particular use case is to be able to use JDBI's @BindBean annotation on DTOs created with AutoValue instead of having to write my own @Binder annotation.

The trouble is that @BindBean uses reflection unless there is a valid BeanInfo class available. Given that the generated classes are always package private, reflection is out as a valid fallback option. This leaves BeanInfo classes. While I _could_ write a BeanInfo class for each AutoValue DTO I create, that kind of defeats AutoValue's advantage of keeping the written code concise.

**Comment by eamonnmcmanus** [comment]
I'm not familiar with JDBI, so it's not clear to me exactly what would be needed here. In this example from the documentation...

```java
public static interface BindBeanExample
{
  @SqlUpdate("insert into something (id, name) values (:id, :name)")
  void insert(@BindBean Something s);

  @SqlUpdate("update something set name = :s.name where id = :s.id")
  void update(@BindBean("s") Something something);
}
```

...would it not just work if Something were a public `@AutoValue` class with public getters? The fact that the object you are passing will actually be an `AutoValue_Something` shouldn't matter, should it?

Otherwise, this seems like it would be a good candidate for the extensibility API proposed as a solution for #87 and other use cases. The idea would be that it would be easy to write some additional code that would run at the same time as the AutoValue processor and generated the needed BeanInfo classes.

**Comment by akanter** [comment]
It would work fine if it were _public_ `@AutoValue` class, yes. The issue is that `@AutoValue` classes are always package private (unless I am mistaken).

I think the extensibility API sounds like a fabulous idea. Is such an API on the roadmap yet? From those links you provided it looks like it has been proposed but not yet undertaken. Should someone create a separate Extensibility API issue to track this?

**Comment by eamonnmcmanus** [comment]
`@AutoValue` classes can be public. It is only the generated `AutoValue_Foo` subclass that is always package-private. In the case at hand, it sounds as if the `@AutoValue` class should in fact be public.

The extensibility API is now tracked with #202. Thanks for making me get around to logging that. :-)

**Comment by akanter** [comment]
Er yeah. When I was saying the classes are always package private, I meant the generated classes.

The Introspection API uses calls `.getClass()` which returns `AutoValue_Foo.class` instead of `Foo.class`. Then the fallback mode uses reflection to inspect the class (`AutoValue_Foo.class`) to determine what fields are available. Since `AutoValue_Foo` is not `public`, this inspection fails.

If there were a `BeanInfo` for the class though, there should be no inspection required.

I'm closing this in favor of https://github.com/google/auto/issues/202. Whenever that is resolved, maybe I'll dig into making this feature myself.
