### ISSUE TITLE
Immutable collections with Builders

### ISSUE THREAD

**Issue by zack-shoylev** [google/auto#203]
Let's use a specific example:
I want my value object to use List<>, and I want the Builder for it to also use List (so as not to force users to depend on ImmutableList directly, say).
But, of course, I want internally my value object to use ImmutableList and any mutable components to be copied to immutable ones when build().
Is this reasonable, or should I just use ImmutableList throughout?

Extra note: this works fine without Builders as you can just use ImmutableList.copyOf in the create() method.

**Comment by eamonnmcmanus** [comment]
At present, I think the best way to achieve this with builders is something like this:

```java
@AutoValue
public abstract class ListContainer {
  public abstract List<String> list();

  public static Builder builder() {
    return new AutoValue_ListContainer.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setList(List<String> list);

    public ListContainer build() {
      ListContainer x = realBuild();
      return x.toBuilder().setList(ImmutableList.copyOf(x.list()));
    }

    abstract ListContainer realBuild();  // not public
  }
}
```

The abstract build method of a builder class does not have to be called `build()`, so we can have a public concrete `build()` that calls the generated `realBuild()`. It's kind of clumsy that you have to build one instance just so you can make another that has an ImmutableList, though.

An alternative approach is this:

```java
@AutoValue
public abstract class ListContainer {
  public List<String> list() {
    return immutableList();
  }
  abstract ImmutableList<String> immutableList();  // not public

  public static Builder builder() {
    return new AutoValue_ListContainer.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public Builder setList(List<String> list) {
      return setImmutableList(ImmutabeList.copyOf(list));
    }
    abstract Builder setImmutableList(ImmutableList<String> list);  // not public

    abstract ListContainer build();
  }
}
```

We're also thinking about allowing getters in the Builder class, so in the first example you could write something like this:

```java
  @AutoValue.Builder 
  public abstract static class Builder {
    public abstract List<String> list();
    public abstract Builder setList(List<String> list);

    public ListContainer build() {
      return setList(ImmutableList.copyOf(list()).realBuild();
    }
    abstract ListContainer realBuild();
  }
```

**Comment by kevinb9n** [comment]
And were we also considering Guava-specific features?  i.e., if they choose
to use ImmutableList as their property type, but List/Collection/Iterable
as the builder method type, then we generate an "ImmutableList.copyOf" for
them?

On Tue, Mar 10, 2015 at 4:04 PM, Éamonn McManus <notifications@github.com>
wrote:

> At present, I think the best way to achieve this with builders is
> something like this:
>
> @AutoValuepublic abstract class ListContainer {
>   public abstract List<String> list();
>
>   public static Builder builder() {
>     return new AutoValue_ListContainer.Builder();
>   }
>
>   @AutoValue.Builder
>   public abstract static class Builder {
>     public abstract Builder setList(List<String> list);
>
>     public ListContainer build() {
>       ListContainer x = realBuild();
>       return x.toBuilder().setList(ImmutableList.copyOf(x.list()));
>     }
>
>     abstract ListContainer realBuild();  // not public
>   }
> }
>
> The abstract build method of a builder class does not have to be called
> build(), so we can have a public concrete build() that calls the
> generated realBuild(). It's kind of clumsy that you have to build one
> instance just so you can make another that has an ImmutableList, though.
>
> An alternative approach is this:
>
> @AutoValuepublic abstract class ListContainer {
>   public List<String> list() {
>     return immutableList();
>   }
>   abstract ImmutableList<String> immutableList();  // not public
>
>   public static Builder builder() {
>     return new AutoValue_ListContainer.Builder();
>   }
>
>   @AutoValue.Builder
>   public abstract static class Builder {
>     public Builder setList(List<String> list) {
>       return setImmutableList(ImmutabeList.copyOf(list));
>     }
>     abstract Builder setImmutableList(ImmutableList<String> list);  // not public
>
>     abstract ListContainer build();
>   }
> }
>
> We're also thinking about allowing getters in the Builder class, so in the
> first example you could write something like this:
>
>   @AutoValue.Builder
>   public abstract static class Builder {
>     public abstract List<String> list();
>     public abstract Builder setList(List<String> list);
>
>     public ListContainer build() {
>       return setList(ImmutableList.copyOf(list()).realBuild();
>     }
>     abstract ListContainer realBuild();
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/203#issuecomment-78167691>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by eamonnmcmanus** [comment]
Yes, that also seems like a fine idea.

**Comment by zack-shoylev** [comment]
How about something like:
```java
   @AutoValue.Builder
   public abstract static class Builder {
      public abstract List<String> list();

      private void preprocess() {
         list(ImmutableList.copyOf(getList());
      }
   }
```
You already have validate() for the regular value object, so something like a preprocess (or whatever a good name for that is) for the builder makes sense, I think.

**Comment by eamonnmcmanus** [comment]
The method would have to be at least package-private so it could be called from the generated builder implementation. Other than that, the idea seems potentially useful. Would it be too much of a stretch to reuse the `@AutoValue.Validate` annotation here?

```java
  @AutoValue.Builder
  public abstract static class Builder {
    public abstract List<String> list();
    public abstract Builder setList(List<String> list);

    @AutoValue.Validate
    void preBuild() {
      setList(ImmutableList.copyOf(list()));
    }

    public abstract ListContainer build();
  }
```

**Comment by zack-shoylev** [comment]
Personally I would prefer the Builder getters be provided by default, but that might be out of scope. Otherwise, I like it.

**Comment by cgruber** [comment]
Builder getters available in #230.

**Comment by eamonnmcmanus** [comment]
I think it's a little premature to close this. We don't have support for `@AutoValue.Validate` in builders yet. (I am looking into it.)

**Comment by cgruber** [comment]
I thought we just removed support for @AutoValue.validate entirely.

**Comment by cgruber** [comment]
(in favor of coding in validations in the `.build()` method.

**Comment by eamonnmcmanus** [comment]
Wow, I'm confused. We did indeed.

**Comment by zack-shoylev** [comment]
I am not sure builder getters are sufficient. What would be the current example code to convert to immutable collections internally?

**Comment by eamonnmcmanus** [comment]
The code I gave above would work, except that it can't use `@AutoValue.Validate` since that no longer exists:

```java
  @AutoValue.Builder
  public abstract static class Builder {
    public abstract List<String> list();
    public abstract Builder setList(List<String> list);

    abstract ListContainer autoBuild();

    public ListContainer build() {
      setList(ImmutableList.copyOf(list()));
      return autoBuild();
    }
  }
```

**Comment by zack-shoylev** [comment]
Thanks @eamonnmcmanus and @cgruber : this looks great!
