### ISSUE TITLE
Autofactory compilation fails on Java 8

### ISSUE THREAD

**Issue by Zubnix** [google/auto#222]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project auto-factory: Compilation failure: Compilation failure:
[ERROR] /home/zubzub/git/auto/factory/src/test/java/com/google/auto/factory/processor/AutoFactoryDeclarationTest.java:[18,71] package com.google.auto.factory.processor.AutoFactoryDeclaration does not exist
[ERROR] /home/zubzub/git/auto/factory/src/test/java/com/google/auto/factory/processor/AutoFactoryDeclarationTest.java:[18,1] static import only from classes and interfaces

**Comment by Zubnix** [comment]
Possibly releted?
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7159016

**Comment by Zubnix** [comment]
On Java 7, an empty jar is build. Symptoms related to: #185

**Comment by Zubnix** [comment]
Not using static imports seems to fix the issue. However when trying to build from intellij causes a 'permission denied' error (works if build from terminal)

**Comment by kluever** [comment]
We're using AutoFactory and Java8 internally, so I suspect this can be closed.
