### ISSUE TITLE
Autofactory fails to build from IntelliJ

### ISSUE THREAD

**Issue by Zubnix** [google/auto#223]
When fixing issue #222 , autofactory fails to build in IntelliJ.

[INFO] --- maven-invoker-plugin:1.8:run (integration-test) @ auto-factory ---
[INFO] Building: functional/pom.xml
[INFO] /bin/sh: /home/zubzub/idea-IU-141.177.4/plugins/maven/lib/maven3/bin/mvn: Permission denied
[INFO] ..FAILED (0.0 s)
[INFO]   The build exited with code 126. See /home/zubzub/git/auto/factory/target/it/functional/build.log for details.

Contents of build.log:
http://hastebin.com/raw/zojugusija

**Comment by ibaca** [comment]
I had the same problem. Just add execution permissions to mvn. It's weird why only fails in IntelliJ + invoker-plugin, but this looks like a IntelliJ or maven-invoker-plugin problem, not and google-auto bug. ```chmode u+x  /home/zubzub/idea-IU-141.177.4/plugins/maven/lib/maven3/bin/mvn```
