### ISSUE TITLE
Release AutoValue 1.1

### ISSUE THREAD

**Issue by pgr0ss** [google/auto#224]
Can you please release version 1.1 (with the builder stuff)?

**Comment by leourbina** [comment]
+1

**Comment by cgruber** [comment]
We have a few changes we are making that are about to work its way in, and
we need to stabilize those - notably how validation is done in builders.
It's a breaking change, so we need to get it done/in/right before
releasing, so the newer behavior is what we release.

Once that's all done, I expect we can release.  This is not a commitment to
release, but I think we could probably release within the next week and a
half or so.  I defer to Eamonn McManos on specifics.

**Comment by leourbina** [comment]
sweet! :100:

**Comment by zack-shoylev** [comment]
+1!

**Comment by arcecio** [comment]
yay! +1

**Comment by adriancole** [comment]
+1

**Comment by mightyguava** [comment]
+1

**Comment by JakeWharton** [comment]
-1

**Comment by yterradas** [comment]
+1

**Comment by cgruber** [comment]
Apologies for the delay.  I'll be releasing later this week.

**Comment by leourbina** [comment]
Any updates on this? Would be nice to have the builder code in maven central. Thanks!

**Comment by cgruber** [comment]
Done. AutoValue 1.1 is released to maven (should show up in search in an hour or two, but be usable directly in a maven pom immediately)

**Comment by leourbina** [comment]
:beers:
