### ISSUE TITLE
[AutoFactory] Dependencies cannot resolve

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#225]
Dagger `2.0-SNAPSHOT` no longer exists, so the dependency can't resolve. Switch to `2.0` maybe?

**Comment by Zubnix** [comment]
autofactory is completely broken on current HEAD. It doesn't compile on latest maven, it uses removed api from dagger 2 dev, integration tests completely fail to even start, it still has some pretty severe bugs reported over a year ago. So yeah... still some work to do :)

**Comment by cgruber** [comment]
Heh.  We know.  Autofactory will get some love soon.

**Comment by cgruber** [comment]
Dagger dependency is removed in #230.
