### ISSUE TITLE
AutoFactory constructors are public if the class is public

### ISSUE THREAD

**Issue by charlesmunger** [google/auto#236]
It rarely makes sense to make the @Inject constructor of an AutoFactory public, but it's the default.

**Comment by arend-von-reinersdorff** [comment]
I disagree. I think for public classes there should be a public way to create instances programmatically. This is mostly about creating instances for testing. But also about principle. Having a public AutoFactory with a package constructor relies on DI container magic to create instances (using the package constructor via reflection). I find that ugly.

This is my personal opinion. There are counter arguments:
* Many Java programmers have no problem with container magic. Just think of injection into private fields in JPA.
* The AutoFactory project is not too concerned about testability of AutoFactories. See issue #99 about final factories.

**Comment by charlesmunger** [comment]
Given that AutoFactory's generated class takes `Provider` instances, the coupling to DI magic is already somewhat there. It's common to have classes that should only ever be obtained via DI, and this can be enforced by making your `@Inject` constructor package-private. AutoFactory doesn't have any way to obtain similar behavior today. 

The use cases for public constructors on AutoFactories I think are limited to:
* Creating objects in tests, where the test is not in the same java package as the autofactory (I think having the ability to mark AutoFactories non-final covers this pretty well - a testing AutoFactory can be provided). 
* Manually instantiating AutoFactories in application code. I think this is weird, because it requires dealing in a bunch of Providers - do people do this? What value are they deriving from it?

I could be convinced that the constructor should have `protected` visibility, but I do feel strongly that the default AutoFactory generated for a public class should not have a public constructor.

**Comment by kluever** [comment]
Sounds like this is WAI.
