### ISSUE TITLE
AutoServiceProcessorTest fails on Windows

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [google/auto#243]
The problem was reported earlier by @rherrmann in https://github.com/google/auto/issues/81#issuecomment-37545877

The problem occurs when AutoServiceProcessorTest compares the generated service files with the two files:
/auto-service/src/test/resources/META-INF/services/test.AnotherService
/auto-service/src/test/resources/META-INF/services/test.SomeService

These files have Unix linebreaks. When service files are generated on Windows, they have Windows linebreaks. The files are compared as bytes, so this difference is significant.

When I change the files to have Windows linebreaks, the test passes on Windows.

**Comment by ronshapiro** [comment]
AutoService uses `BufferedWriter.newLine()`, which says that it should respect the platform newline character(s). If this is still an issue, let's open a new bug, but given that this is ~4 years old, I think we should declare bankrupcy
