### ISSUE TITLE
AutoFactory doesn't support more than one qualifier annotation on parameters

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [google/auto#245]
I think this is a low priority issue. I haven't seen actual use of more than one qualifier annotation.

For example:

    @Qualifier
    @Retention(RUNTIME)
    @Target(PARAMETER)
    @interface Configured {
    }

    @AutoFactory
    final class SomeClass {
        private final String providedDepA;
    
        SomeClass(@Provided @Configured @Named String providedDepA) {
            this.providedDepA = providedDepA;
        }
    }

Generated Autofactory is missing the @Named qualifier:

    @Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
    final class SomeClassFactory {
      private final Provider<String> providedDepAProvider;
      @Inject
      SomeClassFactory(@Configured Provider<String> providedDepAProvider) {
        this.providedDepAProvider = providedDepAProvider;
      }
      SomeClass create() {
        return new SomeClass(providedDepAProvider.get());
      }
    }

**Comment by tbroyer** [comment]
It should probably report an error, or copy annotations so it fails later (e.g. Dagger); but it's not supported: http://docs.oracle.com/javaee/7/api/javax/inject/Inject.html

**Comment by arend-von-reinersdorff** [comment]
@tbroyer thanks for pointing that out :-) I didn't know that.

Also, I agree that reporting an error would be better than silently dropping annotations.


However,
* The Javadoc for @Inject says *should not*, not *must not*. So multiple qualifiers are discouraged but not forbidden

> no more than one qualifier *should* annotate a single field or parameter
> http://docs.oracle.com/javaee/7/api/javax/inject/Inject.html

* Also some dependency injection frameworks support multiple qualifiers
  * CDI supports multiple qualifiers

  > An injection point may even specify multiple qualifiers.
  > http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#qualifiers

  * I believe, Spring also supports multiple qualifiers. But I didn't find documentation for it.

On the other hand, other frameworks don't support multiple qualifiers
* As you said, Dagger doesn't support multiple qualifiers.

> Dependencies may not have multiple qualifier annotations.
> http://square.github.io/dagger/

* Guice doesn't support multiple qualifiers either

> Only one such annotation may apply to a single injection point
> http://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/BindingAnnotation.html


As there's so little support for multiple qualifiers, I guess support in AutoFactory is very low priority.

**Comment by cgruber** [comment]
Most importantly, the JSR-330 doesn't support multiple qualifier
annotations. Don't know about spring, but CDI does. However, CDI actually
breaks compatibility with JSR-330 in this context, and this is a point of
conflict between the two specifications.  If you're using multiple
qualifiers you are not, per the spec, compatible with JSR-330.  That was a
choice of the CDI spec leads and we can't really do much about it, though
there is some discussion about this matter in a thread about a future
revision to JSR-330.  I doubt multiple qualifiers will become a thing,
however.  The semantics are fraught and confusing, and most JSR-330
implementing teams seem pretty down on the idea.

**Comment by cgruber** [comment]
As to should vs. must in the javadoc, you are parsing language in a way the
spec authors did not intend.  "should not" in the case of multiple
qualifiers is synonymous with must not. A soft recommendation as you are
interpreting is not really relevant to a specification like this, and the
fact that the CDI spec leads would like JSR-330 to update to include
language that supports it tells me that even they acknowledge that it is
not supported in 330.

**Comment by arend-von-reinersdorff** [comment]
@cgruber You are correct, "should" reminded me strongly of the MUST/SHOULD/RFC 2119 language that is often used in Internet standards. But javax.inject doesn't have the usual reference to RFC 2119.

Thanks a lot for all the information about CDI being incompatible with JSR-330 on multiple qualifiers :-)
You mentioned a thread about a future revision to JSR-330. That sounds interesting, could you post the link or a general direction where to find it?

Also, I tested with Spring and it supports multiple qualifiers.

**Comment by cgruber** [comment]
The discussion is stalled, and on a regular email thread off-list, and on a
doc shared among participants.  Nothing terribly exciting at this point.
