### ISSUE TITLE
generated classes do not include type annotations

### ISSUE THREAD

**Issue by mfulton26** [google/auto#247]
Other than the `AutoValue` annotation itself should not generated `AutoValue_*` classes include the same annotations as the `abstract` class (except perhaps those annotations annotated with [`Inherited`](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Inherited.html))?

e.g. Given
```java
@Target(TYPE)
@Retention(RUNTIME)
public @interface Bar {...}
```
and
```java
@AutoValue
@Bar
public abstract class Foo {...}
```
AutoValue currently generates
```java
@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_Foo extends Foo {...}
```
but I'd like it to generate
```java
@Generated("com.google.auto.value.processor.AutoValueProcessor")
@Bar
final class AutoValue_Foo extends Foo {...}
```
.

Is there a reason not to do so?

Thanks.

**Comment by tbroyer** [comment]
See discussion in #187

**Comment by mfulton26** [comment]
Thanks. That looks like the same issue so I've subscribed to it and am closing this one.
