### ISSUE TITLE
inconsistent transitive maven deps for auto-factory

### ISSUE THREAD

**Issue by lukesandberg** [google/auto#249]
I was considering adding an AutoFactory dep to closure-templates but ran into this:

Dependency convergence error for com.google.auto:auto-common:0.4 paths to dependency are:
+-com.google.template:soy:2.5.0-SNAPSHOT
  +-com.google.auto.factory:auto-factory:1.0-beta2
    +-com.google.auto:auto-common:0.4
and
+-com.google.template:soy:2.5.0-SNAPSHOT
  +-com.google.auto.factory:auto-factory:1.0-beta2
    +-com.google.auto.service:auto-service:1.0-rc2
      +-com.google.auto:auto-common:0.3
]
	at org.apache.maven.plugins.enforcer.DependencyConvergence.execute(DependencyConvergence.java:131)
	... 22 more

auto-factory and auto-service disagree on the version of auto-common to use

**Comment by tbroyer** [comment]
The mysteries of Maven… auto-factory has a direct dependency on auto-common so its version "overrides" the one brought transitively by auto-service. Also, isn't auto-service in provided scope? I'd call it a bug in the enforcer plugin.

**Comment by lukesandberg** [comment]
i don't think auto-service is in the provided scope
https://github.com/google/auto/blob/master/factory/pom.xml#L52

though, i admit i know next to nothing about maven

**Comment by tbroyer** [comment]
You might have found a bug in auto-factory's pom then ;-)

**Comment by hgschmie** [comment]
This is actually a misunderstanding in dependency-convergence. If you want to fix it, the project running the dependency convergence needs to add a dependency management section to resolve this conflict.

This is IMHO not a auto value bug.

**Comment by lukesandberg** [comment]
I fixed by changing the auto pom... So I think this issue is moot
