### ISSUE TITLE
AutoValue Builder default values

### ISSUE THREAD

**Issue by tomrozb** [google/auto#258]
Looks like it's impossible to define default values when using `@AutoValue.Builder`. You have to define all the properties or you'll get:

```java.lang.IllegalStateException: Missing required properties: X```

Using @AutoValue without builder it possible to pass default values through constructor. With builder pattern it's not possible. It'd be nice to have such possibility. 

Any chance to provide such functionality?

**Comment by hannesstruss** [comment]
[The docs](https://github.com/google/auto/tree/master/value#default-values-with-builders) provide an example of how to implement default values with Builders.

**Comment by tomrozb** [comment]
@hannesstruss thanks, I haven't noticed that code when I was looking for solution.

**Comment by cxzhang2** [comment]
Hijacking this thread: @tomrozb can you explain how to pass defaults through a constructor with AutoValue?

**Comment by eamonnmcmanus** [comment]
The question isn't very clear, but perhaps you are wondering about something like this?

```java
@AutoValue
abstract class Animal {
  abstract String name();
  abstract int numberOfLegs();

  static Animal create(String name) {
    return create(name, OptionalInt.empty());
  }

  static Animal create(String name, int numberOfLegs) {
    return create(name, OptionalInt.of(numberOfLegs));
  }

  private static Animal create(String name, OptionalInt numberOfLegs) {
    int n = numberOfLegs.isPresent() ? numberOfLegs.get() : 4;  // this is the default
    return new AutoValue_Animal(name, n);
  }
}
```

**Comment by cxzhang2** [comment]
@eamonnmcmanus that's exactly what I was looking for, thank you!

**Comment by mb720** [comment]
Here's the updated link to the documentation on default values: [link](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#default)
