### ISSUE TITLE
@AutoService doesn't work in abstract class.

### ISSUE THREAD

**Issue by jpink** [google/auto#272]
The AutoService annotation must be placed in implementation class, not in abstract class. Otherwise I get
COMPILATION ERROR : 
-------------------------------------------------------------
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider my.pakage.AbstractProcessor could not be instantiated: java.lang.InstantiationException

It would be nice if you can have only one annotation for all of your processors.

**Comment by cgruber** [comment]
This is working as designed.  This is a false economy.  AutoService generates metadata about what concrete classes the ServiceLoader should load up, and it can't instantiate abstract classes, so it's not an appropriate usage.
