### ISSUE TITLE
AutoValue fails when a isFoo() method returns Boolean instead of boolean.

### ISSUE THREAD

**Issue by dballesteros7** [google/auto#275]
I believe it is because [this line](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L532) only checks for boolean.class.

Is there any particular reason why this doesn't check for Boolean.class as well? It would help when you have optional boolean parameters, i.e.

```java

@AutoValue
class Bar {
  @Nullable abstract Boolean isFoo();

  @AutoValue.Builder
   class Builder {
     abstract Builder setFoo(@Nullable Boolean foo);
     abstract Bar build();
   }
}
```

My workaround is to use boolean and always set a default builder with the value set to false, but it would be nice to be able to have the value unset and then be able to do validations in the build method, e.g. when validate parameters passed in a URL.

I can send a CL if this is a reasonable request.

Of course I could avoid this if I don't use the "is" prefix, but for some variables names this is better than "get" and is the convention in our code.

**Comment by eamonnmcmanus** [comment]
It's deliberate, since we're following a subset of the [JavaBeans conventions](https://docs.oracle.com/javase/tutorial/javabeans/writing/properties.html). There, the special `isFoo` case applies exactly to `boolean` and no other type.

As a practical matter, I think `@Nullable Boolean` is something of a code smell. Among other problems it means an unsuspecting user can write
```java
if (bar.isFoo()) {
  ...
}
```
which will blow up with a NullPointerException if `isFoo` returns null. You could indeed arrange for the value never to be null in the `build()` method, but that would lead readers of the code to wonder why it is `Boolean` and not `boolean`.

Although it's slightly clunky, you do have a way to know whether the `foo` property was specified:
```java
@AutoValue
public class Bar {
  public abstract boolean isFoo();

  public static Builder builder() {
    return new AutoValue_Bar.Builder();
  }

  @AutoValue.Builder
  public abstract class Builder {
    public abstract Builder setFoo(boolean foo);
    abstract boolean isFoo();

    abstract Bar autoBuild();
    
    public Bar build() {
      try {
        isFoo();
      } catch (IllegalStateException e) {
        setFoo(...logic_for_default_value_of_foo...);
      }
      return autoBuild();
    }    
  }
}
```

**Comment by dballesteros7** [comment]
Thanks! Definitely I like the approach below better to catch when the argument was not specified.

**Comment by riwnodennyk** [comment]
We may do it even simpler:

```
@AutoValue
public class Bar {
  public abstract boolean isFoo();

  public static Builder builder() {
    return new AutoValue_Bar.Builder();
  }

  @AutoValue.Builder
  public abstract class Builder {
    Builder(){
        setFoo(...logic_for_default_value_of_foo...);
    }

    public abstract Builder setFoo(boolean foo);

    abstract Bar build();
  }
}
```

**Comment by eamonnmcmanus** [comment]
@riwnodennyk, I think that is equivalent in practice to this:
```java
@AutoValue
public class Bar {
  public abstract boolean isFoo();

  public static Builder builder() {
    return new AutoValue_Bar.Builder()
        .setFoo(...logic_for_default_value_of_foo...);
  }

  @AutoValue.Builder
  public abstract class Builder {
    public abstract Builder setFoo(boolean foo);

    abstract Bar build();
  }
}
```

which is how we usually recommend structuring it. But I believe the original poster wanted to compute a default value only if one is not specified explicitly. If you define an initial value when the Builder is created then you can't know whether another value was provided later.
