### ISSUE TITLE
toBuilder methods shouldn't be passed to extensions

### ISSUE THREAD

**Issue by rharter** [google/auto#281]
Currently, the toBuilder methods are passed to extensions as properties, since the context is constructed before the builder methods are checked.  These methods should not be sent to extensions as properties.

**Comment by eamonnmcmanus** [comment]
Oops. :-)

**Comment by Rainer-Lang** [comment]
Any solution?

**Comment by rharter** [comment]
Since we keep pointing people here when they report this issue in the extension repos, the workaround is to implement the `toBuilder` method manually until this is fixed.

```java
public Builder toBuilder() {
  return return new AutoValue_Foo.Builder(this);
}
```

**Comment by eamonnmcmanus** [comment]
This is fixed in the latest snapshot.

**Comment by feinstein** [comment]
Why this isn't in the `Builder` [docs](https://github.com/google/auto/blob/master/value/userguide/builders.md)? Any limitations?

**Comment by eamonnmcmanus** [comment]
@feinstein I'm not sure what your question is. This issue was fixed nearly three years ago.

**Comment by feinstein** [comment]
@eamonnmcmanus my question was answered here: https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#to_builder

This doc is just "too deep" and I didn't find it sooner, my apologies.

**Comment by eamonnmcmanus** [comment]
We're open to suggestions on how to structure the documentation so that you might have found this more easily!

**Comment by feinstein** [comment]
Maybe include a reference to the How To for builders on the Readme?
