### ISSUE TITLE
[Value] Do not silently implements Serializable if one field is not serializable

### ISSUE THREAD

**Issue by jbgi** [google/auto#282]
Ideally Auto-Value annotation processor should fail with an error if an annotated class implements Serializable but one of its field does not.

**Comment by eamonnmcmanus** [comment]
Feel free to reopen if I am misunderstanding this, but it seems like a very marginal case. Even if the type of a field does not inherit from Serializable, the runtime type might. So the check would have to be something like: if the `@AutoValue` class implements Serializable then there must be no field whose type is a final class that does not implement Serializable, unless the `@AutoValue` class also implements Externalizable. That seems like a check that would only be helpful very occasionally. Is the suggestion triggered by a real case where it would have helped?

**Comment by jbgi** [comment]
Yeah that was a real case where the check would have help avoiding a bug: a ```Serializable``` ```@AutoValue``` class had a not ```Serializable``` ```@AutoValue``` field.
I think it would be useful to have a warning if there is a field that is not of interface type and that does not implements ```Serializable``` . And an error in case it is a ```@AutoValue``` / or final class.

But then I also plan to just stop using ```Serializable``` at all... so hopefully this will not be a problem anymore...
