### ISSUE TITLE
AutoValue should respect @Nullable annotations on types

### ISSUE THREAD

**Issue by philipp-classen** [google/auto#283]
AutoValue generates non-null runtime checks for all fields that are not annoted as "@Nullable". At the moment, "@Nullable" annotations using  JSR 308 type annotations are ignored. Thus, non-null checks will be generated for fields which are intended to be nullable.

---

For example, the Eclipse "@Nullable" annotation looks like this:

```
@Documented
@Retention(value=CLASS)
@Target(value=TYPE_USE)
public @interface Nullable
```
Source: http://help.eclipse.org/mars/index.jsp?topic=/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/annotation/Nullable.html

Note that it only defines "TYPE_USE" as Target. It is a new feature that is available since Java 8.

Before that, it was defined as follows:
```@Target({ ElementType.FIELD, ElementType.LOCAL_VARIABLE, ElementType.METHOD, ElementType.PARAMETER })```

AutoValue handles the old annotation fine, but ignores the new TYPE_USE based annotation. Consequently, it generates non-null runtime checks for all non-annotated fields, it is critical that detects "@Nullable" annotation.

Note: Mixing TYPE_USE and the older annotations (FIELD, LOCAL_VARIABLE, METHOD, PARAMETER) is not a good idea. Though it works in simple examples, it introduces ambiguity, for instance, when using it with arrays. Thus, Eclipse rightly decided against it.

**Comment by philipp-classen** [comment]
My colleague has an experimental patch to add support for type annotations. It uses the Java 8 API, but, in principle, it could be implemented in a Java 7 backward compatible way (using reflection).

We hope to find time to provide a pull request, so you can take a look at the idea.

**Comment by eamonnmcmanus** [comment]
Yes, I have an internal issue tracking this. As you point out, the need to have the code work on earlier Java versions means it isn't trivial, but it shouldn't be all that hard either.

**Comment by philipp-classen** [comment]
Please take a look at the patch in pull request #293

**Comment by eamonnmcmanus** [comment]
The patch in #293 has been incorporated into the latest snapshot.

**Comment by sudhirj** [comment]
Has this regressed in 1.5 and 1.5.1? I can't get `@Nullable` to work at all. Null checks are always being generated.

**Comment by eamonnmcmanus** [comment]
There are no differences between 1.5 and 1.5.1 that could explain that. Are you sure that is the only thing that has changed? Does it work using 1.5 and JDK9?

**Comment by sudhirj** [comment]
It's a little difficult to check 1.5.0 on JDK9 - there was a bug w.r.t to exensions and `@Memoized` which I use. So I can't really if that interfered with `@Nullable`. On 1.5.1 + JDK9 I see no errors or warnings, but just a flat refusal to remove null checks. Hold on, will post an example on a branch, it's an open source project.

**Comment by sudhirj** [comment]
On https://github.com/sudhirj/switchboard/pull/1/files I've added @Nullable annotations to the `board` and `choice` properties, and switched their order to establish that code is fact being regerated. But the null checks still remain.

**Comment by eamonnmcmanus** [comment]
I observe that the jar file for AutoValue 1.5.1 includes javax/annotation/Nullable.class, which seems like a very bad thing. I would suggest avoiding the use of `javax.annotation.Nullable` with Java 9, since the standard module that defines `javax.annotation` does not include that class and packages can't be split across modules. AutoValue treats any annotation called `@Nullable` the same way, regardless of what package it is in. You could use `org.checkerframework.checker.nullness.qual.@Nullable`, or you could define your own `@Nullable` like this:

```java
@Target(TYPE_USE)
@Retention(SOURCE)
@interface Nullable {}
```

Thanks for bringing this problem to our attention!

**Comment by sudhirj** [comment]
Thanks, the checkerframework looks useful in and of itself, will pull it in and try.

**Comment by cheister** [comment]
@sudhirj You might be running into the same problem as https://github.com/google/auto/issues/546

**Comment by sudhirj** [comment]
@cheister I think I am. My current workaround is to use the annotations on the checker framework, but is there any reason that javax.annotation isn't safe to use? Is that only for internal use inside Java or something?
