### ISSUE TITLE
AutoValue emits warning for properties even if they're consumed by Extensions

### ISSUE THREAD

**Issue by rharter** [google/auto#286]
The [current implementation](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L656) of AutoValue throws the following warning in `methodsToImplement()` for any abstract methods that don't take any parameters and return a value before extensions have had the chance to 

```
warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
```

A valid test case should be the following, but there's no such thing as `compilesWithoutWarning()`, though there totally should be.  

```java
  public void testDoesntRaiseWarningOnConsumedProperties() {
    JavaFileObject iface = JavaFileObjects.forSourceString("foo.bar.Dizzler", "" +
        "package foo.bar;\n" +
        "interface Dizzler {\n" +
        "  String dizzle();\n" +
        "}");
    JavaFileObject impl = JavaFileObjects.forSourceString("foo.bar.Baz", "" +
        "package foo.bar;\n" +
        "import com.google.auto.value.AutoValue;\n" +
        "@AutoValue public abstract class Baz implements Dizzler {\n" +
        "  abstract String foo();\n" +
        "}");
    assertAbout(javaSources())
        .that(ImmutableList.of(iface, impl))
        .processedWith(new AutoValueProcessor(ImmutableList.of(new FooExtension())))
        .compilesWithoutError().and().compilesWithoutWarning();
  }
```

**Comment by JakeWharton** [comment]
RE warnings asserts: https://github.com/google/compile-testing/issues/41

**Comment by eamonnmcmanus** [comment]
This shows up in particular with Parcelable, where you can write an extension that implements the `describeContents()` method, but AutoValue will still warn about it. There's a sequencing problem here: the extension can claim the `describeContents()` method, so it won't be considered as defining a property called `describeContents`; but the warning currently happens before the extension gets a chance to do that.

Regarding testing, [CompilationErrorsTest](https://github.com/google/auto/blob/master/value/src/test/java/com/google/auto/value/processor/CompilationErrorsTest.java) can be used to check that there are no warnings.

**Comment by rharter** [comment]
I agree with the sequencing, my thought was that we just have to move that validation after the properties are consumed by the extensions.

As for `CompilationErrorsTest`, I had considered that but noticed it is specifying the AutoValueProcessor directly. On second consideration I see that adding a test exception to the sources classpath should be enough for it to get picked up by the processor.  I'll take a look later.

**Comment by rharter** [comment]
Because of the way [CompilationTestErrors](https://github.com/google/auto/blob/master/value/src/test/java/com/google/auto/value/processor/CompilationErrorsTest.java#L259) compiles the source, I'm not sure how I can provide a test extension that the AutoValueProcessor will be able to pick up.  I'd presumably need to put the source on the classpath, but then also have the META-INF resource that tells ServiceLoader where to find it.  Any suggestions here?

**Comment by eamonnmcmanus** [comment]
Perhaps add logic to AutoValueProcessor that consults `processingEnv.getOptions()` to get the name of one or more classes to be added as an extension? Then you could pass
`-Acom.google.auto.value.ExtensionClass=com.whatever.ThingExtension` as a compiler option. This could possibly also replace the constructor that takes an `Iterable<? extends AutoValueExtension>`.

**Comment by rharter** [comment]
Correct me if I'm wrong, but that would require a not insubstantial change to the Processor simply for the sake of this style of test.  We still need to use the `ServiceLoader` to find extensions since that leads to super easy extension additions by users, so this would mean we'd have to append that list with one coming from the compiler options, simply to enable a test due to a shortcoming of compile-testing.

**Comment by eamonnmcmanus** [comment]
This should be fixed in the latest snapshot.

**Comment by naturalwarren** [comment]
What's the version of the latest snapshot - how can I consume it?

@eamonnmcmanus

**Comment by naturalwarren** [comment]
Found it in the POM. Thanks!
