### ISSUE TITLE
can not have create and a builder at the same time.

### ISSUE THREAD

**Issue by hgschmie** [google/auto#287]
this results in the create static method trying to call the `AutoValue_Foo` constructor which is now private because a builder is present.

the constructor should only be private if only a builder is present, but package private if other create methods are present.

Our use case is that there are places where a bean is created incrementally (from business logic code) and places where we want an uniform "all at once" approach is wanted (deserialization from JSON e.g.). 

The create method could use the builder but this requires a large amount of not-autogenerated boilerplate code.

**Comment by eamonnmcmanus** [comment]
AutoValue can't tell if there is a static factory method. It doesn't require such methods to be called `create`, and it can't look inside the code of a method to see whether the method calls the `AutoValue_Foo` constructor. Having said that, I'm not sure there's a really strong reason for the constructor to be private when a builder is present. Maybe it could be package-private whether or not there is a builder. Comments invited from @kevinb9n. :-)

**Comment by kevinb9n** [comment]
It's extremely important that AutoValue be extremely easy to learn and
reason about, and I'm a little wary of confusion we could be introducing if
we do this. As just one example: what will users assume about whether the
generated constructor is calling their validation method or not?  Perhaps
we can deal with that, but I suspect other little wrinkles like that could
be hiding too.

On Wed, Nov 18, 2015 at 2:41 PM, Éamonn McManus <notifications@github.com>
wrote:

> AutoValue can't tell if there is a static factory method. It doesn't
> require such methods to be called create, and it can't look inside the
> code of a method to see whether the method calls the AutoValue_Foo
> constructor. Having said that, I'm not sure there's a really strong reason
> for the constructor to be private when a builder is present. Maybe it could
> be package-private whether or not there is a builder. Comments invited from
> @kevinb9n <https://github.com/kevinb9n>. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/287#issuecomment-157888399>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by hgschmie** [comment]
@kevinb9n I understand the desire for simplicity. Right now, I can not have an explicit constructor (which would force callers to provide values for all the fields in the bean in an atomic fashion) *and* a build that would allow incremental construction and validation. So I resorted to having my create methods to use the builder which requires me to write the boilerplate code that I want to avoid.

Making the c'tor non-private would solve my problems very nicely. :-)

**Comment by hgschmie** [comment]
I assume you are opposed to a feature flag such as `@AutoValue(visibleConstructor=true)`, so I did not propose that. :-)

**Comment by eamonnmcmanus** [comment]
I think @kevinb9n's point about validation is crucial. If you are creating an instance through a builder then validation happens in your `build()` method (which typically forwards to a generated package-private `autoBuild()`). If you are creating an instance through a static factory method that calls the generated constructor then validation happens in the static factory method. That's why you must choose to create one way or the other, but not both.

Perhaps you could say a bit more about your use case. Are you generating `@AutoValue` classes? What's the objection to writing a static factory method like this:
```java
  public static Foo create(String bar, int baz, boolean buh) {
    return builder().bar(bar).baz(baz).buh(buh).build();
  }
```

**Comment by hgschmie** [comment]
This is how I am doing it today. The problem is that this created method is manual work. Calling the constructor is not.

The current use is that we serialize & deserialize value classes from the wire (where constructor-only works fine) but also need to have a builder based construction in code.

I understand @kevinb9n argument; it is simply a bummer that I need to duplicate the effort manually. Maybe have a way on how to create such a create method programmatically?

**Comment by eamonnmcmanus** [comment]
Hmm. This seems like too special a case for us to warp the main API for it. It might make a good example of an [extension](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/extension/AutoValueExtension.java). All that extension would do would be to render the constructor of the generated class visible. Without extensions, you have a hierarchy like this:

AutoValue_Foo → Foo

With extensions it can look like this:

AutoValue_Foo → $AutoValue_Foo → $$AutoValue_Foo → Foo

The immediate subclass of Foo (here $$AutoValue_Foo) is the one generated by AutoValue, and the others are generated by extensions. If your extension declares itself final then it gets to generate AutoValue_Foo. It's expected to declare a constructor with names and types corresponding to the properties, and to forward the constructor parameters to the superclass constructor. But it can make the constructor visible if it likes.

This might be overkill, though.

**Comment by hgschmie** [comment]
Yes, I could do this as an extension. However, you would need to release a version with the Extension API in that case. :-) (1.1 does not have it).

**Comment by hgschmie** [comment]
I am cool with closing this (#287) and my pull request proposal (#289) once 1.2 with extension support has been released.

**Comment by artem-zinnatullin** [comment]
>This seems like too special a case for us to warp the main API for it.

We have valid reasons (I think so :smile_cat:) to have both `create()` and `Builder` for one entity: an entity that can be created manually and automatically. Same as @hgschmie but different argumentation. 

**Why we want to have `create()`:**
To prevent unneeded memory allocations, GC pressure and tons of methods calls which need to be done via `Builder`. In our case, it's JSON deserialization and parsing from `android.database.Cursor`. Just imagine parsing thousands of objects via `Builder`, ew!

**Why we want to have `Builder`**:
To be able to write readable code when we need manual creation of an object. In our case, we mostly use builders in tests. Just imagine totally unreadable object creation code with method call and some meaningless values, ew!

Would be nice if we could have both `create()` and `Builder` and use one or another when appropriate.

TL;TR: `create()` when you need performance, `Builder` when you need readability.

Seems like a valid thing to have it in the core library isn't it? I guess, many of us use AutoValue for such purposes.

**Comment by artem-zinnatullin** [comment]
Any update on this (please)?

**Comment by eamonnmcmanus** [comment]
We hope to have a 1.2 release with provisional support for extensions Real Soon Now. I say "provisional" because we expect that the extensions API will change later and extensions may need to be adjusted to work with subsequent releases.

**Comment by rharter** [comment]
@eamonnmcmanus Are there planned changes, or just expecting that there might need to be some?

**Comment by eamonnmcmanus** [comment]
Expecting that there might need to be some.

**Comment by PaulWoitaschek** [comment]
Any news on this? I think its an unnecessary limitation right now. I need the constructor for mapping from my database. If I use the builder for so many objects, that will be a performance hit.

Therefore I can't use the builder which makes the regular creation from code a real mess when I force 15 parameters in a single static factory.

**Comment by eamonnmcmanus** [comment]
The Extension API referenced above is now stable. We'll probably release 1.3 Real Soon Now, but in any case the Extension API will not change between the current 1.3-rc2 and the final 1.3. So that is certainly one option.

**Comment by mengxianun** [comment]
Maybe you can do this
`@AutoValue
public abstract class Animal {

	public static Animal create(String name, int numberOfLegs) {
		return new AutoValue_Animal.Builder().name(name).numberOfLegs(numberOfLegs).build();
	}

	public abstract String getName();

	public abstract int getNumberOfLegs();

	public static Builder builder() {
		return new AutoValue_Animal.Builder();
	}

	@AutoValue.Builder
	public abstract static class Builder {
		public abstract Builder name(String value);

		public abstract Builder numberOfLegs(int value);

		public abstract Animal build();
	}
}`
