### ISSUE TITLE
AutoValue: Adding @Valid attribute to getter results in error

### ISSUE THREAD

**Issue by thehereward** [google/auto#288]
We want to annotate a getter on one of our classes with the @Valid annotation to allow cascading validation. AutoValue copies this annotation to the AutoValue class. This results in the following error message:

```
HV000131: A method return value must not be marked for cascaded validation more than once in a class hierarchy, but the following two methods are marked as such: public my.name.space.Parameters my.name.space.AutoValue_Class.getParameters(), public abstract my.name.space.Parameters my.name.space.Class.getParameters().
```

We are working around this by applying the annotation to the parameter in the factory method.

e.g.

``` java
@JsonCreator
public static Class create(@Valid Parameters parameters){ /* code */ }
```

It would be nicer if the @Valid were _not_ copied to the autovalue class so we could annotate the getting directly.

**Comment by JakeWharton** [comment]
There are equal (if not more) arguments for desiring annotations to be copied so this issue should be about figuring out how to configure the behavior in a declarative way that works for everyone.

**Comment by rharter** [comment]
I would argue there's much more need to have annotations copied than to
have them not copied, so I think copying annotations, at least as the
default behavior, is needed.

**Comment by eamonnmcmanus** [comment]
I assume we're talking about [javax.validation.Valid](https://docs.oracle.com/javaee/6/api/javax/validation/Valid.html) here. I don't see anything obvious about that that would allow AutoValue to guess that it shouldn't be copied. Other than having an explicit list of annotations not to copy, of course. As an alternative workaround, you could have a package-private alias for the property:

```java
@AutoValue
public abstract class Foo {
  public Parameters getParameters() {
    return getRealParameters();
  }

  /*not public*/ abstract Parameters getRealParameters();
  ...
}
```

That does make for messy names in toString(), and means you would have to do the same thing in the builder if you have one, so possibly the workaround meantioned by @thehereward is better.

**Comment by shtratos** [comment]
I've also encountered this issue and I used this workaround:
```java
@AutoValue
public abstract class Foo {
  public abstract Parameters getParameters();

  @Valid
  private Parameters getValidatedParameters() {
    return getParameters();
  }
  ...
}
```

This doesn't affect `toString()` or `Builder`.

The only downside is that in validation error message you get something like `validatedParameters[0].name is empty`, not `parameters[0].name is empty`

**Comment by eamonnmcmanus** [comment]
This should be addressable using `@CopyAnnotations` now (you can exclude annotations).
