### ISSUE TITLE
AutoValue has SOURCE RetentionPolicy

### ISSUE THREAD

**Issue by hgschmie** [google/auto#290]
Is there a deeper meaning behind this? Right now, this makes it really hard for tooling to look at code and do special things if a class is autogenerated. (e.g. I want to dynamically discover the correct getters to reflect on a auto generated bean). 

As the use case: 

A public bean A has a `public abstract String foo()` method. The AutoValue_A bean also has a `public abstract String foo()` method, however the class itself is package private. 

When calling `object.getClass().getDeclaredMethods()` on an instance of `AutoValue_A`, there will be a method object representing the `foo()` method. However, calling invoke on that method with the instance as parameter will result in an `IllegalAccessException`. What is necessary is to find the super class (which is `A`) and use this class object to do getDeclaredMethods() and then call invoke on the method object which represents `foo()` in the `A` object.

So what I suggested to do is to traverse up the super class chain until the class having the `@AutoValue` annotation is encountered, then call `getDeclaredMethods()` on that class object.

`AutoValue` has SOURCE retention policy. Bummer. Is it possible to make that `RUNTIME`?

**Comment by kevinb9n** [comment]
On Mon, Nov 23, 2015 at 4:33 PM, Henning Schmiedehausen <
notifications@github.com> wrote:

> Is there a deeper meaning behind this? Right now, this makes it really
> hard for tooling to look at code and do special things if a class is
> autogenerated.
>
One of AutoValue's core values is that no one should ever need to care
whether a type was implemented using AutoValue or some other means.


> A public bean A has a public abstract String foo() method. The
> AutoValue_A bean also has a public abstract String foo() method, however
> the class itself is package private.
>
> When calling object.getClass().getDeclaredMethods() on an instance of
> AutoValue_A, there will be a method object representing the foo() method.
> However, calling invoke on that method with the instance as parameter will
> result in an IllegalAccessException. What is necessary is to find the
> super class (which is A) and use this class object to do
> getDeclaredMethods() and then call invoke on the method object which
> represents foo() in the A object.
>
> So what I suggested to do is to traverse up the super class chain until
> the class having the @AutoValue annotation is encountered, then call
> getDeclaredMethods() on that class object.
>
Sounds like a general quirk with Java reflection. First question is, of
course, whether you can get away with setAccessible(true). But the other
generalized solution is to examine *all* supertypes that declare an
override-compatible signature, until you find a public one. It shouldn't
matter whether that's the @AutoValue class or not, should it?


-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by eamonnmcmanus** [comment]
It is indeed a quirk with Java reflection. You don't need to identify the `@AutoValue` class to invoke the method. You just need to find any ancestor where a method with the same signature is visible. The method in question is public, so you can just use Class.getMethod on each public ancestor until you find one where it doesn't throw NoSuchMethodException. That logic will be widely useful. I've had to do the same thing in other contexts that have nothing to do with AutoValue_Foo classes.

**Comment by hgschmie** [comment]
@eamonnmcmanus The problem is not that the method is not public. It is public just fine. The instance is not. AutoValue_Foo is package private.

Given @kevinb9n's comment, it seems that this is an ideological issue, so I won't bother any further; we will simply use a patched version of autovalue.

**Comment by kevinb9n** [comment]
Hang on. Before starting your own fork, have you *tried* our solution?

We're aware your method is public and your class is not. You expect to be
able to call the method because it also exists on *some* supertype
that *is* public.
Cool: so just find that class, and call it.


On Tue, Nov 24, 2015 at 9:35 AM, Henning Schmiedehausen <
notifications@github.com> wrote:

> @eamonnmcmanus <https://github.com/eamonnmcmanus> The problem is not that
> the method is not public. It is public just fine. The instance is not.
> AutoValue_Foo is package private.
>
> Given @kevinb9n <https://github.com/kevinb9n>'s comment, it seems that
> this is an ideological issue, so I won't bother any further; we will simply
> use a patched version of autovalue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/290#issuecomment-159350234>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by hgschmie** [comment]
You changed the visibility to class in f95b232; referencing this issue would have been nice.

**Comment by eamonnmcmanus** [comment]
We didn't change the visibility to `RUNTIME` though, and we still don't think AutoValue should be visible to reflection.
