### ISSUE TITLE
Is It Safe To Share AutoValue types With Clients?

### ISSUE THREAD

**Issue by CraigJPerry** [google/auto#308]
Hey Guys,

Are AutoValue objects designed to be safely shared with clients of my library or are they supposed to be restricted for internal only use?

E.g. If i give a client an object of an AutoValue type i made, i should assume they can still change the value without me knowing?

```
package com.craigjperry.testdrive.autovalue;

import com.google.auto.value.AutoValue;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class SubclassAbuseTest {

    @AutoValue
    abstract static class Pair<L, R> {
        // <L, R> re-defined since you can't reuse a class's generic type parameter in a static method
        static <L, R> Pair<L, R> of(L left, R right) {
            return new AutoValue_SubclassAbuseTest_Pair<>(left, right);
        }

        abstract L left();

        abstract R right();
    }

    // Could a malicious party mess with your immutable value types?
    static class AttackOnPair extends Pair<Integer, Integer> {
        private static Integer left;
        private static Integer right;

        AttackOnPair(Integer left, Integer right) {
            AttackOnPair.left = left;
            AttackOnPair.right = right;
        }

        static AttackOnPair of(Integer left, Integer right) {
            return new AttackOnPair(left, right);
        }

        @Override
        Integer left() {
            return left;
        }

        @Override
        Integer right() {
            return right;
        }

        void setLeft(Integer left) {
            this.left = left;
        }
    }

    @Test
    public void referenceToImmutableValueTypeChangesUnexpectedly() throws Exception {
        Pair<Integer, Integer> immutablePairReference = AttackOnPair.of(1, 1);
        assertEquals(new Integer(1), immutablePairReference.left());
        ((AttackOnPair) immutablePairReference).setLeft(2);
        assertEquals(new Integer(1), immutablePairReference.left());
    }
}
```

**Comment by tbroyer** [comment]
Would adding a package-private zero-arg constructor prevent subclassing outside the package?

Also, if you document that the contract of the class is to be immutable and a “client” implements it as mutable, then it's breaking the contract and anything could happen. Same is true for implementations of `equals` and `hashCode`: even if another implementation is immutable but has an incompatible implementation of those methods, things can break.

**Comment by JakeWharton** [comment]
The README recommends the package ctor :+1:

**Comment by eamonnmcmanus** [comment]
In the example, the classes are package-private, which means that their default constructors are too. I'm not sure I really understand the original question. If the classes were public, we do certainly recommend adding a package-private constructor, which means that, when operating within normal Java rules, "malicious" code outside the package can't subclass it. But could malicious code be added to the same package? Could it use reflection to change the purportedly final properties of AutoValue_SubclassAbuseTest_Pair? I think the best we could say is that _if_ the AutoValue class has a package-private constructor and _if_ there is a SecurityManager that disallows [setAccessible](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AccessibleObject.html#setAccessible-boolean-) and _if_ any untrusted code is loaded by a different ClassLoader than the one that loaded the AutoValue class, then yes, it should be impossible for malicious code to make a mutable subclass.

I think, though, that most people in the know have given up on the idea of running untrusted and trusted Java code in the same JVM. Along with all those _if_s in the previous paragraph is an implicit _if_ you trust the JVM to be secure, and as history has shown it is really too complicated a beast for that trust to be justified.

**Comment by eamonnmcmanus** [comment]
I don't think there's anything we can usefully do here.
