### ISSUE TITLE
AutoValue: Support String[] array

### ISSUE THREAD

**Issue by vanniktech** [google/auto#320]
Right now it is not supported as only primitive arrays are supported. Would love to have support for String[] aswell.

If you're also interested in this I could start an implementation.

**Comment by eamonnmcmanus** [comment]
We deliberately don't support object arrays, including `String[]`. The reasons are [here](https://github.com/google/auto/blob/master/value/userguide/howto.md#object_array). Do you have a use case that isn't addressed well by using a `List<String>` instead of a `String[]`?

**Comment by vanniktech** [comment]
Yeah I can understand those reasons. Unfortunately I'm on Android where I don't have Guava Included hence I don't get `ImmutableList` etc and therefore `String[]` in this case is easier. The method `List<String> myStrings()` everyone can call and modify the contents of it.

If AutoValue would support `String[]` array and return a copy each time you call the method the class is still immutable.

**Comment by JakeWharton** [comment]
Everyone can modify the contents of String[] as well. You can use
unmodifiableList with a defensive copy in your create method for an easy
immutable version of a list.

**Comment by kevinb9n** [comment]
The point is that with an array, AutoValue would *know* how to just insert
'.clone()' all over the place. Unfortunately, it has been established that
automatic array cloning on get is NOT what most users want, and it was
backed out some months ago. We tried pretty hard to argue for it but our
arguments clearly didn't hold water with users.

Niklas: for what it's worth, Guava does support Android...


On Mon, Apr 11, 2016 at 2:39 PM, Jake Wharton <notifications@github.com>
wrote:

> Everyone can modify the contents of String[] as well. You can use
> unmodifiableList with a defensive copy in your create method for an easy
> immutable version of a list.
>
> On Mon, Apr 11, 2016, 5:36 PM Niklas Baudy <notifications@github.com>
> wrote:
>
> > Yeah I can understand those reasons. Unfortunately I'm on Android where I
> > don't have Guava Included hence I don't get ImmutableList etc and
> > therefore String[] in this case is easier. The method List<String>
> > myStrings() everyone can call and modify the contents of it.
> >
> > If AutoValue would support String[] array and return a copy each time you
> > call the method the class is still immutable.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/auto/issues/320#issuecomment-208573287>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/320#issuecomment-208574137>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by vanniktech** [comment]
To prevent anyone from modifying `String[]`, AutoValue could use `Arrays.copyOf()`. `Collections.unmodifiableList()` would work though it kinda defeats the purpose of AutoValue in that point because you have to remember to either use `ImmutableList` or `unmodifiableList` to get immutable auto values.

For now I'll stick to `unmodifiableList` though `String[]` support would still be nice in my opinion.

@kevinb9n I know that Guava supports Android but I don't feel like adding 15k methods to my android project just to get immutable classes.

**Comment by kevinb9n** [comment]
On Mon, Apr 11, 2016 at 2:54 PM, Niklas Baudy <notifications@github.com>
wrote:

> To prevent anyone from modifying String[], AutoValue could use
> Arrays.copyOf().
>
Same exact thing as .clone() discussed above.



> Collections.unmodifiableList() would work though it kinda defeats the
> purpose of AutoValue in that point because you have to remember to either
> use ImmutableList or unmodifiableList to get immutable auto values.
>
> For now I'll stick to unmodifiableList though String[] support would
> still be nice in my opinion.
>
> @kevinb9n <https://github.com/kevinb9n> I know that Guava supports
> Android but I don't feel like adding 15k methods to my android project just
> to get immutable classes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/320#issuecomment-208578537>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
