### ISSUE TITLE
Gradle DSL method not found: 'compileOnly()'

### ISSUE THREAD

**Issue by achooley** [google/auto#324]
[project gradle](https://github.com/google/auto/files/227489/build.txt)
[module.gradlet](https://github.com/google/auto/files/227491/module.txt)

After added all dependencies i have this error:"Gradle DSL method not found: 'compileOnly()'"

**Comment by tbroyer** [comment]
Which version of Gradle are you using? (`compileOnly` is _native_ in 2.12)
Is your `conpileOnly` line in the `dependencies` block?
Is this an Android project or simple `java` project? (Did you properly applied the `java` plugin?)

**Comment by chuleiO** [comment]
Thx for quick response. This i default android project.  
Yes, This is my block (take from AutoValue instruction)
Gradle v 2.12. And in Studio Setting i`am use local gradle distribution with path to gradle 2.12 
![ss 2016-04-20 at 11 34 29](https://cloud.githubusercontent.com/assets/1076205/14668380/a98ccf7e-06ec-11e6-9d7c-3891a73380d3.png)
![ss 2016-04-20 at 11 38 38](https://cloud.githubusercontent.com/assets/1076205/14668381/a9916b06-06ec-11e6-98be-d8e738366149.png)

**Comment by tbroyer** [comment]
You may need the `android-apt ` plugin instead of `net.ltgt.apt` plugin; and IIRC use `provided` instead of `compileOnly`.

**Comment by chuleiO** [comment]
Thxs for help. You are right. After added ` classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'` and 
`apply plugin: 'com.neenbedankt.android-apt'`  all compile correctly 
But why previous version dont work. I done all the same to  https://github.com/google/auto/blob/master/value/userguide/index.md and https://plugins.gradle.org/plugin/net.ltgt.apt

**Comment by tbroyer** [comment]
Android projects are really a special kind of Gradle projects, and the `net.ltgt.apt` has no support for them.

**Comment by ronshapiro** [comment]
Declaring bug bankruptcy on this super old bug. This all changed in Gradle anyway.
