### ISSUE TITLE
Why isn't AutoValue a separate project/repo ?

### ISSUE THREAD

**Issue by adi1133** [google/auto#325]
AutoValue seems to have a huge following recently, it is growing at a different rate than the other Auto projects.

Keeping AutoValue in a shared repository clutters the GIT log, the issue tracker and the github releases section.

There are other projects that have much less code than this one and have a standalone repo: RxRelay, Timber and RxReplayingShare come to mind.

**Comment by kenzierocks** [comment]
Should probably be closed in favor of #374.
