### ISSUE TITLE
AutoFactory does not handle varargs parameters

### ISSUE THREAD

**Issue by zstewar1** [google/auto#326]
I'm trying to convert an existing type to be partially injected using autofactory, but our existing constructors and client code makes use of varargs to pass in differing numbers of arguments.

For example:
```java
@AutoFactory
class MyClass {
    public MyClass(@Provided InjectedParameter ip, RepeatedParameter... rp) {
        // ...
    }
}
```

However the signature of the corresponding `create` method is: `MyClassFactory.create(RepeatedParameter[] rp)` which rather defeats the point.

It's possible to work around this by changing the signature to accept a `List<RepeatedParameter>` and using `Arrays.asList()`, but it would be better if AutoFactory just supported varargs parameters directly.

**Comment by gk5885** [comment]
Yeah, that sounds totally reasonable.
