### ISSUE TITLE
AutoValue.java RentionPolicy(RetentionPolicy.SOURCE)

### ISSUE THREAD

**Issue by williamwebb** [google/auto#331]
If there is no downside to increasing the retention level it would be extremely helpful to have this annotation retained at the Runtime for Deserialization purposes.

As shown [here](https://gist.github.com/JakeWharton/0d67d01badcee0ae7bc9), currently to achieve deserialization an additional annotation is required. Which while this works requires users to know to use this annotation. If AutoValue.java were retained at runtime there would be a concrete relationship that could be used and enforced by the AutoValue annotation processor.

**Comment by eamonnmcmanus** [comment]
I'm not sure this is sufficiently strong motivation. The retention is SOURCE because this is an implementation detail. Clients of an AutoValue class should neither know nor care that it is one.

Assigning to @kevinb9n for a second opinion.

**Comment by JakeWharton** [comment]
There's also https://github.com/rharter/auto-value-gson/ now which uses the built-in extension mechanism to achieve the same effect as my Gist without reflection.

**Comment by williamwebb** [comment]
@JakeWharton only reasoning for not going with that option is it again requires the uses of AutoValue to know to add the static method to return the TypeAdapter. For something that would ideally be transparent.

**Comment by kevinb9n** [comment]
I think that extension or another like it is the right place to work this out.

Éamonn's statement, "Clients of an AutoValue class should neither know nor care that it is one", could be fairly described as THE founding principle of AutoValue. The thing that made us realize our idea was different from all the rest. The annotation is not even @Documented, let alone visible to non-source-level tools.

**Comment by williamwebb** [comment]
👍
