### ISSUE TITLE
Support using superinterfaces/superclasses for builder return values

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#335]
For my use case, I have interfaces that define methods very close to what an `AutoValue` builder uses, but since they are only interfaces I don't apply `AutoValue.Builder` directly to them. I have subclasses that are abstract and are annotated with the builder annotation. I also don't have generics for the `<B extends Builder<B>>` case, since it would be useless in my case since the subclasses are implementation details. The processor throws an exception telling me that I must return the same type as what I put AutoValue.Builder on, but I think it would be suitable for it to return a superinterface as well. What do you think?

N.B.: This explanation might not be very clear, so I have written a sample [here](https://gist.github.com/kenzierocks/fd670c6ed492991d279845d8d1e8a708).

**Comment by eamonnmcmanus** [comment]
I'm having difficulty understanding the use case. You have a Builder whose callers won't actually call `build()`? The `sendData()` method in the sample seems like a surprising thing to have in a builder.

*Maybe* if the `@AutoValue.Builder` inherits every one of its methods, including the `build()` method, from an ancestor `Ancestor` then we could accept that the methods of `Ancestor` would return `Ancestor`. It seems kind of like a corner case, though.

Meanwhile you do have the option of restating all of the abstract methods with the correct return type. So in the sample, `Builder` would include this:
```java
@Override
public abstract Builder data(String data);
```

**Comment by kenzierocks** [comment]
Yes, I just realized my use case is a little weird. I might just fork auto/value to fit it. Thanks for your tips.
