### ISSUE TITLE
Unnecessary semicolon in generated AutoAnnotation_*#appendEscaped

### ISSUE THREAD

**Issue by dborowitz** [google/auto#337]
Our project has the following @AutoAnnotation method:
https://gerrit.googlesource.com/gerrit/+/136aab1f0abea5675af7fcac4eac2e90f15e61fa/gerrit-sshd/src/main/java/com/google/gerrit/sshd/Commands.java#50

Building this with auto-value 1.2 produces the following appendEscaped method:

```java
  private static void appendEscaped(StringBuilder sb, char c) {
    switch (c) {
    case '\\':
    case '"':
    case '\'':
      sb.append('\\').append(c);
      break;
    case '\n':
      sb.append("\\n");
      break;
    case '\r':
      sb.append("\\r");
      break;
    case '\t':
      sb.append("\\t");
      break;
    default:
      if (c < 0x20) {
        sb.append('\\');
        appendWithZeroPadding(sb, Integer.toOctalString(c), 3);;
      } else if (c < 0x7f || Character.isLetter(c)) {
        sb.append(c);
      } else {
        sb.append("\\u");
        appendWithZeroPadding(sb, Integer.toHexString(c), 4);
      }
      break;
    }
  }
```

Note the extra semicolon in the `if (c < 0x20)` block.

(If you want to reproduce this locally by building the whole Gerrit project, you'll need to follow the [Eclipse project setup instructions](https://gerrit-review.googlesource.com/Documentation/dev-eclipse.html), then `cat .apt_generated/com/google/gerrit/sshd/AutoAnnotation_Commands_named.java`. Unfortunately, while the non-IDE Buck-driven build is easier to set up, it doesn't produce the generated source code as an output.)

**Comment by tbroyer** [comment]
The extra semi comes from https://github.com/google/auto/blob/30cea621cb6610acca6b39cd5f0d6805e9293546/value/src/main/java/com/google/auto/value/processor/autoannotation.vm#L346 (really strange that you don't reproduce it with the Buck build then)

**Comment by dborowitz** [comment]
To clarify the comment about the buck build: you can't see the bug because
it doesn't save the generated source files anywhere, they are compiled into
the relevant output jar and then discarded.

**Comment by eamonnmcmanus** [comment]
I've already fixed this in Google's internal version, coincidentally last Thursday, so the fix should appear at the next push.
