### ISSUE TITLE
Auto value 1.3 not consuming properties

### ISSUE THREAD

**Issue by naturalwarren** [google/auto#343]
I'm using auto value 1.3 and am consuming a property that isn't a builder or getter. This results in a Autovalue warning and error at compile time:

```
AuthenticationPreferences.java:15: error: PreferencesExtension wants to consume a property that does not exist: setRealtimeAuthToken
public abstract class AuthenticationPreferences implements Preferences {
                ^
AuthenticationPreferences.java:35: warning: Abstract method is neither a property getter nor a Builder converter, and no extension consumed it
    public abstract void setRealtimeAuthToken(String token);
                         ^
1 error
1 warning

```

This is what my consume properties method looks like:

```
public Set<String> consumeProperties(Context context) {
        return Sets.newHashSet("setRealtimeAuthToken");
    }
```

I'm not sure why I'm getting the warning and the error. Am I not using consume properties properly? I followed @rharter's example in auto-parcel.

**Comment by gabrielittner** [comment]
That's because `setRealtimeAuthToken` isn't a property. You have to use `consumeMethods(Context)` to consume regular methods.

**Comment by naturalwarren** [comment]
This sounds right thanks Gabriel.

**Comment by naturalwarren** [comment]
Gradle in my IDE was still syncing 1.2, be sure when you switch to 1.3 to clean and re-sync!
