### ISSUE TITLE
BooleanSubject failure messages are confusing when subject is null

### ISSUE THREAD

**Issue by dborowitz** [google/auto#350]
This test:
```java
Boolean b = null;
assertThat(b).isFalse();
```
results in "The subject was expected to be false, but was true". No it's not; it's null.

Similarly, this test:
```java
Boolean b = null;
assertThat(b).isTrue();
```
results in "The subject was expected to be true, but was false".

**Comment by JakeWharton** [comment]
I think you meant to file this on https://github.com/google/truth/
