### ISSUE TITLE
How to use auto-value with firebase 9.2.0 in Android?

### ISSUE THREAD

**Issue by epool** [google/auto#354]
I want to use [auto-value][1] with [firebase 9.2.0+][2]. I have the following code:

    @AutoValue
    public abstract class Office {

        public static Builder builder() {
            return new AutoValue_Office.Builder();
        }

        public abstract double latitud();
        public abstract double longitud();

        @AutoValue.Builder
        public static abstract class Builder {

            public abstract Builder latitud(double latitud);
            public abstract Builder longitud(double longitud);

            public abstract Office build();

        }

    }

But when I make to call this `Office office = childDataSnapshot.getValue(Office.class);` I am getting this error:

    com.google.firebase.database.DatabaseException: No properties to serialize found on class com.example.app.model.Office

Somebody have an idea why I am getting this error and how to solve it? I read that firebase is no longer using `jackson` for json serialization. So I am not sure how to specify a kind of `@JsonProperty("latitud")` I have used `@PropertyName` unsuccessfully.

I also tried rename the abstract methods like `public abstract double getLatitud();` and after that the error is the next one:

    java.lang.InstantiationException: Can't instantiate abstract class com.example.app.model.Office

So I am not sure how to solve this.

  [1]: https://github.com/google/auto/tree/master/value
  [2]: https://firebase.google.com/

**Comment by gk5885** [comment]
This is a question, not a bug..  Those are more appropriate for StackOverflow.  Please post your question there.
