### ISSUE TITLE
AutoValue should respect re-abstracted toString method as a property

### ISSUE THREAD

**Issue by progressnerd** [google/auto#357]
I often just want a small tiny type that wraps a string, and I don't think it should be necessary to create a new abstract property getter beyond the toString method. For example, I'd like to just do this:

```java
@AutoValue
abstract class FirstName {
  static FirstName create(String s) {
    return new AutoValue_FirstName(s);
  }
  public abstract String toString();
}
```

Unfortunately, the generated class constructor doesn't accept the "toString" argument --- in this example it accepts no arguments. I understand I can add a new abstract method to represent the string property, but supporting this use case as is, would be nice.

**Comment by JakeWharton** [comment]
You can specify a non-public property named something like
`explicitToString()` and then define `toString()` as a final and delegate
to this property.

**Comment by progressnerd** [comment]
@JakeWharton Yes, I know, I do that currently. Just wondering if it could be directly supported as is.

**Comment by JakeWharton** [comment]
What about extensions that want to replace toString? Like our redacted one:
https://github.com/square/auto-value-redacted

**Comment by rharter** [comment]
It sounds like you're simply describing an immutable String, as opposed to
a type.

In your example, what should the AutoValue constructor do with the string
you pass in?

Even on a normal model object, you'd have to create a field to assign it
to.  Is that any different than making an abstract property?

**Comment by progressnerd** [comment]
@rharter No, I don't want a String. I want a super-easy [tiny type](http://www.markphelps.me/2014/12/09/tiny-types.html) to wrap a String and make my code less "stringly-typed". Right now, that can be achieved with:

```java
@AutoValue
abstract class FirstName {
  static FirstName create(String s) {
    return new AutoValue_FirstName(s);
  }
  abstract asString();
  public final String toString() {
    return asString();
  }
}
```
This is fine, just wondering if @AutoValue could do a tad bit better and eliminate the need for the superfluous `asString` method.

**Comment by rharter** [comment]
I see what you mean.  What happens when you want a tiny type for an `int`?  Or a `boolean`?  

I would argue this is outside the scope of AutoValue, since it's really targeted at full blown immutable types, but seems like it might be a good candidate for it's own annotation processor.

**Comment by progressnerd** [comment]
@rharter AutoValue already gives me everything one might want when creating a tiny type for an integer or boolean. My "FirstName" example above was probably not too motivating, so I'll attempt a better one: a type to represent a "unique id"  --- this is often an important standalone concept where you really want a separate static type to represent it rather than merely passing around a primitive. If your unique id is a glorified integer, then AutoValue already gives you everything you could possibly want, i.e.:

```java
@AutoValue
abstract class UniqueId {
  static UniqueId of(int intValue) {
    return new AutoValue_UniqueId(intValue);
  }

  abstract int toInt();  // alternatively called "intValue" or "asInt"
}
```

Same story with wrapping other primitives. It is really the special-ish case of wrapping a string, because the toString method already exists and I'd prefer to just use that rather than live with two methods that convert my type to a string. See, if I do this:

```java
@AutoValue
abstract class UniqueId {
  static UniqueId of(String stringValue) {
    return new AutoValue_UniqueId(stringValue);
  }

  abstract String asString();
}
```

Now my type now has two similar-looking methods --- asString() and toString() --- that return different things, which could be surprising. For presumably the same reason, the JDKs Path class doesn't offer a method to get the Path as a String other than toString(). To avoid that surprise, I'm more likely to make toString delegate to asString:

```java
@AutoValue
abstract class UniqueId {
  static UniqueId of(String stringValue) {
    return new AutoValue_UniqueId(stringValue);
  }

  abstract String asString();

  public String toString() {
    return asString();
  }
}
```

Which, again, is OK and not the end of the world, but it's extra boilerplate that isn't conceptually necessary, and it means some callers within the same package might differ in terms of which ones they call, which has a small negative impact on readability of my code. A (small?) tweak to make AutoValue treat a re-abstracted toString() method as a property would avoid this.

**Comment by JakeWharton** [comment]
You could write an extension which does this that uses an annotation or marker interface, enforces only a single property, and automatically generates a `toString()` that delegates to that single property.
```java
@AutoValue @TinyType
abstract class UniqueId {
  static UniqueId of(String stringValue) {
    return new AutoValue_UniqueId(stringValue);
  }

  abstract String value();
}
```
which would generate:
```java
public final class AutoValue_UniqueId extends $AutoValue_UniqueId {
  @Override public String toString() {
    return String.valueOf(value());
  }
}
```

**Comment by progressnerd** [comment]
@JakeWharton That's an interesting idea that would definitely cover some of my use cases. On balance, I think I prefer my original proposal because:

1. The advantage of the @TinyType behavior on non-String values is pretty limited. It just gives you a toString that lacks the class name and that's it, which may not necessarily be what you want anyway. Non-string wrappers don't have the same toString/asString conflict to avoid. I'm not sure I would personally bother using it for anything other than a String wrapper.

2. Treating an abstract toString as a property is more general purpose with perhaps other applications, my tiny type example being just one. Another example is when you really want the toString value to be created once and cached rather than re-computed on every call. In that case, you could mark it as abstract and pre-compute it once in your factory method, like this:

```java
@AutoValue
abstract class MyType {
  static MyType  create(Object property1, Object property2, ...) {
    String s = expensiveToStringComputation(property1, property2, ...);
   return new AutoValue_MyType(property1, property2, ..., s);
  }

  abstract Object property1();
  abstract Object property2();
  //...

  public abstract String toString();
}
```

By the way, thank all of you for responding so quickly with feedback and alternatives. It's nice to bounce this idea off open ears.

**Comment by rharter** [comment]
Thanks for clarifying the problem, that really helps make it clearer.

The only real problem here is that the term `toString` is a reserved word, right?  The fact that AutoValue always tries to treat it as a "to string" method, instead of letting you co-opt for some other purpose?

Presumably that update would be applicable to all other reserved method names, too, right?  So `hashcode` and `equals`?

I understand your motivation, and it's a neat concept (I haven't heard of TinyTypes before), though I'm not sure that I'm entirely on board with coopting `toString` like that since it seems to break the contract of the general usage of `toString`.  That being said, do people really care about the contract for `toString`? :)

**Comment by progressnerd** [comment]
@rharter AutoValue already lets you override toString, and this would just be a shortcut to doing that. And it isn't co-opting it for another purpose: the Object#toString contract is that it returns a String representation of the object, and it would still be doing that. This is all functionality that is already available and perfectly correct, it just requires more boilerplate, which is the problem AutoValue exists to fix.

I think there's an argument for treating re-abstracted hashCode methods the same way. There are already people who want to pre-compute and memoize particularly expensive hash codes, and treating a re-abstracted hashCode method as a property would be an avenue to let them do that.

What about re-abstracted equals methods? Now that's just craziness :) I would be fine with a hard error in that case, because I can't see what possible point it would serve.

In the end, we would be left with a 1:1 relationship between abstract methods in the @AutoValue type and properties of that type, which would be a nice consistency.

**Comment by eamonnmcmanus** [comment]
To summarize the proposal as I understand it. Today, you can write `public abstract String bar()` to define a string property `bar`. Then you supply the value that that property should have in the constructor, `new AutoValue_Foo("a bar")`. But this does not work for `public abstract String toString()`. That does not define a string property `toString`. The proposal would be (1) to allow it to do so, but (2) to treat it as a special case in that we don't generate the usual `toString()` implementation (which would produce something like `"Foo{toString=whatever}"`) but instead just have `toString()` return the string that is passed to the constructor.

That feels a bit too special-caseish to me. Every new feature like this has a certain weight, in that it adds to the burden of people who are trying to understand how AutoValue works. We'd have to add a paragraph like the one I just wrote to the user manual, and that would be that much more information that people have to absorb.

Concerning memoized `hashCode()`, we'll shortly be publishing an extension that will be enabled by default, and will allow you to apply `@Memoized` to any no-arg method in an AutoValue type. Then the method will be overridden with an implementation that caches its value after the first call. As a special case, you can redeclare `hashCode()` or `toString()` as `@Memoized abstract`, and their values will be cached after the first call. Or, you can declare your own expensive `toString()` and have it be `@Memoized`. I think that will cover some of the use cases discussed here, as well as being applied to many others.
