### ISSUE TITLE
GWT Serialization, nesting problem

### ISSUE THREAD

**Issue by methylene** [google/auto#362]
When nesting B inside A like this

``` java
@AutoValue
@GwtCompatible(serializable = true)
abstract class A {

    @AutoValue
    @GwtCompatible(serializable = true)
    abstract static class B {
        abstract String s();
        static B create(String s) {
            return new AutoValue_A_B(s);
        }
    }

    abstract B b();

    static A create(String b) {
        return new AutoValue_A(B.create(b));
    }
}
```

Then

> com.google.gwt.user.client.rpc.SerializationException: could not get type signature for class B

happens whenever A is used in an RPC call. This also happens if B is "normal" Serializable or IsSerializable.

There is a workaround (include B in "Dummy"): http://stackoverflow.com/questions/138099/how-do-i-add-a-type-to-gwts-serialization-policy-whitelist

I'm using GWT 2.8.0-beta1 and AutoValue 1.3-rc2.

**Comment by kluever** [comment]
We are dropping GWT support in ~6 months: https://groups.google.com/forum/#!topic/guava-discuss/ZLpBaYAtUl4
