### ISSUE TITLE
Validation with extension

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/auto#366]
When Using AutoValue with extensions its no longer possible to perform additional validation as you no longer control the object creation.
When you do not use extensions you can just check something like
```java
if(value < 0) throw new IllegalArgumentException()
```
inside your create method, but with extensions this cannot be done. It is important to have a way to validate objects upon creation.

**Comment by rharter** [comment]
Why can't you validate them in your static factory methods?  Are you concerned that when an object is generated from Gson, for instance, it won't be validated?

**Comment by PaulWoitaschek** [comment]
I validate them in my static factory, but for example [auto-value-with](https://github.com/gabrielittner/auto-value-with) does not use my static factory.

I'm talking about extensions, not gson.

**Comment by rharter** [comment]
I was simply using Gson as an example of an [extension](https://github.com/rharter/auto-value-gson).

Just like any other static factory methods, I think the general idea is that you'd have to validate the data before it goes to the creating method (whether it's a constructor, extension based static factory method, or builder).

```java
@AutoValue public abstract class User {
  public abstract String id();
  public abstract String name();
  public abstract String email();

  public User withEmail(String email) {
    if (!Validator.isValidEmail(email)) {
      throw new IllegalArgumentException("Must supply a valid email address");
    }
    return withEmailInternal(email);
  }
  abstract User withEmailInternal(String email);
}
```

**Comment by PaulWoitaschek** [comment]
good idea!
