### ISSUE TITLE
Allow @Nullable Builder accessors for nonnull values

### ISSUE THREAD

**Issue by ZakTaccardi** [google/auto#369]
Calling `Person.builder().build()` throws an `IllegalStateException - Property "name" has not been set`

```
@AutoValue
public abstract class Person {

    //note, this in non null
    public abstract String name();

    public static Builder builder() {
        return new AutoValue_Person.Builder();
    }

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder name(String s);

        public Person build() {
            if (name() == null) { //exception thrown here
                name("null");
            }

            return autoBuild();
        }

        @Nullable //calling this throws an illegal state exception requiring that name be set, even though this builder accessor is marked @Nullable
        abstract String name();

        @Nullable
        abstract Person autoBuild();


    }
}

```

Accessing the builder's properties should be allowed if the builder accessor is marked as `@Nullable`, even if the respective AutoValue property is non-null.

**Comment by PaulWoitaschek** [comment]
You can set the default value while creating the builder:

```java
public static Builder builder() {
  return new AutoValue_Person.Builder()
    .name("null");
}
```

**Comment by ZakTaccardi** [comment]
But if you call `builder().name(null)`, the default value is removed.  My use case is a null `name` provided by an API. Obviously I can workaround this by manually checking the fields, but I would like AutoValue''s builder validation to be able to handle this, automatically.

**Comment by PaulWoitaschek** [comment]
I wrote `.name("null")`like you did in your example. 

I don't understand - why can't you set the default name in your `static builder()` method?

**Comment by ZakTaccardi** [comment]
`.name("null")` (`String`) and `.name(null) (`null` value) are different. So even if I provide a default  `"null"` `String` value with the builder like you suggested, that default value could be overridden by someone setting a `null` name. I don't want to allow the possibility of someone overriding the default value with a `null`.

My request is that I want to be able to run a *final* validation pass on nulls using `build()/`autoBuild()`.

**Comment by PaulWoitaschek** [comment]
Then make your name method not public and use a proxy method that handles your logic.

```java
@AutoValue.Builder public static abstract class Builder {

    abstract Builder name(String s);
    
    public Builder safeName(String name){
      name(name==null ? "defaultValue" : name);
    }

    public abstract Person build();
}
```

**Comment by eamonnmcmanus** [comment]
I think what you want is this:

```java
@AutoValue.Builder
public static abstract class Builder {
  public abstract Builder name(String s);

  abstract Optional<String> name();

  abstract Person autoBuild();

  public Person build() {
    if (!name().isPresent()) {
      name("null");
    }
    return autoBuild();
  }
}
```

We do document this [here](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#normalize) but possibly it could be a bit more discoverable.

**Comment by ansman** [comment]
@PaulWoitaschek, @eamonnmcmanus I have the same problem and since I'm using AV for Android I can't use `Optional`. The problem I'm having is the following:
```
@AutoValue
public abstract class MyObject {
    public static final String TYPE_A = "type_a";
    public static final String TYPE_B = "type_b";
    public static final String TYPE_BOTH = "type_both";

    public abstract String type();
    public static Builder builder() {
        return new AutoValue_MyObject.Builder();
    }

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder type(@Nullable String type);
        @Nullable
        public abstract String type();

        public Builder add(@NonNull MyObject object) {
            if (type() == null) { // crash
                type(object.type());
            } else if (!type().equals(object.type())) {
                type(TYPE_BOTH);
            }
            return this;
        }

        public abstract MyObject build();
    }
}
