### ISSUE TITLE
Split auto-value projects into top-level github.com/google projects

### ISSUE THREAD

**Issue by cgruber** [google/auto#374]
The auto-projects do not release together, have only some connection through auto-common (but no more or less than, say, Dagger has through auto-common), and are one project with a mix of issues, many of which are irrelevant to followers of only one sub-project. Owing to this, we're going to split auto up into their own first-class github project under the google/ organization.

Auto-value, being the most common google/auto project will remain here, and the auto project will be renamed auto-value.  

The other projects will be respectively migrated with full commit history to auto-factory, auto-service, and auto-common respectively.  The sub-projects, in their own home, will have their sibling projects deleted from their repo, and they will be moved up one directory level.

At this point, we'll manually replicate open auto-factory/common/service issues in their new homes, and will close those issues here. Existing pull requests will be closed, but since the repository history is intact, pull requests can simply merge in the new changes, then rebase and squash, if the authors wish.

This process will happen fairly gradually, as we have to coordinate this on both the github and google internal side (to keep syncing cleanly).
- Auto Common
  - [ ] Move repository
  - [ ] Migrate issues and close pull requests
  - [ ] Fix and validate syncing rules
  - [ ] Build and test in new repository
  - [ ] Delete from google/auto 
- Auto Factory
  - [ ] Move repository
  - [ ] Migrate issues and close pull requests
  - [ ] Fix and validate syncing rules
  - [ ] Build and test in new repository
  - [ ] Delete from google/auto 
- Auto Service
  - [ ] Move repository
  - [ ] Migrate issues and close pull requests
  - [ ] Fix and validate syncing rules
  - [ ] Build and test in new repository
  - [ ] Delete from google/auto 
- Auto Value
  - [ ] Pull up value project to top level
  - [ ] Fix and validate syncing rules
  - [ ] Build and test in new repository

**Comment by kluever** [comment]
Do we ever intend on splitting these apart?

**Comment by eamonnmcmanus** [comment]
I think at this stage it's fair to admit that we're not going to make this split. While it would undoubtedly be a better final state, it's not _enough_ better to justify the work and churn that would be involved.
