### ISSUE TITLE
No way to set Optional Property of type T to Optional.empty()

### ISSUE THREAD

**Issue by mearly87** [google/auto#384]
If an optional property has been set, there is no way to set it back to `Optional.empty()` because the setter uses `Optional.of()` instead of `Optional.ofNullable()`

For example if you have this class:

```
import com.google.auto.value.AutoValue;
import java.util.Optional;
import javax.annotation.Nullable;

public class Test {

  @AutoValue
  public static abstract class Item {

    public abstract Optional<String> getName();

    public static Builder builder() {
      return new AutoValue_Test_Item.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    public static abstract class Builder {

      public abstract Builder setName(@Nullable String name);
      public abstract Item build();

    }
  }

  public static void main(String args[]) {
    Item item = Item.builder().setName("Test").build();
    item.toBuilder().setName(null).build();
  }
}
```

This will result in a NullPointerException. Is there no way to set this property to empty in the builder? Seems like a valid use case to me.

**Comment by eamonnmcmanus** [comment]
At the least, this deserves to be a FAQ. I answered it [just yesterday](https://github.com/google/auto/pull/328#issuecomment-249699544) in another context. In short, the way to achieve what you want is this:

```
@AutoValue.Builder
public static abstract class Builder {
  public Builder setName(@Nullable String name) {
    return setName(Optional.ofNullable(name));
  }
  abstract Builder setName(Optional<String> name);
  public abstract Item build();
}
```

**Comment by kenzierocks** [comment]
https://github.com/google/auto/pull/353 fixes this issue, I believe.

**Comment by eamonnmcmanus** [comment]
Thanks, Kenzie, yes it can.
