### ISSUE TITLE
Calling final builder step without providing required arguments

### ISSUE THREAD

**Issue by androidfred** [google/auto#385]
STEPS TO REPRODUCE
Call final builder step (usually .build()) without providing required arguments

EXPECTED RESULT
Compiletime error

ACTUAL RESULT
Runtime error

MISC
Instead of returning the builder on all steps, return the next required argument. When there are no required arguments left, return the builder. See eg http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

**Comment by jbgi** [comment]
looks like a duplicate of #370.

**Comment by androidfred** [comment]
Apologies for filing duplicate.

**Comment by androidfred** [comment]
@jbgi For what it's worth, the style of implementation I reference is different.
