### ISSUE TITLE
JSON to AutoValue POJO

### ISSUE THREAD

**Issue by robohorse** [google/auto#395]
Sorry for this issue, but i want to say about [plugin](https://github.com/robohorse/RoboPOJOGenerator) for IDEA and Android Studio, witch supports AutoValue POJO generation :)

**Comment by eamonnmcmanus** [comment]
I think that's interesting, but I don't see that there anything in particular we should do in the AutoValue project. If there is, please feel free to reopen this issue saying what it is.
