### ISSUE TITLE
hashcode overflow

### ISSUE THREAD

**Issue by hanwen** [google/auto#396]
this is with 

maven_jar(
  name = 'auto_value',
  artifact = 'com.google.auto.value:auto-value:1.3-rc1',
  sha1 = 'b764e0fb7e11353fbff493b22fd6e83bf091a179',
)

but I don't see it in the fixed issues for v 1.4:

https://bugs.chromium.org/p/gerrit/issues/detail?id=4672&q=autovalue&colspec=ID%20Type%20Stars%20Milestone%20Status%20Priority%20Owner%20Summary

$ bazel build gerrit-sshd:sshd

$ unzip -c bazel-out/local-fastbuild/bin/gerrit-sshd/libsshd-gensrc.jar com/google/gerrit/sshd/AutoAnnotation_Commands_named.java | grep 127
        ((127 * 111972721) ^ (value.hashCode()));

java int is signed 32-bits, max 2G. 127*111972721 is 14G.

This triggers an error-prone warning.

**Comment by eamonnmcmanus** [comment]
This issue is indeed fixed in 1.4-rc1. We haven't written a list of fixed issues for 1.4 yet.
