### ISSUE TITLE
@Memoized expects javax.annotation.Generated to be present

### ISSUE THREAD

**Issue by blipinsk** [google/auto#398]
The new `MemoizeExtension` expects `javax.annotation.Generated` to be present in the project. 
If you don't have it, build fails.

![generated_missing](https://cloud.githubusercontent.com/assets/6371716/19720486/9b6ce75a-9b6e-11e6-8851-561f7b47ae70.png)

Need a PR for that?

**Comment by blipinsk** [comment]
Since those are just like few lines of code, here's a pull request 😉

**Comment by commonsguy** [comment]
Note that his is particularly relevant for Android, which does not have `javax.annotation.Generated`, meaning that `@Memoize` appears to be unusable on Android.

**Comment by eamonnmcmanus** [comment]
This is a duplicate of #503, which is fixed in AutoValue 1.5.1.
