### ISSUE TITLE
Use compareTo instead of equals for BigDecimal

### ISSUE THREAD

**Issue by loriopatrick** [google/auto#411]
Inside of the generated code for the equals method, `this.num.equals(that.num())` is used for the BigDecimal type.

BigDecimal.equals will fail for numerically equivalent values if their accuracies differ. http://stackoverflow.com/questions/6787142/bigdecimal-equals-versus-compareto

Is there anyway to have the generated code use `compareTo(that) == 0` instead of the `equals`?

**Comment by eamonnmcmanus** [comment]
One option in cases like this is to wrap the object in another one that has the desired behaviour for `equals`. In the case of BigDecimal, though, it's not clear to me what you could use for `hashCode()` to preserve the property that equal objects must have equal hash codes. I think the best you can do is to convert to Double and use the `hashCode()` from that. That means that all sufficiently big or small numbers will have equal hash codes.

```java
@AutoValue
public abstract class Foo {
  abstract WrappedBigDecimal wrappedNumber();  // not public
  public BigDecimal number() {
    return wrappedNumber().bigDecimal();
  }

  public static Foo create(BigDecimal number) {
    return new AutoValue_Foo(new WrappedBigDecimal(number));
  }
}

class WrappedBigDecimal {
  private final BigDecimal bigDecimal;
  WrappedBigDecimal(BigDecimal bigDecimal) {
    this.bigDecimal = bigDecimal;
  }

  BigDecimal bigDecimal() {
    return bigDecimal;
  }

  @Override public boolean equals(Object that) {
    return that instanceof WrappedBigDecimal
        && ((WrappedBigDecimal) that).bigDecimal.compareTo(bigDecimal) == 0;
  }

  @Override public int hashCode() {
    return Double.hashCode(bigDecimal.doubleValue());
  }

  @Override public String toString() {
    return bigDecimal.toString();
  }
}
```

**Comment by eamonnmcmanus** [comment]
I don't think this is an issue, as such. `BigDecimal.equals` has just as valid a claim as `BigDecimal.compareTo` to be used in the generated `equals` method. The proposed workaround is probably adequate for when `compareTo` is better.
