### ISSUE TITLE
Allow customizing error behaviour for missing elements in BasicAnnotationProcessor

### ISSUE THREAD

**Issue by grandstaish** [google/auto#415]
If processing is over and there are still unprocessed elements, I'd like to be able to override the default error message. For reference, the current message is:

```
<processor_name> was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
```

I'd like to be able to defer elements for reasons other than dependencies not being resolved, and then post-process (if they still haven't been processed) give a more helpful message to users so they can solve the issue. Does this sound like something you'd consider? 

Thanks for the library!

**Comment by gk5885** [comment]
This is already supported.  From `BasicAnnotationProcessor`

"`Each {@code ProcessingStep} can defer elements by including them in the set returned by {@link ProcessingStep#process(SetMultimap)}; elements deferred by a step will be passed back to that step in a later round of processing.`"

**Comment by grandstaish** [comment]
@gk5885  I know I can defer elements, I want to customize the error message post processing. Currently the `BasicAnnotationProcessor` handles this entirely by itself using the `reportMissingElements` method (which is private).
