### ISSUE TITLE
autovalue for class in own library gives Constructor cannot be applied Error- AIDL

### ISSUE THREAD

**Issue by RajuSE** [google/auto#424]
I have Following parcelable "Ingredient" class in my library.

````
import android.os.Parcel;
import android.os.Parcelable;

import com.google.auto.value.AutoValue;

@AutoValue
public abstract class Ingredient implements Parcelable {

    private String name;
    private int quantity;
    private String ingreType;

    public Ingredient(String name, int quantity, String ingreType) {
        this.name = name;
        this.quantity = quantity;
        this.ingreType = ingreType;
    }

    public static Ingredient create(String name, int quantity, String ingreType){
        return new AutoValue_Ingredient(name,  quantity, ingreType);
    }

    abstract String getName();
}`
````

After Adding that library in the dependency, project is successfully building.
But At runtime I am getting:
>Error:(22, 16) error: constructor AutoValue_Ingredient in class AutoValue_Ingredient cannot be applied to given types;
required: String
found: String,int,String
reason: actual and formal argument lists differ in length
&
>Error:(122, 50) error: cannot find symbol variable CREATOR &
>Error:(9, 20) error: constructor Ingredient in class Ingredient cannot be applied to given types;
required: String,int,String
found: no arguments
reason: actual and formal argument lists differ in length

**Comment by ronshapiro** [comment]
You are writing your own constructor and fields - autovalue does that for you. Try removing those. 

You also have an error for needing a `CREATOR` field for auto-value-parcel to succeed.

**Comment by RajuSE** [comment]
Oops I removed constructor. But about CREATOR error, Since I am using AutoValue for AIDL purpose, facing issue https://github.com/rharter/auto-value-parcel/pull/92 which seems to have no solution or workaround. Sadly I have to now move back to old Parcelable boilerplate code.

**Comment by eamonnmcmanus** [comment]
It appears that the issue is with AIDL and/or auto-value-parcel, rather than with AutoValue *per se*. Let me know if I'm wrong about that and I'll reopen the issue.

**Comment by CoolMind** [comment]
For those who is seeking an error with this response. I also caught it, in my case I had to add `abstract` to every field and add brackets:

    @SerializedName("id")
    public abstract Integer id();
    @SerializedName("name")
    public abstract String name();
