### ISSUE TITLE
Document @AutoAnnotation

### ISSUE THREAD

**Issue by dimo414** [google/auto#430]
[`@AutoAnnotation`](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/AutoAnnotation.java) doesn't appear to be mentioned anywhere in the auto/value user guide. It's certainly a niche / power-user feature, but it'd be nice to at least mention its existence, even if just to link to the javadocs.

**Comment by tbroyer** [comment]
It's documented at https://github.com/google/auto/blob/57dfad360306619a820e6aae4a14a1aa67c29299/value/userguide/howto.md#annotation

**Comment by dimo414** [comment]
Weird, I swear I looked, sorry about that.
