### ISSUE TITLE
Support using interfaces for the <B extends Builder<B>> case

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#432]
Right now, only `abstract class`es can benefit from the change made in https://github.com/google/auto/commit/c689fc914bda4fb39000894a02d71263a7352438. Is there any way to make it support interfaces as well, so I don't have to change all my builders just to take advantage of this? 

Test case:
```java
import com.google.auto.value.AutoValue;

@AutoValue
abstract class AV {
    interface SuperBuilder<B extends SuperBuilder<B>> {
        B foo(String foo); // Error: Setter methods must return AV.Builder
    }

    @AutoValue.Builder
    interface Builder extends SuperBuilder<Builder> {
        Builder bar(String bar);
        AV build();
    }

    abstract String getFoo();
    abstract String getBar();
}
```

**Comment by eamonnmcmanus** [comment]
That works fine for me. My guess is that you are using Eclipse. I've added workarounds to AutoValue for many Eclipse bugs in the past, but for [this one](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481555) you'll have to wait until it is fixed in Eclipse. That will apparently be in 4.7.

**Comment by kenzierocks** [comment]
Yes, I am using Eclipse. Thanks for the related bug report!
