### ISSUE TITLE
Can AutoValue filter field that return null or empty list ?

### ISSUE THREAD

**Issue by JungleTian** [google/auto#435]
for example:
`[
    {
        "data": {
            "tabs": [{"foo":123}]
        },
        "id": 100001,
        "style": "a"
    },
    {
        "data": {
            "tabs": [] // this is  empty
        },
        "id": 100002,
        "style": "b"
    }
]`

when the `tabs` return null or empty array , then continue.

result :
`[
    {
        "data": {
            "tabs": [{"foo": 123}]
        },
        "id": 100001,
        "style": "a"
    }
]`

**Comment by eamonnmcmanus** [comment]
It's not very clear what you are asking. I think the answer is no, though. AutoValue doesn't have any logic for filtering. If you're using it in conjunction with a JSON library, that library might have such logic. In that case you should ask there.

**Comment by JungleTian** [comment]
@eamonnmcmanus  thanks a lot
