### ISSUE TITLE
auto-factory beta4 now has runtime dependency

### ISSUE THREAD

**Issue by ben-manes** [google/auto#436]
In prior releases the generated code had no runtime dependency on the auto-factory jar. It was therefore best used as,

```gradle
  compileOnly "com.google.auto.factory:auto-factory:$version"
```

But in beta4 the generated code relies on `com.google.auto.factory.internal.Preconditions`. This changes the above to be `compile`. The previous behavior seemed intentional.

**Comment by eamonnmcmanus** [comment]
That does seem kind of gratuitous. There's just one small method coming from that dependency. Couldn't it be put in the generated code instead?

**Comment by ronshapiro** [comment]
I think the right answer is to split the processor from the source. We could put that method in each factory, but that seems unnecessary.

**Comment by JakeWharton** [comment]
The method is only a null check. Seems like it could be inlined into the generated code instead of bothering with a method call at all.

**Comment by ben-manes** [comment]
In beta3 there were no null checks. It also seems that it could code generate the argument name, rather than (or in addition to) the less helpful index.

**Comment by ronshapiro** [comment]
The index was done for users of Proguard (so the names wouldn't leak, if necessary).

**Comment by ben-manes** [comment]
Oh, right. thanks.

**Comment by ronshapiro** [comment]
Are there objections to just splitting the artifacts? I think that's what conceptually makes the most sense, and what has been requested for autovalue has well.

For the record, I'm open to having some flag or something to indicate that we should use parameter names instead of indices.

**Comment by JakeWharton** [comment]
But for AutoValue it's the source-only annotations which are only used at
compile-time and the processor and it's dependencies which go on a
different classpath as a desired separation. I want the same separation in
factory too.

This is a runtime component, however, which is entirely new and a different
problem than the annotation split. None of the Auto* libraries currently
have a runtime and adding one for such a trivial thing seems excessive.

**Comment by eamonnmcmanus** [comment]
I'm inclined to agree with @JakeWharton. In `@AutoAnnotation` for example (which is part of AutoValue), we [add](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/autoannotation.vm#L278) whatever support functions are needed in the generated code. Wouldn't an approach like that be viable here too?

**Comment by ronshapiro** [comment]
What's the difference in having one runtime method and a source-retention annotation, versus generating that one method in each file and a source-retention annotation?

To me it just seems unnecessarily wasteful to duplicate it when the cost of having a compile time dependency is so little (assuming that the processor code is split out). 

We could also generate the preconditions file if it doesn't exist, and if multiple compilation units generate it, the class files will be identical. In my mind that's worse than just including the file at runtime, but better than including the method in each file or inlining the null check.

**Comment by JakeWharton** [comment]
> What's the difference in having one runtime method and a source-retention annotation, versus generating that one method in each file and a source-retention annotation?

The former imposes that all users of the tool add the runtime dependency and include it for all downstream consumers. The latter keeps the tool as a compile-only utility that imposes nothing on downstream consumers.

> To me it just seems unnecessarily wasteful to duplicate it when the cost of having a compile time dependency is so little (assuming that the processor code is split out).

The method is only two lines long. It's not like it's complicated logic or a long method. If you can't afford to inline those then you shouldn't be using any of the Auto* libraries since they force the use of two classes instead of one which is far more costly.

**Comment by ronshapiro** [comment]
`1.0-beta5` is released and fixes this
