### ISSUE TITLE
Copy Javadoc into generated Builder classes

### ISSUE THREAD

**Issue by nikclayton** [google/auto#438]
It would be very useful if AutoValue could copy any documentation from the abstract getters in to the Builder methods it creates.

For example, given the following class:

```
@AutoValue
public abstract class Foo {
  /** Some useful documentation for this field... */
  public abstract String id();

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder id(String id);
    public abstract Foo build();
  }
}
```

The generated builder's id() method should have the same `/** Some useful documentation for this field... */` comment.

**Comment by eamonnmcmanus** [comment]
It's an interesting idea, but I'm not sure that it would always work very well. What if the doc comment looks like this:

```java
  /** Returns the identifier of this Foo. */
  public abstract String id();
```

That would look strange if applied to the setter.

**Comment by toolforger** [comment]
Javadoc already automatically does this.
See https://stackoverflow.com/a/15906009/6944068 .

**Comment by eamonnmcmanus** [comment]
@toolforger, @nikclayton was asking for doc comments to be copied from the getter method (`Foo.id()`) to the implementation of the setter method (`AutoValue_Foo.Builder.id(String)`). Javadoc won't do that.

**Comment by eamonnmcmanus** [comment]
I don't think we're going to do anything here unless we can come up with an unobtrusive way to avoid the sort of problem I mentioned [above](https://github.com/google/auto/issues/438#issuecomment-284550787). I don't see how to do that, but we can reopen this issue if someone has a good idea.

**Comment by toolforger** [comment]
Ah, now I understand.
If I look at a Builder's setter, I can easily find the corresponding getter, so I never considered this a problem worth solving. (I still do not, actually. A competent Java programmer should be able to find that. Javadoc on getters and setters is mostly a waste of everybody's time.)
