### ISSUE TITLE
Can the final generated AutoValue class be made public?

### ISSUE THREAD

**Issue by autovalue** [google/auto#440]
As per the autovalue [template](https://github.com/google/auto/blob/5c23ef9b8e1201ec3ea998682f9297d3f59aff36/value/src/main/java/com/google/auto/value/processor/autovalue.vm#L27) the generated class is set to have package level visibility by default:
`final class AutoValue_Model`

One of the libraries I'm using relies on providing the class type to work.

Passing `Model.class` into the library didn't work because the object itself has a class of `AutoValue_Model` causing the library to throw a "class not registered" exception. And it wouldn't make sense to force the library to look up the object hierarchy for a match.

And trying to reference `AutoValue_Model` from my presenter package won't work because of the class' visibility.

Would it be possible to provide some way to make the generated classes public via an annotation parameter so edgecases like this can be handled.

Any further feedback is welcome. Thanks in advance.

**Comment by tbroyer** [comment]
How about exposing the class on your auto class itself?

```java
@AutoValue
public abstract class Model {
  public static final Class<? extends Model> ACTUAL_CONCRETE_CLASS = AutoValue_Model.class;
```

**Comment by autovalue** [comment]
Thanks for the quick reply, that's a pretty clever workaround. That approach gets me past the registration stage, but I still need to access the class so it can be referenced inside a callback method like this:

```java
//...
onItemBound(AutoValue_Model.class, new OnItemBoundCallback<AutoValue_Model>() {
    @Override
    public void itemBound(@NonNull AutoValue_Model model) {
        picasso.load(model.image());
    }
});
//...
```

**Comment by lowasser** [comment]
Can you hack around that part with raw types, perhaps? =\

**Comment by autovalue** [comment]
@lowasser, I don't think so, the example was simplified to reduce the code, the actual callback requires extra parameters and the type parameters must match.

The method definition of the callback is:
```java
public <S extends BindRule<T>, T> void onItemBound(@NonNull Class<T> clazz, @NonNull OnItemBoundCallback<T, S> callback);
```

and I need to pass in:
```java
onItemBound(AutoValue_Model.class, new OnItemBoundCallback<AutoValue_Model, ModelRule>() {
    @Override
    public void itemBound(@NonNull ModelRule modelRule, @NonNull AutoValue_Model model) {
        // do stuff
    }
});
```

**Comment by autovalue** [comment]
Any news on supporting this functionality?

**Comment by eamonnmcmanus** [comment]
It is straightforward to write an AutoValue extension that will do this. It could either do it always, or when it detects a custom annotation like `@PublicConstructor` or whatever on the `@AutoValue` class. The idea would be that it would just need to output a class like this:

```java
public final class AutoValue_Foo extends Foo {
  public AutoValue_Foo(String bar, int baz) {
    super(bar, baz);
  }
}
```

**Comment by autovalue** [comment]
I'm afraid I'm currently not familiar enough with the autovalue API/annotation processors to write an extension from scratch in a non-trivial fashion.

I was initially under the impression that the final AutoValue class was always generated using [autovalue.vm](https://github.com/google/auto/blob/5c23ef9b8e1201ec3ea998682f9297d3f59aff36/value/src/main/java/com/google/auto/value/processor/autovalue.vm) as a template. But on inspecting the [code](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/extension/AutoValueExtension.java#L198) further, this doesn't seem to be the case.

I can try my hands on it over the weekend, but would be greatly appreciated if someone with more experience with this could help me out.

**Comment by eamonnmcmanus** [comment]
Here are a couple of starting points:
* [This test](https://github.com/google/auto/blob/master/value/src/test/java/com/google/auto/value/processor/ExtensionTest.java#L654) shows how to make an extension that is just an empty subclass. You would just need to insert "public" before the class declaration and before the constructor declaration.
* [The standard MemoizeExtension](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/extension/memoized/MemoizeExtension.java) shows another style of code generation, and uses `@AutoService` to ensure that the extension gets the required META-INF/services so that AutoValue can find it.

**Comment by autovalue** [comment]
Thanks for pointing me in the right direction. I'll see how I get on over the weekend.

**Comment by j1mmi** [comment]
@autovalue I want to do something similar that requires being able to reference the generated class outside the package, did you get anywhere on this?
