### ISSUE TITLE
AutoValue method build()

### ISSUE THREAD

**Issue by JWBlueLiu** [google/auto#445]
why add judgement in build()？
*e.g*
```
        @Override
        public Story build() {
            String missing = "";
            if (id == null) {
                missing += " id";
            }
            if (title == null) {
                missing += " title";
            }
            if (!missing.isEmpty()) {
                throw new IllegalStateException("Missing required properties:" + missing);
            }
            return new AutoValue_Story(
                    this.id,
                    this.title);
        }
```
how can i set some default value to id or title

**Comment by JWBlueLiu** [comment]
standard builder pattern doesn't like this

**Comment by lowasser** [comment]
https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#default covers how to add a default value to a builder.  Does that help?

**Comment by JWBlueLiu** [comment]
@lowasser 
why method build need to check value is null
this is what i want to know
and title maybe is null

**Comment by jbduncan** [comment]
@JWBlueLiu If I've understood your question correctly, it's because the default value of object fields and variables in Java (that is, if they aren't explicitly set with a value) is null.

Is this the sort of answer you were looking for?

**Comment by JWBlueLiu** [comment]
@jbduncan 
yes, this is what i want to express

**Comment by eamonnmcmanus** [comment]
If you want null to be allowed for a property, you can mark it `@Nullable`. Here `@Nullable` can be any `@Nullable` annotation, such as `javax.annotation.Nullable` from [JSR 305](https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305). Suppose the `Story` class looks like this:

```java
@AutoValue
public abstract class Story {
  @Nullable public abstract String id();
  @Nullable public abstract String title();

  public static Builder builder() {
    return new AutoValue_Story.Builder();
  }

  @AutoValue.Builder
  public abstract class Builder {
    public abstract Builder id(String id);
    public abstract Builder title(String title);
    public abstract build();
  }
}
```

Then you can write `Story.builder().build()` and you will get a `Story` where the `id` and `title` properties are both null.
