### ISSUE TITLE
Require Java 8 for running AutoValue

### ISSUE THREAD

**Issue by eamonnmcmanus** [google/auto#449]
Up until now we have ensured that AutoValue would compile and run on Java 6 and would generate code that itself compiles on Java 6. In https://github.com/google/auto/issues/448 I am proposing that we drop the requirement that the generated code can compile on Java 6, and instead target Java 7. However, generating code that can run on Java 7 does not require that it can be *compiled* on Java 7. It can perfectly well be compiled on a later platform with `-source 7 -target 7 -bootclasspath <rt.jar-from-7>`. I am therefore proposing that, after AutoValue 1.4, we allow the source code of AutoValue itself to use Java 8 fully.

**Comment by eamonnmcmanus** [comment]
This requirement is now in place.

**Comment by bogdandrutu** [comment]
Hey @eamonnmcmanus I think I may understand the reason behind moving to java7 from java6, but jumping to java8 will make any product/library to not be able to run on Android at all. Android still has to support a lot of Java7 devices. What is the story for that?

**Comment by eamonnmcmanus** [comment]
You can still compile code with `-source 7 -target 7` so that it can run on Android. The only change is that the *compiler* you use must be a Java 8 compiler. That should be the case for all modern development environments, including Android ones.

**Comment by rkraneis** [comment]
You might want to mention that in the Readme. It is not immediately apparent, that the generated code will be Java 7 compliant and compilable with these source/target settings.
