### ISSUE TITLE
Vote on IntelliJ fix for annotation-processor sources in gradle projects

### ISSUE THREAD

**Issue by tkruse** [google/auto#458]
Sorry if this is spam.
IntelliJ IDEA has a bug when trying to import gradle projects using annotation-processor generated sources. I think that may cause users to avoid using AutoValues.

Please vote for this to be fixed:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-124090

Close this ticket without further comment if you like.

**Comment by eamonnmcmanus** [comment]
Well, I don't think we can do anything about that issue here, and calls for ballot-stuffing do seem a little out of place. But, this will hopefully be useful for people who have hit the same problem and are Googling for a solution.
