### ISSUE TITLE
When I rebuild the demo that got a error !

### ISSUE THREAD

**Issue by e-hai** [google/auto#459]
"... access nested builders while building?"

**the code:** 

@AutoValue
public abstract class Animal {
  public abstract String name();
  public abstract Species species();

  public static Builder builder() {
    return new AutoValue_Animal.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setName(String name);
    public abstract Species.Builder speciesBuilder();
    public abstract Animal build();
  }
}

@AutoValue
public abstract class Species {
  public abstract String genus();
  public abstract String epithet();

  public static Builder builder() {
    return new AutoValue_Species.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setGenus(String genus);
    public abstract Builder setEpithet(String epithet);
    public abstract Species build();
  }
}

**the error:**
`Error:(21, 41) : Method looks like a property builder, but its return type is not a builder for an immutable type in com.google.common.collect`

**Comment by eamonnmcmanus** [comment]
I think that means you are using an old version of AutoValue. The current version doesn't have that error message.

**Comment by e-hai** [comment]
@eamonnmcmanus 
The version is
 `provided 'com.google.auto.value:auto-value:1.3'`
`apt 'com.google.auto.value:auto-value:1.3'`

**Comment by eamonnmcmanus** [comment]
The current version is 1.4 and that's what you need if you want to use a property builder for a nested `@AutoValue` class.

**Comment by e-hai** [comment]
thx : )
