### ISSUE TITLE
auto-factory 1.0-beta4 generated factory classes have now a dependency

### ISSUE THREAD

**Issue by foxylion** [google/auto#460]
With auto-factory 1.0-beta4 there is a dependency to `com.google.auto.factory.internal.Preconditions`. Previously the generated factories had zero dependencies. Now they rely on an internal class.

This will break builds using GWT (`Preconditions` is not in class path by default). And requiring the maven-dependency `auto-factory` to be available at runtime. Previously it was enough to have it available at compile time.

Also auto-factory relies on guava with a built-in `Preconditions` class that could be used instead.

**Comment by ronshapiro** [comment]
This is a dupe of another issue, I'll find later when I'm at my computer.
It's been fixed and possibly even synced out.

**Comment by tbroyer** [comment]
That was #436

**Comment by ronshapiro** [comment]
`1.0-beta5` is released and fixes this
