### ISSUE TITLE
Link to userguide in Readme not a link

### ISSUE THREAD

**Issue by vogella** [google/auto#462]
On https://github.com/google/auto/tree/master/value the link to the userguide should be a link:

For more information, consult the [detailed documentation] (userguide/index.md)

**Comment by eamonnmcmanus** [comment]
Yes, we noticed this yesterday. Apparently the github markdown engine changed in a way that caused links like this `[foo](http://bar/baz)` no longer to be recognized if there was a line break inside the `](`. We were relying on the old behaviour, which however was outside the Commonmark spec. A forthcoming update will fix the documentation.

**Comment by eamonnmcmanus** [comment]
This has now been fixed.
