### ISSUE TITLE
Report an error if `@Memoized` is applied to a method that is not part of an `@AutoValue` type.

### ISSUE THREAD

**Issue by netdpb** [google/auto#467]
#466 reports that `@Memoized` doesn't memoize methods that are not part of an `@AutoValue` type. That is intentional, but we should report an error at the annotated method in order to avoid surprising (lack of) behavior.

**Comment by tbroyer** [comment]
Shouldn't that be an error prone check?

**Comment by netdpb** [comment]
I think Error Prone is good for valid Java that is nevertheless buggy. An annotation processor should be directly responsible for reporting errors in usage of its annotations, IMO.
