### ISSUE TITLE
Combine with FreeBuilder to get latest?

### ISSUE THREAD

**Issue by kilaka** [google/auto#481]
Sounds like AutoFactory AutoValue and [FreeBuilder](https://github.com/google/FreeBuilder) are up the same valley.
What about combining the 2 projects?
Also, it seems that AutoValue does not support JavaBean convention, nor newer Java 8 features (like Optional). FreeBuilder supports them.

\* Sorry that I posted this as an issue. Tried clicking on the Wiki, but just got redirected to the main page. Anyhow, having duplicate repos for very related functionality + not using the same conventions was the motivation to open an issue.
\* I can do the moving myself (pull request). Just want to discuss this first.
Thanks.

**Comment by JakeWharton** [comment]
> it seems that AutoValue does not support JavaBean convention, nor newer Java 8 features (like Optional)

Both of these are supported.

**Comment by kilaka** [comment]
From the [main example (index)](https://github.com/google/auto/blob/master/value/userguide/index.md), there's no `animal.getName()` but rather `animal.name()`. That's why I said not using for JavaBean convention.
I now see that the _auto_ project also supports builders. So what about combining this with [FreeBuilder](https://github.com/google/FreeBuilder)? They're both Google projects.
\* Jake, it's an honor to get a reply by a celeb ;)

**Comment by JakeWharton** [comment]
Beans:
https://github.com/google/auto/blob/master/value/userguide/howto.md#beans
Optional isn't documented, but all Java 8 variants and Guava are supported.

**Comment by JakeWharton** [comment]
Also have you see the comparison:
https://github.com/google/FreeBuilder/blob/master/README.md#autovalue-vs-freebuilder
and AutoValue's design slides:
https://docs.google.com/presentation/d/14u_h-lMn7f1rXE1nDiLX0azS3IkgjGl5uxp5jGJ75RE/edit
?

**Comment by eamonnmcmanus** [comment]
That FreeBuilder is under github.com/google is something of a result of history. It isn't being maintained by anyone at Google.

There is a fundamentally different philosophy between the two projects. AutoValue adheres strongly to the philosophy that code should not generate APIs. You write the API (abstract methods in your `@AutoValue` class and builder) and AutoValue generates its implementation. On the other hand, FreeBuilder generates part of your API for you. Without getting into a discussion of the merits of either approach, they are not really reconcilable.

@kilaka, if you found the documentation confusing then please open an issue about that. Thanks!

**Comment by kilaka** [comment]
Hey guys, I'm not sure where to ask this. Sorry for the overload.
What about generating decorators? AutoDecorator? :)
I'd like to contribute.

**Comment by eamonnmcmanus** [comment]
We've talked about an AutoForward, and I think @ronshapiro has looked into it a bit, but it's never been really clear what would be useful. It's worth noting that, for interfaces, java.lang.reflect.Proxy is often a better way to achieve the same end than code generation.

**Comment by kilaka** [comment]
Regarding using `java.lang.reflect.Proxy`, it cannot be used for type safe decoration.
An example:
Consider you want to decorate `java.sql.Connection` and only the `close()` method. The important requirement here is for the `close()` method to be recognized in compile time as belongs to the `Connection` interface, meaning using the `@Overwrite` annotation.

**My point is that there's no way doing this using `java.lang.reflect.Proxy`**.
See a discussion on the subject on [this SO post](http://stackoverflow.com/questions/38054748/java-7-custom-method-decoration-without-default-delegating-all-other-many-me).

**Comment by cgruber** [comment]
Let's kick the @AutoForwarder discussion into a different issue, as it's not relevant to this one.
