### ISSUE TITLE
Generated AutoValue is put in `target/classes` instead of `target/generated-sources/annotations`

### ISSUE THREAD

**Issue by kilaka** [google/auto#482]
Hey, I've put the Animal example into a [very small project](https://www.dropbox.com/sh/8sd7icgq98gcwc1/AAAUBPfkQFkwRM53qE98yYH5a?dl=0). `Animal.java` + `pom.xml`.
Runnig `mvn clean install` caused the generated java file (`AutoValue_Animal.java`) to be put in along with the classes, in `target/classes`.
The issues with that are:
1. IntelliJ IDEA doesn't recognize the generated Java file. See [SO Q&A](http://stackoverflow.com/questions/43652094/how-to-make-intellij-idea-recognize-build-time-generated-sources).
2. It's not conventional. See [maven documentation](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#generatedSourcesDirectory). Default location should be `${project.build.directory}/generated-sources/annotations`. This also causes IDEA to recognize correctly the generated Java file.

Cheers and thanks for contributing to the community. Appreciate it. I try to contribute as well :)

**Comment by tbroyer** [comment]
Because you didn't configure the source/target level for the maven-compiler-plugin, it defaults to 5; and this is case, because JavaC 5 didn't support annotation processing, it doesn't pass the `-s` argument to tell it where to output generated sources.

You should have a warning about cross compilation in the Maven output.

And blame Maven for configuring a default source/target level.

**Comment by kilaka** [comment]
I think it's a maven issue as well but not because of the default Java 5.
As I wrote in [SO](http://stackoverflow.com/a/43657410/435605), it seems that the following fixes the issue:

    <plugin>
    	<groupId>org.apache.maven.plugins</groupId>
    	<artifactId>maven-compiler-plugin</artifactId>
    	<version>3.5</version>
    	<configuration>
    		<source>5</source>
    	</configuration>
    </plugin>

This caused the file `AutoValue_Animal.java` to be generated in `target/generated-sources/annotations`, which IntelliJ IDEA read without any additional tweaking.

**Comment by tbroyer** [comment]
You're right that `5` works, and it's probably a bug in plexus-compiler: it'll pass `-s` if the JDK is not pre-Java-1.6, which it detects by looking for `1.0`, `1.1`, …, `1.5` (so `5` is seen as "Java 1.6 or later"): https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.2/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L382-L409 (see also https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.2/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L240-L250 where it's used)

…and, the default value in maven-compiler-plugin is obviously `1.5`, not `5` as I said.

**Comment by kilaka** [comment]
minus x minus = plus ;-)
Translation: 2 bugs made it work correctly.
