### ISSUE TITLE
"exception during invocation of getAnnotationMirrors" on Mac OS

### ISSUE THREAD

**Issue by MatrixFrog** [google/auto#485]
Are there any known issues with annotation processing, specific to Mac OS? We recently started using AutoValue and it seems to work fine on Linux but fail on Mac (not sure if anyone's tried Windows yet). Have you seen anything like this before?

`error: @AutoValue processor threw an exception: java.lang.RuntimeException: exception during invocation of getAnnotationMirrors`

https://github.com/google/closure-compiler/issues/2465

**Comment by eamonnmcmanus** [comment]
I [followed up](https://github.com/google/closure-compiler/issues/2465#issuecomment-298248266) on that issue. Thanks for drawing it to my attention!

**Comment by nglorioso** [comment]
Looks like this was a JDK7 v JDK8 issue over there.
