### ISSUE TITLE
@AutoService value: accept array of class instead of single class

### ISSUE THREAD

**Issue by jbgi** [google/auto#488]
I think it would make sense to be able to implement more than one service by the same class.
(would require java 8+ though)

**Comment by tbroyer** [comment]
Instead of making it repeatable, changing `value` from `Class<?>` to `Class<?>[]` would be enough (and backwards-compatible as source level –obviously not a binary level though)

**Comment by jbgi** [comment]
@tbroyer good point. plus since `@AutoService` as `SOURCE` retention, it should not break any code!

**Comment by jbgi** [comment]
This is definitely low priority: I was feeling lazy to create a second class when I wanted that feature.

**Comment by hzsweers** [comment]
I actually want this. Say you write an SPI-based extensions API and you want to have one class that implements multiple related interfaces for code sharing, currently this isn't possible to support with AutoService

**Comment by hzsweers** [comment]
I put a demo/proposal PR up in #548
