### ISSUE TITLE
autovalue extensions for builders

### ISSUE THREAD

**Issue by eliasbagley** [google/auto#491]
Hi, is there any way to use the extensions API to modify the generated builder code?

**Comment by naturalwarren** [comment]
Not that I'm aware of. What's the use case you're thinking of?

**Comment by JakeWharton** [comment]
Dupe #349

**Comment by eamonnmcmanus** [comment]
As @JakeWharton notes, this is a duplicate of #349. We should at least stop having the generated `Builder` class be final, which would allow some use cases to work.
