### ISSUE TITLE
Producing Javadoc for methods

### ISSUE THREAD

**Issue by cammace** [google/auto#499]
When using AutoValues, is there a way to still generate the Javadoc for each getter and setter method? For example, I have [this class](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsResponse.java) which can use AutoValue but I'm restricted currently because we still need to be able to generate Javadoc for each API. Is there a workaround or will I have to override each of these methods? Please point me in the right direction if this is already documented, I wasn't able to find information directly regarding this issue.

**Comment by lowasser** [comment]
AutoValue [doesn't really *do* setters](https://github.com/google/auto/blob/master/value/userguide/howto.md#setters).  But generally speaking, you are writing your own abstract methods for the getters, and that's the public API people see.  You wrote those methods; they're in your code; you can write Javadoc for them right there.
