### ISSUE TITLE
AutoValue for abstract base class question

### ISSUE THREAD

**Issue by evindj** [google/auto#502]
Hi,
I have a base class that defines an abstract method, I would like all subclasses of these class to value type my definition looks like this:
```
abstract class BaseClass{
        List<BaseClass> children
        abstract doWork();}
```
This base class is implemented by many subclasses that I would love to be value type.
I can't define @AutoValue at the class level the AutoValue_BaseClass does not contain the definition of doWork(). When I define @AutoValue at the subclass level a value constructor for List<Trigger> is required. Do you guys have ideas on how I can handle this?
Thanks.

**Comment by eamonnmcmanus** [comment]
The question is a bit unclear. Is `List<BaseClass> children` a field in `BaseClass` and you're looking for a way to initialize it from the constructor? Could it be `List<BaseClass> children()`, in which case it would be a property of every `@AutoValue` subclass?

**Comment by evindj** [comment]
```List<BaseClass> children``` is a private field in BaseClass with its accessor (Sorry for omitting that).
```
abstract class BaseClass{
        private List<BaseClass> children;
        public List<BaseClass> getChildren();
        public abstract doWork();
        public BaseClass(List<> children);
}
```
My goal is was to have all subclasses of BaseClass be value type.
 When I define the ```@autovalue``` type at the base class level, the AutoValue library does generate the AutoValue_BaseClass that extends Base class but do not include the definition of the abstract method doWork() which causes a compilation error. So I decided to put the ```@autovalue``` on every BaseClass subclass like this
```
@autovalue
class ChildClass extends BaseClass{
   // ctor that takes a list BaseClass as parameter
   public static ChildClass create(List<BaseClass> v){
        return new AutoValue_ChildClass(v)
   }
}
```
but after compiling I got the error message " constructor for List<BaseClasse> is required. ", my first assumption was that AutoValue library is trying to create a different list for every children but I might be wrong. I guess my question is that I do not know how to handle this scenario and would like some guidance.

**Comment by Purus** [comment]
I am facing similar kind of issue.. When extending, the base class methods are not availalbe in the generated class.

**Comment by eamonnmcmanus** [comment]
The answer to the original question is [here](https://github.com/google/auto/blob/master/value/userguide/howto.md#ignore). You can't add a constructor parameter for a field that doesn't correspond to an abstract method, but you can assign to the field immediately after construction. It's not perfect but it does the job.

I don't understand the comment from @Purus. What base class methods? Could you give some example code?

**Comment by Purus** [comment]
@eamonnmcmanus I am sorry. I realize my issue is different. I have created a new issue for it. https://github.com/google/auto/issues/735
