### ISSUE TITLE
API changes review for Auto Common

### ISSUE THREAD

**Issue by lvc** [google/auto#514]
The review of API changes for the Auto Common library since 0.1 version: https://abi-laboratory.pro/java/tracker/timeline/auto-common/

The report is updated 3 times a week (Mon, Wed, Fri). Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-compliance-checker and https://github.com/lvc/japi-tracker tools.

Thank you.

![auto-common-1](https://user-images.githubusercontent.com/1517837/29519900-270dba5c-8690-11e7-9312-be1902885f70.png)
![auto-common-2](https://user-images.githubusercontent.com/1517837/29519978-6c5e7d9e-8690-11e7-98c6-332f42c67a54.png)

**Comment by ronshapiro** [comment]
Until we reach a 1.0, we have no commitment to API compatibility for auto-common
