### ISSUE TITLE
How to get details what goes wrong during annotations processing?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [google/auto#525]
Android Project, Gradle. 

During compilation AutoValue cannot generate classes. In logs is no message from Auto Value annotation processor about any errors. 

Is any option available for detecting what goes wrong?! maybe i should provide special variable/key for getting logs of what is goes wrong?

Will appreciate any help.

P.S. looks like it can be related to Nested classes. and Parcelable state

**Comment by eamonnmcmanus** [comment]
Unfortunately no, there are no logging options for the AutoValue processor. You could try removing the jar with the Parcelable extension (assuming you have it) and see whether that changes what you see. It's surprising to me that you would get neither output classes nor error messages.

**Comment by nglorioso** [comment]
Since this request for assistance is ~2 years old and might be for a specific instance, I'm closing this for now.
