### ISSUE TITLE
disable null check for entire app

### ISSUE THREAD

**Issue by mohamadk** [google/auto#528]
hi, thanks for this amazing library.
is this possible to remove null check for the entire project without set @nullable to every field?

**Comment by eamonnmcmanus** [comment]
I'm not sure how that would work. Maybe with a `-A` option that you would apply when compiling? What is your use case?

**Comment by mohamadk** [comment]
I have  a project with a lot of models  which all my models are auto value but for some reason, my partner says all of the fields can be null and we cannot specify what fields can be null and what's cannot, so I have to convert all my fields to nullable and as I said I have a lot of them. so is there a shortcut

**Comment by eamonnmcmanus** [comment]
I think your best bet would be to use some sort of tool that modifies your source code to insert `@Nullable` in front of every abstract method in an `@AutoValue` class, when the method is not already `@Nullable` and doesn't return a primitive type. I can't see how this could be addressed in AutoValue itself.

**Comment by mohamadk** [comment]
so if I want to create a lot of models which all of the fields of them is nullable I should put a @nullable annotation on it.
don't you think this is a boilerplate code? when I know all of the fields are nullable.
I supposed auto value create to avoid boilerplate codes.
I personally rather this feature be in autovalue config but thanks anyway the library is  great still without this feature
