### ISSUE TITLE
API report for Google AutoValue

### ISSUE THREAD

**Issue by lvc** [google/auto#534]
Hi,

Here is the report on API changes and backward binary compatibility for the Google AutoValue library: https://abi-laboratory.pro/java/tracker/timeline/auto-value/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars at http://central.maven.org/maven2/com/google/auto/value/auto-value/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library to be aware of past and future API changes.

The tool checks all public API methods and classes. Please let me know if it should not check some parts of the API.

Also please let me know if you are interested to see reports for other modules in the tracker.

Thank you.

![auto-value-2](https://user-images.githubusercontent.com/1517837/31328226-88fee7f0-acdc-11e7-8fcf-512d7015a710.png)
![auto-value-1](https://user-images.githubusercontent.com/1517837/31328227-8902863a-acdc-11e7-9077-a9c25b642d0b.png)

**Comment by tbroyer** [comment]
You may want to exclude `com.google.auto.value.processor` from the checks, as its only public API is actually a `javax.annotation.processing.Processor` implementation.

**Comment by eamonnmcmanus** [comment]
This is interesting, thanks. I think the only packages that it makes sense to analyze are `com.google.auto.value` and `com.google.auto.value.extension`. The single annotation `com.google.auto.value.extension.memoized.Memoized` would also make sense, but not the other things in that package.

**Comment by lvc** [comment]
Hi,

Thank you for the review.

The report is fixed.

![auto-value-4](https://user-images.githubusercontent.com/1517837/31426201-fed46dee-ae6a-11e7-8bbb-5757cf9a4989.png)

![auto-value-3](https://user-images.githubusercontent.com/1517837/31426202-fef24a9e-ae6a-11e7-9606-6abec353aba5.png)

**Comment by eamonnmcmanus** [comment]
Thanks, that's certainly interesting. It's true that we added a method to AutoValueExtension.Context in 1.3, though that's not an interface that people are expected to implement. Perhaps we should add a note to that effect. Probably, though, if we add any more methods they will be default methods, now that we require Java 8 to compile.

I'm closing this since it's not an actual issue.

**Comment by lvc** [comment]
I've marked `AutoValueExtension.Context` interface as non-implementable by users and regenerated report. It's all green for now: https://abi-laboratory.pro/java/tracker/timeline/auto-value/

Thanks a lot!
