### ISSUE TITLE
Request to consider new parameter ImmutableList<AutoValueExtension> applicableExtensions in AutoValueExtension.generateClass 

### ISSUE THREAD

**Issue by sopak** [google/auto#540]
I created an extension to enforce guided auto value object initialisation.  
https://github.com/sopak/auto-value-step-builder
I would like to be able to return false from method mustBeFinal(), and for that, I need to know constructor of a final class. 

I would like to extend class AutoValueExtension and add method and call it from AutoValueProccessor.writeExtensions
```java
public String generateClass(Context context, String className, String classToExtend, boolean isFinal, ImmutableList<AutoValueExtension> applicableExtensions) {
  generateClass(context, className, classToExtend,isFinal);
}
```
Can you give me your oppinion?

**Comment by eamonnmcmanus** [comment]
I'm not really clear on what you're asking for. If you got a list of applicable extensions, what would you use it for?

**Comment by sopak** [comment]
I need to know the name of the final AutoValue_ClassName.
Respective how many "$" I have to prepend.
I need it for a case where no builder/creator is used and I want to create an instance.

**Comment by JakeWharton** [comment]
The final one has no prefix

**Comment by sopak** [comment]
@JakeWharton ups,  thank you. How can I miss it. :)
