### ISSUE TITLE
@Nullable does not work correctly with Java 9 because auto-value depends on old version of auto-common

### ISSUE THREAD

**Issue by cheister** [google/auto#546]
Properties that are marked with `javax.annotation.Nullable` are not recognized as nullable properties in Java 9 because auto-value uses an old version of auto-common.

In Java 9 the element tree of the `javax.annotation.Nullable` annotation has `ElementKind.MODULE` which will have `Visibility.DEFAULT` in auto-common 0.8 and therefore auto-value will not take it into account.  

auto-common fixed this issue with https://github.com/google/auto/commit/2c035ce5172a6c4d21d859e2609b57358db02f6f#diff-9119c229dbf20ab7e88dbbe95b525a05 but it has not been released since that change was made.

The latest auto-value still depends on auto-common 0.8 which does not have that fix.

Can you release a new version of auto-common and have auto-value depend on the new version?

**Comment by kubagruszka** [comment]
Seems that I've run into the same problem. Is there any workaround to move forward with the depending implementation ?

**Comment by netdpb** [comment]
Yes. New releases are forthcoming.

**Comment by davido** [comment]
Probably related: https://github.com/google/auto/issues/562.

**Comment by ronshapiro** [comment]
Can you add an explicit dependency on `0.9` (to your `annotationProcessorPaths` in maven/`annotationProcessor` in gradle) to make sure this fixes your issue?

**Comment by cheister** [comment]
This was fixed when 1.5.3 was released.
