### ISSUE TITLE
AutoValue with Protobuf

### ISSUE THREAD

**Issue by krisskross** [google/auto#553]
Hi

Any ideas / efforts in the area of providing protobuf serialization for AutoValue? The square/wire protobuf implementation have an internal API that seems fit for this purpose.

Cheers,
-Kristoffer

**Comment by krisskross** [comment]
At the moment we use square/wire as an internal protocol between services. But the code generation doesn't allow extending the behavior of the generated classes (validation, transformation etc), which means a lot of static methods that operate on wire/square classes.  So i'm looking for a middle ground between having protobuf serialization and AutoValue.

Worst case, AutoValue could wrap the wire/square classes ...

**Comment by JakeWharton** [comment]
Wire let's you write your own code generator.

**Comment by krisskross** [comment]
Hmm. Yes, I guess its possible to generate a wire class from the AutoValue definition with some annotations for the tags. Or was it something else you had in mind?

**Comment by krisskross** [comment]
I'm looking at `JavaGenerator` which only public method accept a Schema which is derived from a proto file so going from AutoValue to Wire is probably not the way. Generating AutoValue from proto seems doable though. Maybe keep Builder as a delegate for state? I'm a little unfamiliar with the API to make a good judgement. Any suggestions?

**Comment by JakeWharton** [comment]
You can replace the entirety of JavaGenerator with your own code gen. Use
the Schema to load and parse the protos and then generate whatever you want.

**Comment by krisskross** [comment]
Awesome. Ill try that. Thanks!
