### ISSUE TITLE
Fail fast for lack of default

### ISSUE THREAD

**Issue by spoerri** [google/auto#554]
The standard way of setting a default is cool, i.e. on the newly-constructed builder instance before returning it from the builder() method.

We’d like to easily avoid situations in which we almost always have a value for a primitive field, but in corner cases we could not get a value (e.g. it’s coming from some other system). In only those cases, we get an unchecked exception. This is difficult to test for, so we’d like to be able to get an exception when we call build() for a default which was not specified for some primitive field, even if a value was subsequently specified by a real builder call.

One way would be to have a special call supported by the generated builder, e.g.:
```
  static Builder builder() {
    return new AutoValue_Animal.Builder()
        .setNumberOfLegs(4)
        .throwIfMissingDefaults();
  }
```

Another would be to go ahead and support defaults via annotation, e.g.:
```
  @AutoValue.Builder(requireDefaults=true)
  abstract static class Builder {
    @Default(“4”) abstract Builder numberOfLegs(int value);
    ...
```
...which would even allow detecting these bugs at compile time.

Would you accept a patch for either, or some other way of achieving the objective?

**Comment by eamonnmcmanus** [comment]
I'm not sure I completely understand the request but here are some suggestions.

One way to achieve the effect of `.throwIfMissingDefaults()` would be to call the `.build()` method in the `builder()`, and discard the result:

```java
static Builder builder() {
  Builder builder = new AutoValue_Animal.Builder()
      .setNumberOfLegs(4);
  builder.build();
  return builder;
}
```

Also, "the corresponding getter currently throws an unchecked exception", you can [declare](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-normalize-modify-a-property-value-at-build-time) the getter to return `Optional<Something>` instead of `Something` and then there's no exception.

**Comment by spoerri** [comment]
> One way to achieve the effect of .throwIfMissingDefaults() would be to call the .build() method in the builder(), and discard the result

Ah, good point

It is a little bit of overhead to make that standard for all my builders, and always new up two objects instead of one.

Do you be it’d be evil to wrap the extra build call in a java “assert” call to optimize my production builds? Oracle’s doc specifically warns “Do not use assertions for argument checking in public methods.”

**Comment by sopak** [comment]
If you want to enforce filling every required field during Compile time, then you can use an extension AutoValueStepBuilder. I add small example how to [here ](https://github.com/sopak/auto-value-step-builder/blob/master/example/src/test/java/cz/jcode/auto/value/step/builder/example/simple/DefaultsTest.java)

Extension basically implements Step Builder pattern, which enforces an order of all required fields.

usage is similar as with builder:

```
 private Address.Builder createBuilderAddressWithAllDefaults() {

        return Address.step().title(ADDRESS_TITLE)
                .street(ADDRESS_STREET)
                .city(ADDRESS_CITY)
                .postcode(ADDRESS_POSTCODE)
                .countryCode(ADDRESS_COUNTRY_CODE)
                .optional()
                .streetParts(ADDRESS_STREET_PARTS)
                .build()
                .toBuilder();
    }

```

I recommend you to create SomeBuilderFactory for all defaults. It's tricky to have another static method in AutoValue which returns Builder.

**Comment by eamonnmcmanus** [comment]
Using an `assert` statement to do the checking-`build()` seems like a great idea to me. Typically assertions are enabled when running tests, so those tests will fail before you ever get to production. Disabling the `assert` in production is then fine, and indeed the right thing to do.

**Comment by spoerri** [comment]
Thanks @eamonnmcmanus 

Thanks @sopak ... colleague and I were just spitballing about something like that, and we concluded “nah, too hard” :)

My original query was a little murky: It’s **primitive** field with which we’re having issues, and not actually required fields. That’s because it’s natural to just refrain from calling the setter for a primitive.

We have code that maps from protocol buffer version 2 messages that looks like:
```
if (message.hasFu()) {
    int fu = message.getFu();
    target.setBar(fu);
}
```
and it works fine when `target` is a pojo, and *seems* to work fine when `target` is instead an autovalue builder. Later we notice that `fu` is not actually marked as required in the schema, and some flaky client is omitting it, and we’re throwing exceptions in prod.

So testing an early `build()` has the disadvantage that it requires defaulting even required non-primitive fields.

So the question still stands! What’s the best way to avoid these bugs?

**Comment by eamonnmcmanus** [comment]
So your requirement would be some way to check that every primitive-valued property in a builder has a value? That seems a bit too specific a problem to solve.

Maybe you could write an AutoValue [extension](https://github.com/google/auto/blob/master/value/userguide/extensions.md) that introspects on the Builder methods looking for the `@Default` annotation you mentioned, and generating a compile error if there are primitive properties without it. So you might have this:

```java
@AutoValue
abstract class Animal {
  abstract String name();
  abstract int numberOfLegs();

  static Builder builder() {
    return AutoValue_Animal.builderWithPrimitiveDefaults()
        .setName("defaultname");
  }

  @AutoValue.Builder(requireDefaults=true)
  abstract static class Builder {
    abstract String name();
    @Default(“4”) abstract Builder numberOfLegs(int value);
    abstract Animal build();
  }
}

// Generated by extension:
// $AutoValue_Animal is the superclass generated by AutoValue itself,
// with the fields and getters and equals/hashCode etc.
final class AutoValue_Animal extends $AutoValue_Animal {
  Builder builderWithPrimitiveDefaults() {
    return new Builder()
        .setNumberOfLegs(4);  // derived from @Default
  }
}
```

**Comment by spoerri** [comment]
Ok thanks
