### ISSUE TITLE
AutoFactory + Dagger 2 method injection

### ISSUE THREAD

**Issue by winterDroid** [google/auto#557]
I'd like to use more or less method injection with Dagger 2 and AutoFactory. Essentially it would be great if AutoFactory would be able to call methods with provided arguments during the construction of the object. So basically that something like that:
```
@AutoFactory
class AClass @Inject constructor(@Provided private val dep: ADependency) {
    @Inject
    fun init(@Provided dep: BDependency) {}
}
```
would generate something like:
```
public final class AClassFactory {
    private final Provider<ADependency> aDependencyProvider;
    private final Provider<BDependency> bDependencyProvider;

    @Inject
    public AClassFactory(Provider<ADependency> aDependencyProvider,
                                        Provider<BDependency> bDependencyProvider) {
        this.aDependencyProvider = checkNotNull(aDependencyProvider, 1);
        this.bDependencyProvider = checkNotNull(bDependencyProvider, 2);
    }

    public AClass create() {
        final AClass aClass = new AClass(checkNotNull(aDependencyProvider.get(), 1);
        aClass.init(checkNotNull(bDependencyProvider.get(), 2));
        return aClass;
    }
}
```

**Comment by ronshapiro** [comment]
Why can't you move that parameter to the constructor? Then you don't need
anything custom

**Comment by winterDroid** [comment]
Obviously you can. It would be more about methods that should be executed right after the object creation but should not be part of the constructor.

**Comment by ronshapiro** [comment]
Maybe I wasn't clear (or I'm not understanding you), but this is what I'm suggesting:

```kotlin
@AutoFactory
class AClass @Inject constructor(@Provided private val dep: ADependency, @Provided private val dep2: BDependency) {
    @Inject
    fun init() { use(dep2); }
}
```

You can still use the dependency right after construction.

**Comment by winterDroid** [comment]
Yeah that would totally work, but then I'd need to manually call `init` in every place and keep reference to the dependency in the class.

I'd like instead just use the dependency in that method and it should be called always after creation of the object which is what dagger's method injection can be used for.

**Comment by ronshapiro** [comment]
> Yeah that would totally work, but then I'd need to manually call `init` in every place and keep reference to the dependency in the class.
Dagger will call it for you since it's marked `@Inject`. Especially since you're using Kotlin, keeping the reference seems to be no more complicated.

> I'd like instead just use the dependency in that method and it should be called always after creation of the object which is what dagger's method injection can be used for.
Yea, but that's not what AutoFactory is used for. You're between two features that probably shouldn't be mixed, so you have to choose one or the other. I don't think it makes sense for AutoFactory to reimplement method injection.

**Comment by cgruber** [comment]
Yeah - I think I see what you're trying to do.  The thing is, Autofactory isn't dagger, and doesn't fully expect objects-to-be-built to be JSR-330 objects. They're partial-JSR-330-ish objects, which autofactory manages.  I don't think there's any argument that AutoFactory couldn't do this, but I suspect it can't be a priority.

To tweak Ron's example, you might consider:

```kotlin
@AutoFactory
class AClass @Inject constructor(@Provided private val dep: ADependency, @Provided private val dep2: BDependency) {
  init {
     // do your post-construct work here. 
  }
}
```

It's a bit of a cheat, becuase while it's technically not work-in-constructor, it's definitely work that happens before an object is finished construction. 

You could even make it conditional, doing somethign like: 

```kotlin
@AutoFactory
class AClass @Inject constructor(
        @Provided private val dep: ADependency,
        @Provided private val dep2: BDependency,
        private val eagerInit: Boolean) {
  init {
    if (eagerInit) init()
  }

  fun init() {
    // init logic
  }
}
```
Then you can decide if you want init automatically called.

**Comment by cgruber** [comment]
As we move more into kotlin familiarity at Google, we should start to examine this question more fully, though, as autofactory doesn't account for things like properties, which it could (and simulate that with get/set logic in java), but that's substantial design shift, and we'd need to think about the kotlin AND java implications of it in autofactory.  For now, I think you'll need to do workarounds.

**Comment by winterDroid** [comment]
Yeah that workaround with the flag sounds ok for now. Just putting the method in the `init` / constructor is not a valid solution for me.
