### ISSUE TITLE
AutoValue does not handle names beginning with double capitals well

### ISSUE THREAD

**Issue by alpeshvas** [google/auto#565]
```
package com.alpesh.Test
 public abstract class Test implements ITest {

        public static Builder builder() {
		return new AutoValue_Test.Builder();
	}

	AutoValue.Builder
	public abstract static class Builder {
		public abstract Builder xIdentityContext(String xIdentityContext);
		public abstract TnCredentials build();
	}

}


public interface ITest {
	String getApiKey();
	boolean isDebug();
	String getUrl();
	String getXIdentityContext();
}
```

Consider the above code at first. Note the method name in ITest interface for method `getXIdentityContext`

Build failed with
 ```
Method does not correspond to a property of  com.alpesh.Test
		public abstract Builder xIdentityContext(String xIdentityContext);
```
Now, comes the interesting part, when changed that method name in ITest Interface with getXidentityContext  ( I -> i )  and did same in AutoValue.Builder( I -> i ). Build succeeded. Have any one experienced this before . Is Autovalue unable to detect property when there is two Capital letters at the beginnig ?

**Comment by tbroyer** [comment]
I believe AutoValue uses the JavaBeans™ conventions, and `getXIdentityContext` following those rules is a getter for a `XIdentityContext` property. See https://docs.oracle.com/javase/8/docs/api/java/beans/Introspector.html#decapitalize-java.lang.String- which explains this special-case.

**Comment by alpeshvas** [comment]
Thanks @tbroyer

**Comment by eamonnmcmanus** [comment]
We recognize that the JavaBeans behaviour is a bit of a misfeature, and I added code (a year ago today) that covers the mirror case, where the getter is xIdentityContext() and the setter is setXIdentityContext(x). We could imagine doing the same thing for this case.
