### ISSUE TITLE
Getter type different from the type used in the setter

### ISSUE THREAD

**Issue by wissil** [google/auto#567]
Not sure if something like that is possible right now.

```
@AutoValue
@JsonDeserialize(builder = AutoValue_House.Builder.class)
public abstract class House {
    
    public abstract String getCity();

    public abstract Person getOwner();

    public static Builder builder() {
        return new AutoValue_House.Builder();
    }
    
    
    @AutoValue.Builder
    public abstract static class Builder {
        
        @JsonProperty(value = "ownerEnc")
        @JsonDeserialize(/* String to Person deserialization */)
        public abstract Builder setOwner(String ownerBase64Enc);

        @JsonProperty(value = "city")
        public abstract Builder setCity(String city);
        
        public abstract House build();
    }
}
```

The issue is that I am getting a field `owner` as a Base64 encoded string from an external JSON, and internally I need to decode it and use it as a `Person` object. For the decoding purpose I would write a custom JsonDeserializer. 

But the issue with **AutoValue** is that it doesn't allow the type in the Builder's setter to be different than the getter (String vs Person).

Defining a custom private constructor to copy the value from the Builder also doesn't work. Otherwise I would deserialize it inside the builder, and set the deserialized value to the outer class.

Is there any way to accomplish what I need with AutoValue?

**Comment by sopak** [comment]
I  am just guessing can't you just add your own implementation to the builder?

```

public abstract Builder setOwnerEnc(String ownerBase64Enc){|
  // deserialize
  Person deserialized=new Person(...)
  this.setOwner(deserialized)
  return this;
}
```

**Comment by tbroyer** [comment]
Don't you actually need to use `setOwner(Person)` too for Jackson? Otherwise, what would it do with the `Person` object it just deserialized? (just thinking out loud)

**Comment by wissil** [comment]
@sopak Yes you can, but how would you retrieve the Builder's field `Person owner` back to the `House` class? You would need a private constructor that takes in a builder, which is impossible with `AutoValue` because it already generated it's own.

**Comment by wissil** [comment]
@tbroyer What do you mean? I am getting the encoded base64 string from the external JSON. And in order to have my business logic inside the application, I have to deserialize it from string to the actual `Person owner`. Setters are invoked by the `ObjectMapper` that maps the external JSON to the internal objects, so setter should ideally do the parsing for me. Getter would ideally retrieve the object that is already parsed (to `Person`, by the setter).

**Comment by sopak** [comment]
@wissil actually it is possible to address setOwner. Because that method belongs  to the Builder
and an immutable object is created by ....build() from the Builder.

**Comment by wissil** [comment]
@sopak Well yeah, but you can't reference `this` from a static context, can you? The builder is static.

**Comment by wissil** [comment]
@sopak Well yeah, but you can' t reference `this` from a static Builder class, can you...

**Comment by lowasser** [comment]
`this` here is referring to the `Builder`, not the `House`, which is perfectly legal.

**Comment by wissil** [comment]
@lowasser Yeah, but how do I get this attribute back to the `House`? Because I need it retrieved from the `House`'s getter

**Comment by sopak** [comment]
@wissil 

```
House myInstance= new House.Builder()
    .setOwnerEnc("somestring")
    .setCity("city")
    .build()

Person personInstance=myInstance.getOwner()
```

**Comment by wissil** [comment]
@sopak Yeah, that works. The downside is having 2 API methods, one of which `setOwner(Person p)` should ideally not be there, but this is close enough. Thanks
