### ISSUE TITLE
Normalize properties not working with Optional and Builder

### ISSUE THREAD

**Issue by lfgcampos** [google/auto#600]
I am trying to reproduce the code from [`normalize` section](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#normalize) and the example with `Optional` inside `Builder` is not working.

It says: `Method matches a property of my.package.Animal but has return type java.util.Optional<java.lang.String> instead of java.lang.String`.
The first example work without problems (where there is no `Optional` in place).

I am working on/with:
- Windows 10 Pro 64-bit
- Eclipse Version: Oxygen.2 Release (4.7.2) Build id: 20171218-0600
- Apache Maven 3.5.0
- Java version "1.8.0_152"
- AutoValue version 1.5.3

**Comment by eamonnmcmanus** [comment]
Could you paste the code that doesn't work here?

**Comment by lfgcampos** [comment]
Never mind, I think it was some corrupted jar when I changed versions.
It is working now, thanks.
