### ISSUE TITLE
Still trying to get jackson to work with auto value

### ISSUE THREAD

**Issue by hgschmie** [google/auto#608]
This repo: https://github.com/artem-zinnatullin/AutoJackson has been quoted often as an example on how to use jackson with autovalue. The sad truth however is that it only works because it changes the visibility of the class to be able to accomplish deserialization. If you lock down the object mapper to not being able to change the visibility, this is what happens:
(adding`objectMapper.disable(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS);` to the test classes)

```
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.artemzin.autojackson.AutoValue_Tweet$Builder] value failed: Class com.fasterxml.jackson.databind.introspect.AnnotatedConstructor can not access a member of class com.artemzin.autojackson.AutoValue_Tweet$Builder with modifiers ""

	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:399)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:216)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2714)
	at com.artemzin.autojacson.TweetTest.shouldDeserializeFromJson(TweetTest.java:48)
```

which is because the Builder definition in the class contains public abstract methods, however the constructor is not. And by not allowing Jackson to modify the visibility rule of the class and the constructor, it can not actually create the builder class. 

What ultimately worked for me is this:

```java
@JsonDeserialize(builder = Tweet.Builder.class)
public abstract class Tweet {

    @NotNull
    public static Builder builder() {
        return Builder.builder();
    }
[...]
    @AutoValue.Builder
    public static abstract class Builder {

        @JsonCreator
        public static Builder builder() {
            return new AutoValue_Tweet.Builder();
        }
}
```

What would be nice if there were an option to actually new up the builder (so make the class and constructor public). The duplication of the static builder() classes feels cumbersome.

**Comment by eamonnmcmanus** [comment]
This feels like too special a case to warrant complicating AutoValue with an option. You've already showed two ways it can work with the existing system. Perhaps other reasons will show up why the builder implementation and its constructor might sometimes need to be public, but in the meantime I don't think we have a strong enough reason to change.

Meanwhile, thanks
