### ISSUE TITLE
Annotations from the parameter of equals(Object) to its implementation are not being copied.

### ISSUE THREAD

**Issue by usmanakram232** [google/auto#612]
As, stated in release notes, I expected the parameter annotation for equal method to be copied to implementation. As, perilously discussed in [579](https://github.com/google/auto/issues/579),

I tried following approaches, one discussed in previous issue and other by defining the annotation in class.   

## Trying `org.checkerframework.checker.nullness.qual.Nullable`
``` java
@AutoValue
public abstract class Play {
  abstract public String game();
  abstract public long gameId();

  public static Play createPlayWith(String game, long gameId){
    return new AutoValue_Play(game, gameId);
  }
  
  @Override abstract public boolean equals(@Nullable Object o);
}
```

## Trying with defined `@interface Nullable {}`

``` java
@AutoValue
@AutoValue.CopyAnnotations
public abstract class Foo {
  abstract public String bar();

  public static Foo createFooWith(String bar){
    return new AutoValue_Foo(bar);
  }
  @Target(ElementType.TYPE_USE)
  @Retention(RetentionPolicy.RUNTIME)
  public @interface Nullable {}

  @Override abstract public boolean equals(@Nullable Object x);
}
```

Both of these abstract classes, with parameter annotation had no affect on implementation of equal(Object o):
``` java
@Override
  public boolean equals(Object o) {
 ...
}
```

[Sample maven project](https://github.com/usmanakram232/lets-play)

**Comment by eamonnmcmanus** [comment]
I believe you are seeing a bug in javac that exists in at least some versions of JDK 8. I was able to reproduce the bug with JDK 1.8.0_112 but not with 9.0.4. Have you tried with 9 or later?

I'm looking into a workaround for JDK 8 but I'm not promising anything.

**Comment by usmanakram232** [comment]
I just tried with jdk 9, and parameter annotations do get copied, but Checker famework's can't be used with jdk 9 yet. Running nullness checker was the reason, why we needed to provide the parameter annotation. :)

So, for now our solution is to disable nullness checker on Auto-value classes and trust them.

**Comment by eamonnmcmanus** [comment]
The workaround I mentioned does fix the problem on Java 8 so I expect it will be in a forthcoming release.
