### ISSUE TITLE
Import AutoValue via Gradle: why api and not implementation?

### ISSUE THREAD

**Issue by mr746866** [google/auto#620]
In the user guide [here](https://github.com/google/auto/blob/master/value/userguide/index.md), the instruction to import AutoValue states following.

```
dependencies {
  // Use 'api' rather than 'compile' for Android or java-library projects.
  compile             "com.google.auto.value:auto-value-annotations:1.6"
  annotationProcessor "com.google.auto.value:auto-value:1.6"
}
```
Is there any specific reason to use `api` instead of `implementation`? *(In general, use of `implementation` is preferred over `api`)*

**Comment by tbroyer** [comment]
See discussion in #606. If `compileOnly` works for you, then use it, but if you're building a library shared with others (publicly) you'd better use `api`.

**Comment by mr746866** [comment]
@tbroyer Can you please explain the consequence of using `implementation`? I am using it in my Android project and don't see any problem with it.

**Comment by tbroyer** [comment]
Any annotation with retention class or runtime can cause issues in downstream modules (at compile time, during static analysis, etc.) under some conditions.

Using `api` on the other hand is mostly harmless. Worst thing is triggering rebuilds (when updating auto-value).

So without going into details in the doc, best status quo is to suggest `api`.

**Comment by eamonnmcmanus** [comment]
With Gradle ≥6.7, it's actually best to use `compileOnlyApi`. We've updated the documentation to reflect that.
