### ISSUE TITLE
How to deal with Proguard issues on Android?

### ISSUE THREAD

**Issue by zsperske** [google/auto#624]
A library we're using recently started using auto-factory and it's causing some 400 or so "library classes depending on program classes" errors with proguard. To be honest, I'm pretty much a noob with Proguard but I was hoping someone could help me understand why this is happening and what I can do to fix it.

I checked some of the issues here and saw a closed one where you guys discussed the impacts of making people define the annotationProcessor separately and how that may cause Android issues. Did you update some documentation somewhere to reflect that/suggest how to resolve the issues?

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.
