### ISSUE TITLE
AutoService can not use for android project when gradle is under3.0.0

### ISSUE THREAD

**Issue by jipengzheng** [google/auto#626]
Recently I am using AutoService in my android project ,This project has one application and many libraries, and all of them are using one interface.
 
When I was using AutoService  in gradle 2.2.2,the library is OK,but the application META-INF/services file couldn’t merge into apk. While in gradle 3.0.0., everything goes well.

I suppose this is Android gradle bug，but I am restricted  to use the updated gradle version. Would you please provide me any other solution? Thanks in advance.

**Comment by ronshapiro** [comment]
Without more information there isn't much we can deduce. I recommend trying to post on StackOverflow and if that doesn't work, trying to file a bug on the Gradle plugin
