### ISSUE TITLE
java.lang.NoClassDefFoundError with Android Studio 3.1.1

### ISSUE THREAD

**Issue by nksaroj** [google/auto#628]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue

**Comment by eamonnmcmanus** [comment]
Can you say more? What does `build.gradle` look like?

**Comment by nksaroj** [comment]
autoValue        : "com.google.auto.value:auto-value:1.6",
    autoValueAnnotations        : "com.google.auto.value:auto-value-annotations:1.6",

**Comment by SelaliAdobor** [comment]
The problem was with a dependency on `auto-value-gson` from what I can tell. Removed the dependency and I got my project to build again.

The pasted example also has the api dependency and annotation processor dependencies switched right?

**Comment by nksaroj** [comment]
https://gist.github.com/nksaroj/03544dc3e4b69cc4ab3f7d8413187f6b 

The above git contains the entire gradle configurations
I am still getting error. Appreciated your help
