### ISSUE TITLE
AutoFactory with Kotlin default arguments

### ISSUE THREAD

**Issue by ebrowne72** [google/auto#637]
It would be nice if when using AutoFactory on a Kotlin class whose constructor has default arguments, the generated factory's `create()` method used the default arguments.

**Comment by ronshapiro** [comment]
AFAIK none of that information is propagated to annotation processors. Even if it was, I'm not sure how we'd generate the correct Java code for that.

**Comment by mgsholte** [comment]
Just in case anyone stumbles across this issue in the future, there is a solution that already exists built into kotlin. If a constructor with default arguments is annotated with `@JvmOverloads`, the compiler will generate multiple constructors based on the specified defaults. In turn, AutoFactory will generate a `create` method for each generated overload.

So this class
```
@AutoFactory
class C @JvmOverloads constructor(
    @Provided val a: String,
    val b: Int = 2,
    val c: String = "c"
)
```
will cause a factory with 3 create methods to be generated:
```
val c1 = factory.create()
assert(c1.b == 2)
assert(c1.c == "c")
val c2 = factory.create(3)
assert(c2.b == 3)
assert(c2.c == "c")
val c3 = factory.create(4, "d")
assert(c3.b == 4)
assert(c3.c == "d")
```

The way Kotlin generates the overloaded Java methods is somewhat restrictive when it comes to multiple parameters with default values. In the above example there is no way to automatically generate an overload that allows specifying `c` while using the default value for `b`. The generated overloads are sensitive to the order of the parameters in the constructor as specified in the [official docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-overloads/).
