### ISSUE TITLE
Release 1.0 of auto-service, auto-factory, auto-common

### ISSUE THREAD

**Issue by swankjesse** [google/auto#638]
I’m using auto-common in an annotation processor. This is bad because all annotation processors share a single classpath but auto-common doesn’t promise a stable API. If another annotation processor depends on a past or future version of auto-common, javac will crash.

Could y’all release 1.0? auto-common celebrates its [4th birthday](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.auto%22%20AND%20a%3A%22auto-common%22) next week.

It doesn’t cause me classpath grief, but I suspect the world would all be happy if there were also releases for auto-service (1.0-rc1 was in January 2014), and auto-factory (1.0-beta2 was April 2015).

**Comment by sgarfinkel** [comment]
Agreed. Been waiting sometime, though. See: #581

**Comment by mattdarwin** [comment]
See also https://github.com/google/auto/issues/703
They've now released 1.0-rc5

**Comment by cpovirk** [comment]
@eamonnmcmanus just did most of these, with AutoFactory 1.0 to be released shortly.
