### ISSUE TITLE
Missing 1.6.1 release notes

### ISSUE THREAD

**Issue by tkruse** [google/auto#642]
including explanation of new auto-values-annotations dependency

**Comment by gabrielittner** [comment]
See
https://github.com/google/auto/releases/tag/auto-value-1.6
https://github.com/google/auto/releases/tag/auto-value-1.6.1

**Comment by tkruse** [comment]
Hm, google search gave me this file: https://github.com/google/auto/blob/master/value/CHANGES.md.
Feel free to close any way you like.

**Comment by eamonnmcmanus** [comment]
I think we should update that file so that it says to look at the release notes in github for more recent releases.

**Comment by Rishu-singhm** [comment]
help@meesho.com

**Comment by Rishu-singhm** [comment]
I can I contact from meesho
