### ISSUE TITLE
AutoValue generation broken when used with javax.validation annotations

### ISSUE THREAD

**Issue by jawpio** [google/auto#652]
Autovalue code with javax.validation is failed to be generated within eclipse.
 - not working example
```java
@AutoValue
public abstract class ColumnRestrictionDto {

	@AutoValue.CopyAnnotations(exclude = Valid.class)
	@Valid
	@NotNull
	public abstract ColumnRestrictionsDto getColumn();

	public static Builder builder() {
		return new AutoValue_ColumnRestrictionDto.Builder();
	}

	@AutoValue.Builder
	@JsonPOJOBuilder(withPrefix = "set")
	public abstract static class Builder {

		public abstract Builder setColumn(ColumnRestrictionsDto value);

		public abstract ColumnRestrictionDto build();
	}
}
```
 - working code
```java
@AutoValue
public abstract class ColumnRestrictionDto {

	public abstract ColumnRestrictionsDto getColumn();

	public static Builder builder() {
		return new AutoValue_ColumnRestrictionDto.Builder();
	}

	@AutoValue.Builder
	@JsonPOJOBuilder(withPrefix = "set")
	public abstract static class Builder {

		public abstract Builder setColumn(ColumnRestrictionsDto value);

		public abstract ColumnRestrictionDto build();
	}
}
```
you can test it with following code - https://github.com/jawpio/eclipse-autovalue-fail

Could be connected with following issue #505 .

**Comment by eamonnmcmanus** [comment]
Can you confirm that it fails with the latest AutoValue (1.6.2) before we investigate? The build.gradle there says 1.5.1.

**Comment by jawpio** [comment]
@eamonnmcmanus I can confirm. It fails with 1.6.2 and 1.6.1...

**Comment by eamonnmcmanus** [comment]
I sent a PR to update to the latest version. It works when invoking Gradle directly. What does it do in Eclipse?

**Comment by jawpio** [comment]
I can confirm invoking Gradle directly works (also in old versions). 
In Eclipse AutoValue classes are not generated and if you open "Error Log" view you'll see following exception.
[eclipse.autovalue.error.txt](https://github.com/google/auto/files/2206893/eclipse.autovalue.error.txt)

**Comment by eamonnmcmanus** [comment]
Thanks for attaching the Error Log. The exceptions there show that this is a bug in the Eclipse compiler. I would suggest logging a bug there.

**Comment by jawpio** [comment]
FYI, eclipse issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=535066.

**Comment by eamonnmcmanus** [comment]
Thanks for logging that! Hopefully it will be addressed punctually by the Eclipse team. We've added workarounds to AutoValue for Eclipse bugs before, but I don't see an obvious way we could do it here.
