### ISSUE TITLE
When is the next release version of auto factory

### ISSUE THREAD

**Issue by sunyal** [google/auto#658]
Currently auto factory has been previously released as beta.  The last release was also back in May 2017.  The code in the repo has changed and works with JDK9 without having to include the JSR 250 api jar.  Is this going to be released to a Maven repo?

**Comment by kenzierocks** [comment]
Really looking forward to this, having the package name prepended to the Factory is really inconvenient.

Any ETA on a release?

**Comment by ronshapiro** [comment]
Sorry for the delay - just released 1.0-beta5.

**Comment by kenzierocks** [comment]
1.0-beta5 already exists (it's the May release) -- and I don't see a -beta6. Is there something I missed?

**Comment by ronshapiro** [comment]
Whoops, you're right. I think I tried to release 1.0-beta5 and I guess that must have failed because I d

**Comment by ronshapiro** [comment]
Ok. 1.0-beta6 is now released. Sorry for the delay!
