### ISSUE TITLE
"Could not write generated class" warning blocking build

### ISSUE THREAD

**Issue by dietervdw-spotify** [google/auto#659]
Hi,

We started using the JVM option `-Werror` to treat all warnings as errors.

However we are blocked because we can't get rid of the following warning:
`[WARNING] /some/class/using/autovalue/SomeClass.java:[12,17] Could not write generated class com.spotify.blabla.AutoValue_SomeClass: javax.annotation.processing.FilerException: Attempt to recreate a file for type com.spotify.blabla.AutoValue_SomeClass`

I'm assuming AutoValue is trying to write this file while it already exists?
Not an issue at all, but the warning is breaking our build.

We are using maven3 .
At first I thought this could be solved by doing a clean before building, but now even that doesn't seem to work anymore.

Any suggestions on why this is happening and how we can disable this warning?

**Comment by ronshapiro** [comment]
Is it possible you're using AutoValue twice somehow? Or including `SomeClass` in two separate compilations?

**Comment by dietervdw-spotify** [comment]
Update: this seems to only happen if you mention the compile target explicitely, because Maven then runs the compilation phase twice for some reason. So I guess Maven error and rightful warning...

**Comment by dietervdw-spotify** [comment]
Re-opening because this basically forces Maven users to invoke the `clean` target ALWAYS when enabling compiler option `-Werror` .
I don't see the value of logging this warning? Can't you just overwrite always?

Not sure if this is AutoValue or generic Java module code though?
Could you let me know if this error is relevant for this project?

**Comment by ronshapiro** [comment]
It's not an AutoValue warning, that's printed by javac.

**Comment by dietervdw-spotify** [comment]
Does `javac` independently intercept that AutoValue wants to write to a class file that already exists and flag this warning? Or does the AutoValue processor flag this to javac, and then javac converts this to a warning?

**Comment by ronshapiro** [comment]
The first case.

**Comment by dietervdw-spotify** [comment]
Ok, nothing to see here then!

**Comment by tbroyer** [comment]
@dietervdw-spotify Make sure you're using a recent version of the maven-compiler-plugin (at least 3.5.1, which is actually already 2 years old), as there have been several issues with annotation processing (specifically https://issues.apache.org/jira/browse/MCOMPILER-235).

See also http://blog.ltgt.net/maven-is-broken-by-design-2/
> As an anecdote, the not-yet-released change I was playing with is related to incremental build, fixing a years-old bug that affects anyone using annotation processors that generates Java sources (most of them). It happens that maintainer of the Maven Compiler Plugin who added the above-mentioned feature never stumbled on it because he always does clean builds with Maven (leaving his IDE handle incremental compilation). In other words, incremental builds in Maven are so broken that even core contributors don’t use them.
