### ISSUE TITLE
Builders should not allow mutation after `build()` called.

### ISSUE THREAD

**Issue by johnbcoughlin** [google/auto#662]
This would probably break a lot of code if it were implemented directly. What about a Builder method `buildOnce()` which would exclude `build()`, and generate a boolean flag which would not allow any mutation once called?

**Comment by eamonnmcmanus** [comment]
Can you say a bit about the motivation for this?

It is currently possible to achieve this effect in a slightly sneaky way:

```java
@AutoValue
public abstract class Foo {
  public abstract String bar();
  ...

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setBar(String x);
    abstract Foo autoBuild();  // the real build method, not public

    private boolean built;
    public Foo build() {  // the build method that users see
      if (built) throw new IllegalStateException();
      built = true;
      return autoBuild();
    }
  }
}
```

**Comment by johnbcoughlin** [comment]
I was trying to figure out a fix like that, thank you!

Someone might reasonably expect they can write code like this:

```
Foo.Builder builder = Foo.builder();

for (int i = 0; i < 10; i++) {
  fooList.add(builder.index(i).build());
}
```

Which will do what they want, but not for the reason they might expect (that the builder is copy-on-write).

**Comment by eamonnmcmanus** [comment]
OK, I think a better example might be this:

```java
@AutoValue
public abstract class Foo {
  public abstract ImmutableList<String> names();
  public static Builder builder() {...}

  @AutoValue.Builder
  public abstract static class Builder {
    abstract ImmutableList.Builder<String> namesBuilder();
    public Builder addName(String name) {
      namesBuilder().add(name);
      return this;
    }
    public abstract Foo build();
  }
}
```

Then if a user does this:
```java
Foo.Builder builder = Foo.builder();
builder.addName("one");
Foo foo1 = builder.build();
builder.addName("two");
Foo foo2 = builder.build();
```
might they be surprised that foo2.names() is \["one", "two"]? Might they have preferred the second `.build()`, or even the second `.addName`, to have thrown an exception?

I'm not finding the case for a change very compelling. It seems like a requirement that would be unusual, and there is the workaround that I mentioned. So I'm going to close this for now. If there's demand we may reconsider.
