### ISSUE TITLE
AutoValue generated code failing new Error Prone UnnecessaryParentheses check

### ISSUE THREAD

**Issue by msridhar** [google/auto#670]
Error Prone 2.3.2 was just released and includes a new [UnnecessaryParentheses check](http://errorprone.info/bugpattern/UnnecessaryParentheses).  We compile with `-Werror` and noticed that AutoValue-generated code fails this check.  Here's an example getting flagged (I added the `// warning here` comments):

```java
  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof DataFlow.AnalysisParams) {
      DataFlow.AnalysisParams that = (DataFlow.AnalysisParams) o;
      return (this.transferFunction.equals(that.transferFunction())) // warning here
          && (this.cfg.equals(that.cfg())); // warning here
    }
    return false;
  }
```

For now we've worked around this by turning off Error Prone for generated code, and we may actually stick with that in the long term.  So this is more of an FYI than a significant problem.

**Comment by eamonnmcmanus** [comment]
Thanks for the report! I agree that it is probably not worth running Error Prone on generated code. This particular issue is easy enough to fix though so we'll probably do that.
