### ISSUE TITLE
AutoValue does not find Generated annotation on Java 11 with -source 1.8

### ISSUE THREAD

**Issue by PhilippWendler** [google/auto#686]
We use AutoValue in a Java 8 project and want to test compilation on Java 11. Unfortunately, in this scenario AutoValue does not find a `Generated` annotation on the class path, and thus skips adding it. However, we need this annotation to be present because otherwise error-prone warns about the generated source code (unnecessary parentheses etc.).

For reproduction take the following source:
```java
import com.google.auto.value.AutoValue;

@AutoValue
public abstract class Test {

  public static Test create() {
    return new AutoValue_Test();
  }
}
```

It can be compiled using
```
javac -processorpath auto-value.jar -cp auto-value-annotations.jar -source 1.8 *.java
```
On Java 8, 9, and 10, this produces
```java
...
import javax.annotation.Generated;
@Generated("com.google.auto.value.processor.AutoValueProcessor")
...
```

On Java 11 this produces
```java
...
// Generated by com.google.auto.value.processor.AutoValueProcessor
...
```
Bumping `-source` to `1.9` produces the expected
```java
...
import javax.annotation.processing.Generated;
@Generated("com.google.auto.value.processor.AutoValueProcessor")
...
```

I am using the `openjdk:11-jdk-slim` Docker image, which has
```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Debian-2, mixed mode, sharing)
$ javac -version
javac 11.0.1
```

I am actually not sure if this is a problem in AutoValue itself or if it is a general problem with Java 11. Particularly I do not understand why it fails only with Java 11, given that it works on Java 10.

But nevertheless we would be interested in knowing how to make the combination Java 8 compatible source + AutoValue + Java 11 + Error-Prone work, or any other suggestions on how to proceed.

**Comment by tbroyer** [comment]
Java 11 no longer includes `javax.annotation.Generated`, so it's no wonder that javac doesn't find it; unless you include some dependency that provides it.

You could also possibly try with `--release 8` instead of `-source 1.8`, though I'm not sure it would change the outcome (without `javax.annotation.Generated` in the classmate)

**Comment by PhilippWendler** [comment]
Thank you very much for your response. I was wondering why AutoValue wouldn't find the new `javax.annotation.processing.Generated` either, which should be present on Java 11.

`--release 8` actually works, and produces `javax.annotation.Generated`, so we will use that.

Thanks for this hint and sorry for asking here although it turns out not be to an AutoValue problem.
