### ISSUE TITLE
AutoService Annotation not compatible with Guice 4.0

### ISSUE THREAD

**Issue by ThorbenKuck** [google/auto#693]
For testability: I developed the [NetCom2-Auto](https://github.com/ThorbenKuck/NetCom2/tree/master/auto) module, which utilizes the Auto-Service and annotation processors to minimize boilerplate code. However, i found a potential issue after testing it.

With the pom.xml looking like this, there are no problems:

```
<dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.15.0</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.thorbenkuck</groupId>
            <artifactId>NetCom2-Auto</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
```

But as soon as you add the dependency to Guice 4.0

```
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.0</version>
        </dependency>
```

The annotation processing fails with the following Exception:

Error:java: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;

This Error is located at the AutoServiceProcessor, line 196.

---

## MVCE

Using maven, create a little test application. This is the only required code:

```java
public class Test {

    public static void main(String[] args) {
        NetCom2.launchServer()
                .use(ObjectRepository.hashingRecursive())
                .at(8888)
                .onCurrentThread();
    }

    @Register
    public void handle(Object o) {

    }
}
```

Maven dependencies

```
<dependencies>
    ....
    <dependency>
        <groupId>com.github.thorbenkuck</groupId>
        <artifactId>NetCom2-Auto</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>com.google.inject</groupId>
        <artifactId>guice</artifactId>
        <version>4.0</version>
    </dependency>
</dependencies>
```

Result: At compile time: Error:java: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;

**Comment by Feuermoond** [comment]
Approved. I had the same issue.

**Comment by tbroyer** [comment]
I'd say this is a typical version conflict resolution issue: Guice 4.0 (which is quite old already) depends on Guava 16, whereas auto-service depends on 23.5, but auto-service is a transitive dependency of NetCom2-Auto, so Maven picks Guava 16:
> * _Dependency mediation_ - this determines what version of an artifact will be chosen when multiple versions are encountered as dependencies. Maven picks the "nearest definition". That is, it uses the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.
>   * "nearest definition" means that the version used will be the closest one to your project in the tree of dependencies. For example, if dependencies for A, B, and C are defined as A -> B -> C -> D 2.0 and A -> E -> D 1.0, then D 1.0 will be used when building A because the path from A to D through E is shorter. You could explicitly add a dependency to D 2.0 in A to force the use of D 2.0.

— Source: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

`mvn dependency:tree` should give you some hints whenever similar things happen.

---
BTW, you should separate annotations and the annotation processor into 2 separate artifacts, and use maven-compiler-plugin's `annotationProcessorPaths` to load the annotation processors: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths

In this specific case, this would have prevented the issue (probably, depends what code your processor generates, whether it depends on Guava, and which version it expects): the compile classpath would have only included Guice (and Guava 16) and your annotations (and auto-service as a transitive dependency, for its annotation, as you generate code using `@AutoService` AFAICT), whereas the processor path would have included your processor and auto-service (for its processor), and Guava 23.5.

**Comment by ronshapiro** [comment]
I imagine the only thing for us to do is to release a new version of auto-service that has a modern version of Guava?

**Comment by tbroyer** [comment]
As long as it still works with the latest Guava, that's not necessary to release a new version. And notice that the "culprit" dependency here was Guice 4.0, not auto-service. Guice 4.2.2 wouldn't have caused a problem (also, I believe using Gradle rather than Maven, as I don't think Gradle uses that _nearest rule_ that Maven has)

**Comment by ThorbenKuck** [comment]
The generated code itself does not depend on guava. The only dependency to guava is through the Auto-Service, which is used to fill up the service files. The annotation processor generates code, that the user normally would have to write and the Auto-Module then collects the generated code. No guava dependency at runtime.

As you can tell, i am quit new to annotation processing and maven (mostly maven, before i only used gradle, there it works fine), so i believe this issue is my fault. Thank you for the heads up! I will try to update the project, but this already introduced a cyclic dependency.
