### ISSUE TITLE
issue with applying plugin 'kotlin-kapt' 

### ISSUE THREAD

**Issue by sfariv** [google/auto#702]
AutoValue doesnt generate any code when I apply 'kotlin-kapt' plugin.

**Comment by JakeWharton** [comment]
Did you move the compiler dependency to the `kapt` configuration?

**Comment by sfariv** [comment]
not sure how to do that? everything is in my build.gradle file right now.

**Comment by JakeWharton** [comment]
Have you read https://kotlinlang.org/docs/reference/kapt.html?

**Comment by sfariv** [comment]
thanks that worked.

Solution:

If you are using:

```
apply plugin: 'kotlin-kapt'
```

Replace:
```
dependencies {
    api "com.google.auto.value:auto-value-annotations:1.6.2"
    annotationProcessor "com.google.auto.value:auto-value:1.6.2"
}
```

With:
```
dependencies {
    api kapt("com.google.auto.value:auto-value-annotations:1.6.2")
    annotationProcessor kapt("com.google.auto.value:auto-value:1.6.2")
}
```

**Comment by tbroyer** [comment]
That should be:
```gradle
dependencies {
    api "com.google.auto.value:auto-value-annotations:1.6.2"
    kapt "com.google.auto.value:auto-value:1.6.2"
}
```

**Comment by ber4444** [comment]
It works with assembleDebug but not with testDebug. Anyone knows how to apply this to tests:
```
kapt {
  correctErrorTypes = true
}
```

**Comment by cinpeCan** [comment]
I have the same problem.

when I applying plugin 'kotlin-kapt', I also want to AutoValue working in my Java Bean.
but now, AutoValue doesnt generate any Java code when I apply 'kotlin-kapt' plugin.
