### ISSUE TITLE
Release AutoService with updated guava version

### ISSUE THREAD

**Issue by mattdarwin** [google/auto#703]
The latest released version of AutoService available on [maven central](https://mvnrepository.com/artifact/com.google.auto.service/auto-service) is 1.0-rc4.  This uses guava 18.0.

Since that date there have been security vulnerabilities found in guava, so AutoService should be upgraded to take these.  It seems like this has been done in 
https://github.com/google/auto/commit/cdd39ee565c8d73fcac08474956dae79caa3df81, but there's not been a subsequent release published to maven central.

**Comment by netdpb** [comment]
Yeesh, yes.

**Comment by mattdarwin** [comment]
ok great.  Any idea when this might be ready in maven central?

**Comment by mattdarwin** [comment]
How can I help get this released soon?

**Comment by Nstd** [comment]
Hope it will be soon!

**Comment by ronshapiro** [comment]
Just released a 1.0-rc5. Sorry for the delay!

**Comment by Nstd** [comment]
@ronshapiro thank you for it. But I still can't find that in maven central.

**Comment by mattdarwin** [comment]
@Nstd there is a separate ticket raised for the problem you mention: https://github.com/google/auto/issues/638

@ronshapiro thanks for the release.  Is there a reason it's called 1.0-rc5 and not 1.0?

**Comment by ronshapiro** [comment]
See #714 for why you can't find the release in Maven yet

**Comment by ronshapiro** [comment]
Should be fixed now

**Comment by Nstd** [comment]
@mattdarwin @ronshapiro thanks for the tips 😃

@ronshapiro I still have a little problem.
When I execute gradle with a little change such as add a custom annotation to a class in my custom annotation processor project, console output following warning message:
``` shell
$ ./gradlew assembleDebug

> Task :app:compileDebugJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: auto-service-1.0-rc5.jar (com.google.auto.service:auto-service:1.0-rc5).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
...
BUILD SUCCESSFUL in 3s
54 actionable tasks: 4 executed, 50 up-to-date
```
With a full clean rebuild, it cost 8 seconds.
``` shell
BUILD SUCCESSFUL in 8s
54 actionable tasks: 51 executed, 3 up-to-date
```
I'm a little confused. Is the incremental annotation processing really working?

Enviroment: Gradle 4.10.1

**Comment by tbroyer** [comment]
@ronshapiro Looks like you didn't move the META-INF to the processor when splitting out the annotations.
