### ISSUE TITLE
Allow default values to be set on AutoValue builders in property default impls

### ISSUE THREAD

**Issue by kevinmost** [google/auto#704]
I hope I'm not missing an obvious limitation that would prevent this from happening, but it feels like AutoValue builders would be so much more readable with the ability to define a method body on each property's builder method, and that method body is used as the default value for any builder instances.

For example, right now, it's very noisy to figure out what properties on an AutoValue object are required vs optional; you have to look at the list of properties in the @AutoValue or @AutoValue.Builder-annotated object, and then look at the list of methods called in the .builder() factory method to determine which ones have a default value provided when the consumer receives the builder.

```java
@AutoValue public abstract class Foo {
  public static Builder builder() {
    // the default values are listed up here,
    // but it's unclear what values are required,
    // and can sometimes be unclear what type
    // each property is.
    return new AutoValue_Foo.Builder().bar(3);
  }

  public abstract int bar();
  public abstract String baz();
  
  @AutoValue.Builder
  public interface Builder {
    // down here, we see that this value object
    // has bar() and baz() properties, but have
    // to look up at the .builder() factory method
    // to learn that bar() has a default value.
    int bar();
    String baz();
    Foo build();
  }
}
```

I would propose something like:

```java
@AutoValue public abstract class Foo {
  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  public abstract int bar();
  public abstract String baz();

  @AutoValue.Builder
  public interface Builder {
    // very clear that bar() has a
    // default value, and baz() doesn't
    default int bar() { return 3; }
    String baz();
    Foo build();
  }
}
```

Obviously, if your `@AutoValue.Builder` type is an `abstract class` because you require more complex logic in your builder, you can use a non-`default` keyword implementation that will be overridden in the generated class to define these defaults.

In the generated code, the builder's constructor could set the values by delegating through to the super implementations; either doing `this.bar = Foo.Builder.super.bar();` if the Builder type is an `interface`, or `this.bar = super.bar();` if the Builder type is a `class`.

Any thoughts? I searched around for prior issues similar to this one, but couldn't find one on the viability of this feature in particular. Thanks in advance.

**Comment by eamonnmcmanus** [comment]
This is an interesting idea, but the example isn't completely accurate. The "before" case should look like this:

```java
@AutoValue public abstract class Foo {
  public static Builder builder() {
    return new AutoValue_Foo.Builder().bar(3);
  }

  public abstract int bar();
  public abstract String baz();
  
  @AutoValue.Builder
  public interface Builder {
    Builder bar(int x);
    Builder baz(String x);
    Foo build();
  }
}
```

Then the "after" case would look like this (I think):

```java
@AutoValue public abstract class Foo {
  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  public abstract int bar();
  public abstract String baz();
  
  @AutoValue.Builder
  public interface Builder {
    default int bar() {
      return 3;
    }
    Builder bar(int x);
    Builder baz(String x);
    Foo build();
  }
}
```

The generated `AutoValue_Foo.Builder` class might look like this:

```java
class AutoValue_Foo extends Foo {
  ...
  static class Builder implements Foo.Builder {
    private int bar;
    private String baz;

    Builder() {
      this.bar = Foo.Builder.super.bar();
    }

    @Override public int bar() {
      return bar;
    }
    ...
```

This shows that it is an extension of the existing feature whereby a builder can have both `Builder bar(int x)` to set the value of `x`, and `int bar()` to retrieve the currently-set value.

This is a novel suggestion, but at first glance it seems kind of confusing. The default `bar()` defines what the default value of the property will be. But then calling `bar()` returns what the property value actually is, through an invisible override. I'm not sure I would guess that that was what the code meant if I ran across this for the first time. Also, this would be a *second* way to define default values, since the existing way will certainly have to continue working.

If you wanted to have the default values shown in the `Builder` itself, you could achieve that this way with the current system:

```java
@AutoValue public abstract class Foo {
  public static Builder builder() {
    return new AutoValue_Foo.Builder().withDefaultValues();
  }

  public abstract int bar();
  public abstract String baz();
  
  @AutoValue.Builder
  public interface Builder {
    default Builder withDefaultValues() {
      return bar(3).baz("three");
    }
    Builder bar(int x);
    Builder baz(String x);
    Foo build();
  }
}
```

So I'm not convinced we need to define another mechanism for it.

**Comment by kevinmost** [comment]
Ah sorry, that's what I get for creating classes directly in the Github issues text-box rather than copy-pasting from the IDE.

You're right that the builder methods should have a parameter, of course. 

My initial thought was that you could define the default impl there, so the builder would look something like:

```
@AutoValue.Builder
public interface Builder {
  default Builder bar(int bar) { return 3; }
  Builder baz(String baz);
  Foo build();
```

But it raises the question of what the generated impl would pass as a parameter when it calls that method. Maybe `null` for objects and `0`/`false` for primitive numerics/boolean? And, if it's possible to detect usages of parameters in method bodies in annotation processors (not sure if that's doable), AutoValue could throw a build error if the parameter is used in the default impl.

I know the value of a mechanism like this isn't super-apparent in this example, but once you have 5, 10, or even more properties on an AutoValue object, it's very noisy IMHO to determine which values are required and which are optional with the current implementation. Having the default impls next to the properties themselves feels a lot like a Kotlin data class, where if a property is optional, it's very clearly expressed what the default value is right next to the property.

**Comment by eamonnmcmanus** [comment]
You can't `return 3` from a method whose return type is `Builder`.

I still think the `withDefaultValues` method is sufficient to address the difficulty you perceive.

**Comment by kevinmost** [comment]
I would still argue that the `withDefaultValues` method isn't really changing much, besides moving the block of code that defines the defaults from one place to another. It seems to me like the main advantage is that autocomplete works before compiling, since you're calling methods on `Builder`, not the generated `AutoValue_Foo.Builder`. Though it also has the slight disadvantage of polluting the `Builder` type with a method that is only used by the `.builder()` factory method.

My goal was less about having the default values shown in the builder, and more about having the default values next to their respective properties (or the builder methods for those properties). It feels like a more logical association to me, but this may be a difficulty that others don't perceive when using AutoValue.

You're right, of course, that my last suggestion was invalid; I was thinking along the lines of:

```
@AutoValue public abstract class Foo {
  public static Builder builder() { return new AutoValue_Foo.Builder(); }

  public int bar() { return 3; } // optional property
  public abstract String baz(); // required property

  @AutoValue.Builder public interface Builder {
    Builder bar(int bar);
    Builder baz(String baz);
    Foo build();
  }
}
```

(maybe requiring the use of a `@HasDefaultValue` or similar annotation so that it's explicit, like a `@Memoized` property), but I could see the argument that this could lead to confusing scenarios. And I assume that the implementation would be tricky (or impossible?), as you can't just invoke the `Foo#bar()` default implementation from the `Builder#build()` method before the instance of `Foo` has been built.

Anyway, thanks for your consideration on this.

**Comment by tbroyer** [comment]
Fwiw, Immutables does something similar: https://immutables.github.io/immutable.html#default-attributes
```java
@Value.Style(visibility = ImplementationVisibility.PACKAGE)
@Value.Immutable
public abstract class Foo {
  public static Builder builder() { return new ImmutableFoo.builder(); }

  @Value.Default
  public int bar() { return 3; }
  public abstract String baz();

  public interface Builder {
    Builder bar(int bar);
    Builder baz(String baz);
    Foo build();
  }
}
```
(the `@Value.Style` changes the visibility of the generated classes, to make them similar to AutoValue: https://immutables.github.io/immutable.html#hide-implementation)

**Comment by eamonnmcmanus** [comment]
We've generally tried to keep the specification of AutoValue as simple as possible while addressing what most people need. Since there's already a way to specify default values, and it's not *too* onerous, we're probably not going to be motivated to do anything like the `@Value.Default` that @tbroyer mentions.
