### ISSUE TITLE
AutoValue java files could be found in the APK

### ISSUE THREAD

**Issue by osana** [google/auto#706]
The issue was reported by a customer of Android [Mapbox sdk](https://github.com/mapbox/mapbox-gl-native). Android sdk uses [Mapbox Java Services SDK](https://github.com/mapbox/mapbox-java) which in turn uses AutoValue. 

The artifact is expected to contain AutoValue .class files (compiled Java classes) but not the .java files (source code). Looking at the extract, these are all AutoValue generated files:
![image](https://user-images.githubusercontent.com/32496536/53769314-88fa2200-3ea9-11e9-84dc-577e2cdabb84.png)

Here is a snipet from a build.gradle file where autovalue is added:
    compileOnly dependenciesList.autoValue
    compileOnly dependenciesList.autoValueGson

dependenciesList is defined as:
  dependenciesList = [
      autoValue           : "com.google.auto.value:auto-value:${version.autoValue}",
      autoValueGson       : "com.ryanharter.auto.value:auto-value-gson:${version.autoValueGson}" ..]

  version = [
      autoValue        : '1.6.2',
      autoValueGson    : '0.8.0', .. ]

**Comment by JakeWharton** [comment]
This is a toolchain failure and not anything wrong with this library. Most annotation processors generate Java source which usually winds up in the same directory as the class files they get compiled into. Whatever toolchain you're using needs to ensure that these are filtered out from any resulting binaries.

**Comment by tbroyer** [comment]
Specifically, this has been fixed Gradle 5.2 (at least for non-Android projects). Make sure the `JavaCompile` tasks have their `options.annotationProcessorGeneratedSourcesDir` set.

…or filter them out from packaging.
