### ISSUE TITLE
auto-service 1.0 rc5 release malformed

### ISSUE THREAD

**Issue by JakeWharton** [google/auto#714]
No auto-service artifact update, auto-service-annotation artifact missing, new auto-service-aggregate artifact only one present.

https://search.maven.org/search?q=g:com.google.auto.service

**Comment by mattdarwin** [comment]
Also, why was it 1.0-rc5 and not just 1.0 ?

**Comment by ronshapiro** [comment]
Hm, looks like my maven-fu did not properly coordinate this when I tried to split out the annotations and the processor into different artifacts. Let me see if I can do something to fix this quickly and then find the root issue

**Comment by ronshapiro** [comment]
This should be fixed now. https://oss.sonatype.org/content/repositories/public/com/google/auto/service/auto-service-annotations/ is resolving

**Comment by JakeWharton** [comment]
Looks good!
