### ISSUE TITLE
Gradle may disable incremental compilation as the following annotation processors are not incremental: auto-service-1.0-rc5.jar

### ISSUE THREAD

**Issue by JarvisGG** [google/auto#716]

**Comment by tbroyer** [comment]
See https://github.com/google/auto/issues/703#issuecomment-476500875

**Comment by tbroyer** [comment]
Will be fixed by https://github.com/google/auto/commit/cf61cff62b6f822604d09620f6997097d5ba57e2 once #719 is merged

**Comment by cesar1000** [comment]
Are you planning a new release with this fix soon? He have a bunch of test modules using this annotation processor that could really do with the incremental compilation :)
