### ISSUE TITLE
@AutoService没用？

### ISSUE THREAD

**Issue by 401825317** [google/auto#717]
![image](https://user-images.githubusercontent.com/19526136/55397659-3cbe0280-5579-11e9-8238-af8adce78008.png)
![image](https://user-images.githubusercontent.com/19526136/55397705-60814880-5579-11e9-83a0-e09946a0e85e.png)
请问是哪种情况引起的呢？
下边是mavan打包pom.xml
![image](https://user-images.githubusercontent.com/19526136/55397763-860e5200-5579-11e9-9f09-8119c41653cc.png)

**Comment by tbroyer** [comment]
The generated file will be in `${project.build.outputDirectory}/META-INF/services/…`, did you check there?
You seem to be copying `${project.build.outputDirectory}` to `WEB-INF/classes`, but you're only showing the sibling `META-INF/`, whereas your `fileSet` would put the file into `WEB-INF/classes/META-INF/services/…`

**Comment by 401825317** [comment]
> The generated file will be in `${project.build.outputDirectory}/META-INF/services/…`, did you check there?
> You seem to be copying `${project.build.outputDirectory}` to `WEB-INF/classes`, but you're only showing the sibling `META-INF/`, whereas your `fileSet` would put the file into `WEB-INF/classes/META-INF/services/…`

你好，motoband_service项目引用了motoband-core，core JAR自动打包的时候已经包含META-INF下得service文件夹了，motoband_service项目中使用ServiceLoader.load(TIMCallBackParse.class)却没有找到结果。我现在只能手动在motoband_service项目中手动生成service文件夹

**Comment by tbroyer** [comment]
If the `META-INF/services/…` is correctly present in your `core` project, then AutoService did its job as expected, and you're having a different problem (apparently related to packaging and/or deployment): if you remove AutoService from the `core` project and instead create the service file manually in there, you'll probably have the same problem.

The best place to get help would likely be StackOverflow (or other forums) then, as it looks like this is actually unrelated to AutoService.
