### ISSUE TITLE
Errors related to child class members not being implemented

### ISSUE THREAD

**Issue by Purus** [google/auto#735]
I have something similar as below.

```
abstract static class AbstractParentWithBuilder {
    abstract String foo();

    abstract static class Builder<B extends Builder<B>> {
      abstract B foo(String s);
    }
  }

  @AutoValue
  abstract static class ChildWithBuilder extends AbstractParentWithBuilder {
    abstract String bar();

    static Builder builder() {
      return new AutoValue_AutoValueTest_ChildWithBuilder.Builder();
    }

    @AutoValue.Builder
    abstract static class Builder extends AbstractParentWithBuilder.Builder<Builder> {
      abstract Builder bar(String s);

      abstract ChildWithBuilder build();
    }
  }
```

After the compiler generates the annotation code, the IDE complains that the members of the AbstractParentWithBuilder class(foo in this case) is not implemented.

What I am missing? I am usign the latest version of Auto Value in the recent version of IntelliJ. I manually compile the class to generate the annotations.

**Comment by eamonnmcmanus** [comment]
Can you copy and paste the actual code that doesn't work? The code above obviously does work because it's [here](https://github.com/google/auto/blob/master/value/src/it/functional/src/test/java/com/google/auto/value/AutoValueTest.java#L2315).

**Comment by Purus** [comment]
I was able to solve the above issue. Now I get different issue now. Below is the code.

This is the parent class.

public abstract class BaseModel {
    public abstract String url();

    public abstract Map<String, String> headers();

    public abstract static class Builder<T extends Builder<T>> {
        abstract public T url(String value);

        abstract public T headers(Map<String, String> value);
    }
}

Below is the child class:

@AutoValue
public abstract class ChildModel extends BaseModel {
    static public Builder builder() {
        return new AutoValue_ChildModel.Builder();
    }

    @AutoValue.Builder
    abstract public static class Builder extends BaseModel .Builder<Builder> {
        abstract public ChildModel.build();
    }
}

I get the below error in IDE.

`Reference to builder is ambigous, both 'ChildModel.Builder' and 'BaseModel.Builder' match`

**Comment by Purus** [comment]
Also during build I get this error.

`Error:java: Method does not correspond to a property of ChildModel `

**Comment by Purus** [comment]
Fixing the build issue resolved all other issues. Thanks.
