### ISSUE TITLE
Please document that a property which is itself an autovalue and has a builder is created automatically

### ISSUE THREAD

**Issue by david-gang** [google/auto#736]
Given 
```
@Autovalue
public abstract class A {
public abstract B getB();
public static Builder builder() {
        return new A.Builder().build()
}

}
```
class B is also an autovalue and has a builder

What happens that the following code is generated in the builder
```
else if (this.b == null) {
        B.Builder b$builder = B.builder();
        this.b = b$builder.build();
      }
```
so no value needs to be supplied.

I looked for the documentation of this in the wiki but did not find it.

I tracked the behavior to:
https://github.com/google/auto/blob/6b9005c0fa68b45a3788878e1383f2f713062d4e/value/src/main/java/com/google/auto/value/processor/PropertyBuilderClassifier.java#L181
and 
https://github.com/google/auto/commit/c8c00a9adde3e355238d430e71e95c8688cdfe67

Would it be possible to document this or do you see this as private implementation detail which can be changed at any moment?

**Comment by eamonnmcmanus** [comment]
This is documented [here](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-access-nested-builders-while-building). If you can think of a way the documentation could have helped you find that, we would certainly appreciate it.
