### ISSUE TITLE
How to determine if a class implements an interface

### ISSUE THREAD

**Issue by OuyuBa** [google/auto#743]
How to determine if a class implements an interface

**Comment by jbduncan** [comment]
@OuyuBa Have you considered using [`Class.isAssignableFrom`](https://stackoverflow.com/questions/12145185/determine-if-a-class-implements-a-interface-in-java#12145210), Apache Commons' [`ClassUtils.getAllInterfaces`](https://stackoverflow.com/questions/6616055/get-all-derived-interfaces-of-a-class#6616098) or ClassGraph's [`ClassInfo.getInterfaces`](https://github.com/classgraph/classgraph/wiki/API:-ClassInfo#classinfo)? :)

**Comment by JakeWharton** [comment]
Is this a question about writing an extension to auto-value? If yes, those suggestions won't work since you need to use the mirror APIs not the reflection APIs. If no, then I'm not sure why it's an issue on this project...

**Comment by eamonnmcmanus** [comment]
I'm closing this because the question is too vague, but feel free to clarify in comments and I will reopen if appropriate.
