### ISSUE TITLE
AutoFactory integration test wrong name

### ISSUE THREAD

**Issue by Zubnix** [google/auto#77]
bad c/p. auto factory integration test is called auto-value integration test.

**Comment by kluever** [comment]
So the test is just incorrectly named? Seems minor, but worth fixing (if it's still an issue).

**Comment by eamonnmcmanus** [comment]
I don't know what this is referring to, and I was unable to find anything in the sources that might correspond to it. So most likely this is a problem that has been fixed some time in the intervening five years.
