### ISSUE TITLE
AutoValue should fail if Builder annotations violate invariants

### ISSUE THREAD

**Issue by ekchang** [google/auto#777]
One element where human error can occur when writing the AutoValue class + Builder is if the setter/getter Nullability annotations are mismatched:

```
@AutoValue
public abstract class Foo {

  public abstract String value();

  @AutoValue.Builder
  public static abstract class Builder {

    public abstract Builder value(@Nullable String value);

    public abstract Foo build();
  }
}
```

Here, the Builder declares it allows a nullable field but the immutable type does not. What is the expected behavior? 

Here is the generated class:
```
@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_Foo extends Foo {

  private final String value;

  private AutoValue_Foo(
      String value) {
    this.value = value;
  }

  @Override
  public String value() {
    return value;
  }

  static final class Builder extends Foo.Builder {
    private String value;
    Builder() {
    }
    @Override
    public Foo.Builder value(@Nullable String value) {
      if (value == null) {
        throw new NullPointerException("Null value");
      }
      this.value = value;
      return this;
    }
    @Override
    public Foo build() {
      String missing = "";
      if (this.value == null) {
        missing += " value";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_Foo(
          this.value);
    }
  }

}
```

The implementation does propagate the `@Nullable` annotation as defined by the Builder, but also enforces nonnull-ness by throwing an NPE. I believe in this scenario, AutoValue should fail the codegen step since this is likely user error.

The reverse should be fine (where the getter is looser in terms of `@Nullable` but Builder wants non-null inputs only) but I cannot imagine where the above is ever done intentionally and can only lead to error prone use of the generated Builder.

**Comment by eamonnmcmanus** [comment]
It's a reasonable request. There's a possibility of breaking some existing code, but if that happens the fix is just to remove the `@Nullable` annotation on the builder method parameter, which shouldn't have been there since the parameter can not in fact be null.
