### ISSUE TITLE
Tests AutoServiceProcessorTest are incorrect

### ISSUE THREAD

**Issue by dparamoshkin** [google/auto#778]
Tests are checking that the annotation processor generates files ("META-INF/services/test.SomeService", etc), but files are already existing in the repo, and no cleanup stage in tests. Also tests not checking the content of the "generated" files

**Comment by tbroyer** [comment]
AFAICT the compile-testing library will check that those files were actually generated (through the `Filer` and the fact that they also exist on the classpath won't matter.

BTW, you'll note that only `test.SomeService` and `test.SomeServiceMulti` exist, not `test.AnotherService` neither `test.AnotherServiceMulti`.

That being said, yes, the test could (and probably should) check the content of those files.

**Comment by dparamoshkin** [comment]
It seems compile-testing library have the bug then, because if you remove files from META-INF folder test would fail.

> BTW, you'll note that only test.SomeService and test.SomeServiceMulti exist, not test.AnotherService neither test.AnotherServiceMulti.

I see all 4 in master brunch

And if i remove those files and run `mvn test` i get

`Tests in error: 
  multiService(com.google.auto.service.processor.AutoServiceProcessorTest): resource META-INF/services/test.SomeServiceMulti not found.
  autoService(com.google.auto.service.processor.AutoServiceProcessorTest): resource META-INF/services/test.SomeService not found.`

**Comment by tbroyer** [comment]
> It seems compile-testing library have the bug then, because if you remove files from META-INF folder test would fail.
> 
> > BTW, you'll note that only test.SomeService and test.SomeServiceMulti exist, not test.AnotherService neither test.AnotherServiceMulti.
> 
> I see all 4 in master brunch

Ah yes, sorry; bad search on my side.

> And if i remove those files and run `mvn test` i get
> 
> `Tests in error: multiService(com.google.auto.service.processor.AutoServiceProcessorTest): resource META-INF/services/test.SomeServiceMulti not found. autoService(com.google.auto.service.processor.AutoServiceProcessorTest): resource META-INF/services/test.SomeService not found.`
> 
> In first glance it looks like it writes file in memory, but reads from file system

Actually, we both read the test wrong: what fails when you delete the file is the `JavaFileObjects.forResource("META-INF/services/test.SomeService")`, which reads the file from the classpath. That file is then passed to `generatesFiles`, which will check both its name and its content.

So, actually, the test checks that files with the same content (and same "kind") as the ones from the repo have been generated (incidentally, it doesn't check the file names, only their content; maybe it should check the names too ?)

IOW, the files from the repo are the "golden files" for the test.

**Comment by dparamoshkin** [comment]
Thank you and sorry, was my mistake. Works like you described
