### ISSUE TITLE
New release of auto service 1.0-rc7 (to tackle guava CVE)

### ISSUE THREAD

**Issue by iemejia** [google/auto#783]
The latest published version of AutoService available on maven central is 1.0-rc6. This version uses guava 20.0. Since [guava 20.0 has reported security vulnerabilities](https://ossindex.sonatype.org/vuln/24585a7f-eb6b-4d8d-a2a9-a6f16cc7c1d0), maybe it is a good idea to do a new release of  AutoService (specially considering that the fix is already in master).
--

**Comment by netdpb** [comment]
It looks to me like [1.0-rc6](https://mvnrepository.com/artifact/com.google.auto.service/auto-service/1.0-rc6) uses Guava 27.1-jre, not Guava 20.0.

That's not the latest Guava (which is 28.1), but is past the range of that vulnerability.

I'll close this issue for now. Please reopen if I've misunderstood something.

**Comment by iemejia** [comment]
My excuses you are right. I have misread the dependency report (generated from some CVE auth bot). Everything ok :+1:
