### ISSUE TITLE
Missing Check against Null

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/auto#796]
https://github.com/google/auto/blob/bffac145b41c24424bbce8197f5a8eee22c7e13f/value/src/main/java/com/google/auto/value/processor/TemplateVars.java#L157
The program can dereference a null-pointer because it does not check the return value of a function that might return null.

**Comment by tbroyer** [comment]
Except in practice it won't ever happen AFAICT: `readerFromUrl` is called from `retryParseAfterException`, which itself is called by `parsedTemplateForResource` in specific conditions, namely when `Template.parseFrom` (from escapevelocity) and/or `readerFromUrl` throw an `IOException`, `NullPointerException`, or `IllegalStateException`. `readerFromUrl` will do the null-check and throw an `IllegalArgumentException` in that case:
https://github.com/google/auto/blob/bffac145b41c24424bbce8197f5a8eee22c7e13f/value/src/main/java/com/google/auto/value/processor/TemplateVars.java#L139-L143
and `Template.parseFrom` won't catch this exception:
https://github.com/google/escapevelocity/blob/escapevelocity-0.9.1/src/main/java/com/google/escapevelocity/Template.java#L109-L114
So, if “no resource with this name is found, the resource is in a package that is not open to at least the caller module, or access to the resource is denied by the security manager” (from the javadoc of both `getResourceAsStream` and `getResource`), `parsedTemplateForResource` will throw an `IllegalArgumentException`, and `readerFromUrl` won't ever be called in the case.

**Comment by eamonnmcmanus** [comment]
Thanks @QiAnXinCodeSafe for the report and @tbroyer for the detailed analysis! I agree with the analysis. It looks as if this was detected by some automated tool? I wouldn't mind adding a redundant check here for improved clarity.
