### ISSUE TITLE
IDE can't recognice AutoAnnotation_Class_method

### ISSUE THREAD

**Issue by Andre601** [google/auto#803]
I have a weird error, where my IDE (IntelliJ IDEA) doesn't recognize `AutoAnnotation_<Class>_<method>` and gives a `Cannot resolve Symbol ...` error.

While the code still seems to work is this still quite an issue for me as it constantly shows this "error".

This here is the code I setup with the AutoAnnotation:
```java
public final class LangUtils {
    @Inject @Lang("de") private static FileConfiguration de;
    @Inject @Lang("en") private static FileConfiguration en;

    @AutoAnnotation
    public static Lang lang(String value) {
        return new AutoAnnotation_LangUtils_lang(value);
    }

    public static String get(String language, String path) {
        switch (language.toLowerCase()) {
            case "de":
                return de.getString(path);

            case "en":
                return en.getString(path);

            default:
                throw new UnsupportedOperationException("That language doesn't exist.");
        }
    }
}
```

The `@Lang(String)` annotation is a `@interface` used to assign different languages available:
```java
@BindingAnnotation
@Retention(RetentionPolicy.RUNTIME) @Target({ElementType.FIELD, ElementType.PARAMETER})
public @interface Lang{
    String value();
}
```
And `FileConfiguration` is from a framework I use, that also makes use of the AutoAnnotation.

The dev of the framework I use says that he doesn't face the issues I encounter and can't really help solving this.

My question now is, if there is a possible fix or at least a way to suppress this error.

**Comment by tbroyer** [comment]
This is an issue with the configuration of your project in your IDE, so:
* which build tool are you using (if any): Maven? Gradle?
* which version of IntelliJ IDEA are you using? (things have changed wrt annotation processing in almost all recent versions)

**Comment by Andre601** [comment]
I use Gradle 4.8.1 on IntelliJ 2019.3 (Was just recently updated)

**Comment by tbroyer** [comment]
Gradle 4.x is a bit old. Update to 5.x (at least 5.2) if you can, or use my `net.ltgt.apt-idea` plugin with older versions (or you could configure IDEA manually, though customizations might go away at each Gradle refresh)
See https://github.com/tbroyer/gradle-apt-plugin for details.

**Comment by Andre601** [comment]
I'll look into the gradle-apt-plugin as I can't update gradle to 5.2, since I use deprecated methods making it incompatible with 5.x releases.

**Comment by Andre601** [comment]
I'm not sure if I do something wrong.
I just added `id 'net.ltgt.apt-idea' version '0.21'` to the plugins list in the build.gradle and the files were successfully downloaded.
Do I need to do any extra steps, as the `AutoAnnotation_LangUtils_lang` still shows red with the same error.

![image](https://user-images.githubusercontent.com/11576465/71297233-e9981400-2382-11ea-82b5-d1ca0f346ada.png)

**Comment by Andre601** [comment]
I now downloaded Gradle 5 but even with that installed, does this error occur.

**Comment by Andre601** [comment]
The issue seems to have fixed itself now after some time.
No real idea what exactly the cause was. Maybe a recent refresh of Gradle's dependencies?
Anyway, I close this now as it seems to be fixed now. Thanks for all the suggestions on how to fix it.
