### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by ruwaid4** [google/auto#812]
In Auto/Value - TypeVariables.Java The following line:
```
if (substitutedParameterType.getKind().equals(TypeKind.WILDCARD)) {
```
Part of:
```
TypeMirror formalParameterType = method.getParameters().get(0).asType();
SubstitutionVisitor substitutionVisitor = new SubstitutionVisitor(typeVariables, typeUtils);
TypeMirror substitutedParameterType = substitutionVisitor.visit(formalParameterType, null);
if (substitutedParameterType.getKind().equals(TypeKind.WILDCARD)) {
```
is unneeded since there is no ExecutableElement with wildcards as parameters since it is against compiler rules. Therefore anything inside the if-statement is unreachable.

**Comment by eamonnmcmanus** [comment]
I think you may be misreading the code. There is a comment inside the `if` that says why it is there. [This test line](https://github.com/google/auto/blob/b50f30a/value/src/it/functional/src/test/java/com/google/auto/value/AutoValueJava8Test.java#L786) will fail to compile without the `if`.
