### ISSUE TITLE
@AutoService to generate META-INF/gradle-plugins as well for standalone gradle plugins

### ISSUE THREAD

**Issue by kostasdrakonakis** [google/auto#813]
When creating standalone `Gradle` plugin we have to generate some files under `META-INF/gradle-plugins` .

I understand that the problem arises when you have to pick the correct name for the custom plugin.

I was thinking that maybe we can add an argument `pluginName`  to the `@AutoService` annotation or we can add another annotation like `@Plugin` where we could specify the name.

Example:

* pluginName

```kotlin
package com.example

@AutoService(value= [Project::class], pluginName = "com.domain.my_custom_plugin")
class CustomStandAlonePlugin : Plugin<Project> {
```
* different annotation

```kotlin
package com.example

@AutoService(Project::class)
@Plugin("com.domain.my_custom_plugin")
class CustomStandAlonePlugin : Plugin<Project> {
```

So when the processor will generate it should generate a file under `META-INF/gradle-plugins`:

`com.domain.my_custom_plugin.properties`

and the entry to this file should be:

`implementation-class=com.example.CustomStandAlonePlugin`

Is there any intention on adding the above feature to auto service?

**Comment by vlsi** [comment]
Gradle has Precompiled Script Plugins: https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins

In other words, if you name a file like `src/main/kotlin/java-library-convention.gradle.kts`, then Gradle automatically generates metadata to make it a `java-library-convention` plugin (it generates `META-INF/gradle-plugins/java-library-convention.properties`)

**Comment by tbroyer** [comment]
The `java-gradle-plugin` will also generate the plugin descriptors from DSL in the build script: https://docs.gradle.org/current/userguide/java_gradle_plugin.html

**Comment by vlsi** [comment]
In other words, I suggest closing the issue as "not planned" as Gradle provides enough services to generate `META-INF/gradle-plugins`.
