### ISSUE TITLE
When I use @Repeatable, IDEA will prompt duplicate annotations

### ISSUE THREAD

**Issue by jxnu-liguobin** [google/auto#816]
I use @Repeatable and @AutoService because I need to implement a repeatable annotation,env: JDK 8, Scala 2.11.6 Play2.5, but IDEA will prompt duplicate annotations when running.
I don't know if it's not supported by AuthService or if I have a problem with the Way of using. thanks

**Comment by nglorioso** [comment]
`@AutoService` isn't a repeatable annotation (i.e.: you can't put multiple `@AutoService` annotations on the same class).

However, you can use a single `@AutoService({Foo.class, Bar.class})` annotation for a class that implements both `Foo` and `Bar` that you want to be service-located for either of the two classes.

**Comment by jxnu-liguobin** [comment]
I don't mean that. I mean that I use the @repeatable annotation to implement the repeated annotation, and use the @autoservice (only use one) to bind the abstract processor impl to implement it to the processor.

**Comment by nglorioso** [comment]
Using `@AutoService` on the annotation processor shouldn't have anything to do with whether or not IDEA (or javac) recognizes `@Person` as a repeatable annotation (which I think is the error you're experiencing from "IDEA will prompt duplicate annotations when running").

Unfortunately, I can't quite do much more remote debugging, so I'm going to keep this closed, but I'd try and build things with other build tools (`sbt`?) to see if you're getting the same errors outside of IntelliJ. You could also consider adding logging to your annotation processor's process method to see if it's getting invoked appropriately.
