### ISSUE TITLE
MoreElements.getLocalAndInheritedMethods does not return the most specific types for method with same signature

### ISSUE THREAD

**Issue by victornoel** [google/auto#825]
Hi,

Taking the the following code:
```java
public interface ASuperInterface1 {
  Double test();
}
public interface ASuperInterface2 {
  Number test();
}
public interface AnInterface extends ASuperInterface1, ASuperInterface2 {}
```

~Calling `MoreElements.getLocalAndInheritedMethods` on the `TypeElement` corresponding to `AnInterface` gives me a method `Number test()` instead of `Double test()`.~ edit: this is no longer true since [auto-common 1.2](https://github.com/google/auto/releases/tag/auto-common-1.2), now the two methods are simply returned.

I believe `MoreElements.getLocalAndInheritedMethods` should choose the more specific return type in that case.

**Comment by victornoel** [comment]
This is blocked by https://github.com/google/auto/issues/825

**Comment by victornoel** [comment]
https://github.com/google/auto/releases/tag/auto-common-1.2 was released with a change @eamonnmcmanus did where multiple methods with same signature but from different interfaces are now all present in the returned set.

I feel like that it thus mean that this bug is not a bug anymore @cpovirk.

Would one of you have an idea what would be the correct way of merging methods with same signature (or overriding) so that I can keep only the most specific one?

**Comment by eamonnmcmanus** [comment]
Thanks for the reminder, it does look as if we can close this issue.

About removing methods with the same signature, you could do something like this:

```java
List<ExecutableElement> methods = <methods with the same name and parameter types>;
Types typeUtils = processingEnv.getTypeUtils();
loop:
while (true) {
  for (var a : methods) {
    for (var it = methods.iterator(); it.hasNext(); ) {
      TypeMirror b = it.next();
      if (a != b && typeUtils.isSubtype(a.getReturnType(), b.getReturnType())) {
        it.remove();
        continue loop;
      }
    }
  }
  break;
}
```

You can use [`Types.isSubsignature`](https://docs.oracle.com/en/java/javase/17/docs/api/java.compiler/javax/lang/model/util/Types.html#isSubsignature(javax.lang.model.type.ExecutableType,javax.lang.model.type.ExecutableType)) to determine that methods have the same name and parameter types. The code here will retain a method with a more specific return type (for example if `Object foo()` is overridden by `String foo()`).

This is pretty ugly, and I haven't tested it. Maybe we should add a method to `MoreElements` to do it. (I also suspect there might be some trickiness to getting it right in the presence of raw types.)

**Comment by victornoel** [comment]
@eamonnmcmanus great, thx a lot, indeed this kind of approach should do the trick and yes, it would be great to have a method in auto-common to do this out of the box, I guess in the context of a given type to resolve the potential type parameters (basically it is like MoreElements.overrides but without the checks about the owning interfaces?)
