### ISSUE TITLE
Thoughts on new annotation for provided parameters that do not change?

### ISSUE THREAD

**Issue by stoyicker** [google/auto#829]
I often find myself creating providers that just provide a field that they take in the constructor. This requires me to manually write, test and maintain the provider and also adds runtime "overhead" that could be skipped if the factories that use this kind of provider could instead hold a direct reference to the field itself. An example of how this could work would be by using a new annotation, say @Final for example:
```java
@AutoFactory
MyClass(@Final Foo _foo, Bar _bar) {
...
} 

// would generate...

public MyClassFactory {
  private final Foo foo;

  public MyClassFactory(Foo _foo) {
    foo = _foo;
  }

  MyClass create(Bar _bar) {
    return new MyClass(foo, _bar);
}
```
Would this be a valid feature?

**Comment by cgdecker** [comment]
It looks like this would be API-generating, which is something auto is generally against.

**Comment by stoyicker** [comment]
I'm not sure I'm following. What does API-generating mean? As in, it would grow the API? I understand that can be bad in some cases, but is it in this one? Why would anyone want to use a tool that cannot solve what (I think) is a pretty common use case and without a doubt relevant to the very goal of the tool (talking about auto-factory in particular here), regardless of how small its API may be?
Not to mention that, proposal patch aside (I can prepare one if you think that it could help the discussion), in my head at least this looks like a non-breaking change, only adding one annotation as far as API is concerned, and relatively small overall.

**Comment by ronshapiro** [comment]
It looks like this is the same as the current autofactory implementation, except to use `Foo` instead of `Provider<Foo>` for the fields of the factory? If you have fields, can you just write `() -> myFoo`? 

AutoFactory was written for close usage with `javax.inject`, so in that context there isn't much need for this feature. It wasn't intended for handwritten usage.

**Comment by stoyicker** [comment]
My goal is to avoid having the function call at all **while** writing as little code as possible. If I write () -> myFoo I still have an extra unnecessary function every time I invoke the factory call and need to write a "useless" anonymous class.

But I see the API problem with the limitation of javax.inject. Would it be acceptable to slightly "abuse" the purpose of @Singleton to put it on the parameters that can be provided directly? I know the documentation says that it describes [types that are only instantiated once](https://docs.oracle.com/javaee/7/api/index.html), but it doesn't have @Target(ElementType.TYPE) (it does not have target restriction at all actually) and for example Dagger 2 allows it to be used on methods for scoping, so one could argue that there's a reasoning for it to cover this use case in AutoFactory.

**Comment by ronshapiro** [comment]
If you really don't want the simple lambdas, I think you're better off creating a fork of AutoFactory.

**Comment by stoyicker** [comment]
Alright I see, thanks
