### ISSUE TITLE
UnnecessaryParentheses issue in generated hashCode() method flagged by error prone 

### ISSUE THREAD

**Issue by davido** [google/auto#849]
Similarly to #670, the recent EP version (2.3.5-SNAPSHOT) is flagging the generated code as invalid:

```
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/util/cli/_javac/cli/libcli_sourcegenfiles/com/google/gerrit/util/cli/AutoAnnotation_OptionUtil_newOption.java:220: error: [UnnecessaryParentheses] These grouping parentheses are unnecessary; it is unlikely the code will be misinterpreted without them
        + (-176714719 ^ (Arrays.hashCode(forbids)))
                        ^
    (see https://errorprone.info/bugpattern/UnnecessaryParentheses)
  Did you mean '+ (-176714719 ^ Arrays.hashCode(forbids))'?
```

**Comment by eamonnmcmanus** [comment]
Is this an `@AutoValue` class? Could you include a snippet of the relevant code?

**Comment by davido** [comment]
It's AutoAnnotation class. The source is here: [1].

[1] http://paste.openstack.org/show/793723

**Comment by kluever** [comment]
This is just an error prone warning, right? It should _not_ be a compile error / "invalid code".

**Comment by davido** [comment]
It's just a warning in a generated class and it's ignored by EP then and only then, if you have this option in EP configuration: "-XepDisableWarningsInGeneratedCode".

However, even with that option, if you promote the check "-Xep:UnnecessaryParentheses:ERROR" to severity error, then all occurrences of that check are flagged, even in generated classes. That's because that feature request in EP was never implemented [1].

Conclusion: it would be a great feature to fix generated code to be warning free.

[1] https://github.com/google/error-prone/issues/808

**Comment by kluever** [comment]
Removing the warning in AutoValue sounds reasonable, but very low priority.

I'd strongly recommend against promoting `UnnecessaryParentheses` to a compile error -- in software you very infrequently control every dependency, and having to file bugs like this over something as silly as an extra set of parens seems like it'll drive a sane person crazy :-)

**Comment by davido** [comment]
> I'd strongly recommend against promoting UnnecessaryParentheses to a compile error -- in software you very infrequently control every dependency [...]

I can report that with Bazel, you can control for what package you are promoting the severity levels of checks. So that they are only activated for my own packages and not third party dependencies, except well for the generatde code: [1]. C'est tout.

[1] https://github.com/GerritCodeReview/gerrit/blob/master/tools/BUILD#L20-L115
