### ISSUE TITLE
@AutoService could be used without interface param

### ISSUE THREAD

**Issue by slavb18** [google/auto#859]
@AutoService could be used without interface param, like @javax.inject.Named 
Interface could be determined using reflection (e.g first interface in list) 

Example

```java
package foo.bar;

import javax.annotation.processing.Processor;

@AutoService
final class MyProcessor implements Processor {
  // …
}
```

**Comment by eamonnmcmanus** [comment]
I'm not sure there'd be much advantage. It's a tiny bit shorter in the source code, but it also requires the reader to understand what the implicit interface is going to be. In the example, if we had `final class MyProcessor extends AbstractProcessor`, would we still deduce an interface of `Processor`? Or might it be `AbstractProcessor`? (Services can be defined by abstract classes, after all.) I think it's much more straightforward just to say explicitly what the service type is.
