### ISSUE TITLE
AutoValue for Java 8 Interfaces

### ISSUE THREAD

**Issue by JakeWharton** [google/auto#86]
``` java
@AutoValue
public interface Human {
  static Human create(String name) {
    return new AutoValue_Human(name);
  }

  String name();
}
```

**Comment by ArturGajowy** [comment]
Actually, this would be more terse and readable than the abstract class with all abstract methods. WDYT?

**Comment by kevinb9n** [comment]
I see that it spares you from typing "abstract" on each accessor. And in the event that you *want* them to be public it spares you from typing that too. Is there any other terseness/readability gain I'm missing?

The choice to use an interface will restrict your freedom in a few ways:

- your accessors will have to be public
- you won't be able to have any other fields (like caching a derived value)
- you lose the option of preventing subtypes (by adding a package-visible constructor)

**Comment by ArturGajowy** [comment]
Still, I'd like to have this choice :) In reference to the restrictions you mention:
 - public accessors are quite common. In case they're not acceptable I can always switch to an abstract class
 - in most cases the value objects don't need to cache/carry additional data. In case it's needed, I can always switch to an abstract class :)
 - in most cases instead of having the empty package-private constructor (which needs a comment at least), I'd rather write a single test that would check by reflection that the `@AutoValue`-annotated interfaces only have one implementation each. Sure, this does not prevent implementations outside the project. If enforcing immutability outside the project is needed as well, I can always switch to an abstract class ;)

**Comment by kevinb9n** [comment]
It's already quite understood that these three restrictions are not massive
and that one can always switch back.

But I claim the benefit of skipping "public abstract" is also not massive.

If we did add this support, we would add a "best practice" to the user
guide suggesting not to even use the feature we're adding. Which should
always give us pause about adding it.




On Wed, May 20, 2015 at 3:32 PM, ArturGajowy <notifications@github.com>
wrote:

> Still, I'd like to have this choice :) In reference to the restrictions
> you mention:
>
>    - public accessors are quite common. In case they're not acceptable I
>    can always switch to an abstract class
>    - in most cases the value objects don't need to cache/carry additional
>    data. In case it's needed, I can always switch to an abstract class :)
>    - in most cases instead of having the empty package-private
>    constructor (which needs a comment at least), I'd rather write a single
>    test that would check by reflection that the @AutoValue-annotated
>    interfaces only have one implementation each. Sure, this does not prevent
>    implementations outside the project. If enforcing immutability outside the
>    project is needed as well, I can always switch to an abstract class ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/86#issuecomment-104062561>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by shmosel** [comment]
I think there is value in being able to omit `public abstract`, considering the main purpose of AutoValue is to reduce boilerplate. Allowing interfaces would also be more in the spirit of "not restricting your freedom" if it doesn't pose a concrete problem.

**Comment by rkraneis** [comment]
I could imagine that this could be investigated again when/if value types arrive and if they mandate not being subclasses of abstract classes. Then there would be a much stronger value proposition for having that feature besides omitting public (abstract).

**Comment by shmosel** [comment]
A possible workaround:
```java
public interface Human {
  static Human create(String name) {
    return new AutoValue_HumanImpl(name);
  }

  String name();
}

@AutoValue
abstract class HumanImpl implements Human {}
```
It's an extra bit of boilerplate, but it could pay off if there are enough properties.
