### ISSUE TITLE
AutoService fails for services with generics and verify = true

### ISSUE THREAD

**Issue by ogregoire** [google/auto#870]
`AutoService` fails when the service is a generic class **and** the `verify` option is set to `true`, even though the service provider is a concrete, no-generics class.

For instance:

**`test/ServiceWithGenerics.java`**

    package test;
    public interface ServiceWithGenerics<T> { }

**`test/ServiceWithGenericsProvider.java`**

    package test;
    @com.google.auto.service.AutoServiceAutoService(ServiceWithGenerics.class)
    public class ServiceWithGenericsProvider implements ServiceWithGenerics<Object> { }

The failure message is:

> ServiceProviders must implement their service provider interface. test/ServiceWithGenericsProvider does not implement test/ServiceWithGenerics

I'm expecting to see a `META-INF/services/test.Service` file with `test/ServiceWithGenericsProvider` as content.

This issue doesn't occur when the `verify` option isn't set or is set to `false`.

(By the way, I believe that all the tests should run with `verify` being `true`.)

**Comment by ogregoire** [comment]
Here's my test-case:

  @Test
  public void generics() {
    assertThat(
            JavaFileObjects.forResource("test/ServiceWithGenerics.java"),
            JavaFileObjects.forResource("test/ServiceWithGenericsProvider.java"))
        .withCompilerOptions("-Averify=true")
        .processedWith(new AutoServiceProcessor())
        .compilesWithoutError()
        .and().generatesFiles(
            JavaFileObjects.forResource("META-INF/services/test.ServiceWithGenerics"));
  }

**Comment by ogregoire** [comment]
I think I found a fix:

[This line](https://github.com/google/auto/blob/5ff5e37a22d0b439c963b2e079832338b5dad825/service/processor/src/main/java/com/google/auto/service/processor/AutoServiceProcessor.java#L228) should be replaced with:

    return types.isSubtype(types.erasure(providerImplementer.asType()), types.erasure(providerType.asType()));

**Comment by netdpb** [comment]
What's your use case for a generic service type? The service loader wouldn't be able to use any of the type parameters without unchecked casting.

**Comment by ogregoire** [comment]
I'm not using generics everywhere; only on the service.

I'm writing my own dependency injection system using no reflection but generating stuff on the fly using annotation processors, a bit like Dagger, but more simple that Dagger and without many features.

Each class with injection points is a service loaded by ServiceLoader at startup (instead of on the fly like Dagger), and I delegate the creation of the service files to AutoService.

I can't really do without generics because the generated code would become unreadable.

This is an example of 

**InjectionPoint** (user-written)

    class Hello { @Inject Hello(...) {  } }

**Service** (part of the API)

    interface Service<T> { ... }

**ServiceProvider** (generated)

    @AutoService(Service.class)
    class HelloService implements Service<Hello> { ... }

**Comment by ogregoire** [comment]
`T` is used as the type of the definition (`Class<T>`), as a return-type for the instance creation, etc. 

The following code is written by the user.

    class Injectee {
      @Inject Injectee (Dependency dependency) { }
    }

This results in something similar to the following code being generated:

    class InjecteeDefinition implements Definition<Injectee> {
      
      @Override public Injectee create(Injector injector) {
        return new Injectee(injector.getDefinition(Dependency.class).create(injector)); // some other methods can be called based on scope, qualifiers, etc.
      }
    }

I'm using JavaPoet to generate those so that the code can be read, debugged and so on, and if I don't keep it readable by using generics instead of casting everywhere, it's an open door for complexity and unmaintainability.

This is the base idea, but I believe you can extrapolate how the greater picture works.

**Comment by eamonnmcmanus** [comment]
So, just to spell this out, we might have a class something like this:

```
public class Injector {
  public <T> T getDefinition(Class<T> c) {...}
}
```

and an interface something like this:
```
public interface Provider<T> {
  T get();
}
```
that you use like this:

```
@AutoService(Provider.class)
public class MyFooProvider implements Provider<Foo> {...}
```

I think we're interested in what's in the body of `getDefinition`. I'm guessing something like this:

```
  private final Map<Type, Provider<?>> providers = getProviders();

  public <T> T getDefinition(Type t) {
    return providers.get(t);
  }

  private Map<Type, Provider<?>> getProviders() {
    Map<Type, Provider<?>> providers = new HashMap<>();
    for (Provider<?> provider : ServiceLoader.load(Provider.class) {
      Type type = providerTypeArg(provider.getClass());
      providers.put(type, provider);
    }
  }
```

where `providerTypeArg` uses reflection to extract `Foo` from `class MyFooProvider implements Provider<Foo>`, and possibly also from `class MyFooProvider implements GeneralFooProvider` and `interface GeneralFooProvider extends Provider<Foo>`.

It can be made to work, but I feel that the absence of support for generics in `ServiceLoader` (and in `META-INF/services`) makes it kind of wobbly. Still, it also doesn't feel as if `@AutoService` should be _preventing_ you from doing this.

Right now, the solution is just not to compile with `-Averify`, but obviously that's not great since it won't tell you if your purported `Provider` is even a `Provider` at all. On the other hand, the error that you get with `-Averify` is arguably justified since `MyFooProvider` does not in fact implement `Provider` as the `@AutoService` annotation claims; it implements `Provider<Foo>` which is a different thing.

**Comment by eamonnmcmanus** [comment]
Here's an idea. Perhaps we could emit a warning rather than an error when the annotated class does implement the given interface, but the interface has type parameter; and perhaps we could arrange for `@SuppressWarnings("rawtypes")` to suppress this warning when applied to the annotated class.

**Comment by ogregoire** [comment]
The basic injector is written as this:

    class DefaultInjector implements Injector {
      List<Definition<?>> definitions;
      DefaultInjector(ClassLoader classLoader) {
        definitions = ServiceLoader.load(Definition.class, classLoader).stream().map(p -> (Definition<?>)p.get()).collect(toList());
      }
      public <T> Definition<T> getDefinition(Class<T> type) {
        return definitions.stream()
          .filter(def -> def.type() == type || type.isAssignableFrom(def.type()))
          .map(ref -> (Definition<T>)ref)
          .findFirst().orElseThrow(() -> new RuntimeException("Unregistered definition for type " + type));
      }
    }

**Comment by eamonnmcmanus** [comment]
I made the change I suggested [above](https://github.com/google/auto/issues/870#issuecomment-679435261):

> we could emit a warning rather than an error when the annotated class does implement the given interface, but the interface has type parameter; and [...] we could arrange for `@SuppressWarnings("rawtypes")` to suppress this warning when applied to the annotated class.

**Comment by ogregoire** [comment]
> 
> 
> I made the change I suggested [above](https://github.com/google/auto/issues/870#issuecomment-679435261):
> 
> > we could emit a warning rather than an error when the annotated class does implement the given interface, but the interface has type parameter; and [...] we could arrange for `@SuppressWarnings("rawtypes")` to suppress this warning when applied to the annotated class.

This is perfect. The `@SuppressWarnings("rawtypes")` is a good tradeoff. Thanks!

**Comment by ogregoire** [comment]
This issue should probably be reopened for the reasons mentioned in the merged PR.
