### ISSUE TITLE
Bug in MoreTypes::equalLists

### ISSUE THREAD

**Issue by ogregoire** [google/auto#873]
The method `MoreTypes::equalLists` reads:

```
    Iterator<? extends TypeMirror> aIterator = a.iterator();
    Iterator<? extends TypeMirror> bIterator = b.iterator();
    while (aIterator.hasNext()) {
      if (!bIterator.hasNext()) {
        return false;
      }
      TypeMirror nextMirrorA = aIterator.next();
      TypeMirror nextMirrorB = bIterator.next();
      if (!equal(nextMirrorA, nextMirrorB, visiting)) {
        return false;
      }
    }
    return !aIterator.hasNext();
```

The last line should be the check on whether `b` has next, not whether `a` has next: `aIterator.hasNext()` will always return `false`, but maybe `bIterator.hasNext()` still has elements and that should be checked.

```
    return !bIterator.hasNext();
```

**Comment by eamonnmcmanus** [comment]
You're right that the final condition is always true. However the method starts with an equal-size check, so in fact only the `hasNext()` call in the `while` condition is useful.

**Comment by ogregoire** [comment]
I'm sorry for not checking further: this issue report was the result of static analysis in IntelliJ of the code, and I didn't check outside the `while` loop.

**Comment by eamonnmcmanus** [comment]
It was a great find anyway. Thanks!
