### ISSUE TITLE
CopyAnnotations doc is backward from its behavior

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#877]
CopyAnnotations' doc on the class and in the repo suggest that you can use it to opt in annotation copying, when in fact it appears that this annotation is only useful to opt _out_ of this behavior

**Comment by eamonnmcmanus** [comment]
The documentation [says](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/AutoValue.java#L92):

> For historical reasons, annotations are always copied from an `@AutoValue` property
> method to its implementation, unless `@CopyAnnotations` is present and explicitly
> excludes that annotation. But annotations are not copied
> from the `@AutoValue` class itself to its implementation unless `@CopyAnnotations`
> is present.

The resulting behaviour is obviously not ideal, but that's where backward compatibility gets you. I think the documentation is correct, but if you want to suggest improvements to it that would make it clearer that would certainly be helpful.
