### ISSUE TITLE
KSP Implementation of AutoService

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#882]
I've written a KSP implementation of auto-service here: https://github.com/ZacSweers/auto-service-ksp

Would you be interested in upstreaming this as a separate, non-annotation-processor option here? I'm fine with maintaining it as a separate project, but want to run it by here in case there's any interest.

**Comment by ZacSweers** [comment]
Note that KSP is experimental right now, so this would be something later down the line when it's stable. It may also require moving to Gradle, as there's no current formal support for KSP in maven projects

**Comment by asos-seancoyle** [comment]
Has there been any progress in supporting KSP?

**Comment by manishindiainc** [comment]
Team, did we have any progress on supporting it officially?

**Comment by Edger** [comment]
Any progress on this？

**Comment by rasmussl** [comment]
Any progress?

**Comment by ZacSweers** [comment]
Closing this. My library works, people can use it if they want 👍

**Comment by polarene** [comment]
Thanks for creating the library, I really needed it!
