### ISSUE TITLE
Have a standalone jar in mavencentral with the processors

### ISSUE THREAD

**Issue by frankbenoit** [google/auto#890]
In Eclipse I can configure the annotation processor by pointing to a jar.
But auto-factory adds several dependencies, hence I have to point to each of those jars.
Also, If I use auto-value and auto-factory, i have to point to the other jar.

I would be happy to see a single jar, which contains all the processors.

Another difficulty is, that having the processors in the my project dependencies, add a different guava version than that one I want to use. Having here the standalone would also make those independently.

**Comment by eamonnmcmanus** [comment]
Realistically, I think we are probably not ever going to get around to doing this, and I'd rather close it than leave it open indefinitely. The best approach with IDEs is most likely to set your project up with Maven or Gradle, and then the dependencies should be retrieved automatically. AutoValue does currently have a fat jar but if anything I think we want to move away from that.
