### ISSUE TITLE
BuilderSpec doesn't expose inherited builder methods to auto value extensions

### ISSUE THREAD

**Issue by caraesten** [google/auto#933]
I'm running into an issue with [auto-value-gson](https://github.com/rharter/auto-value-gson) that seems to be caused by how the `BuilderSpec` in auto-value exposes builder methods. As an example, I have this base builder class (in kotlin)

```
interface ExampleBaseBuilder<out BuilderType : ExampleBaseBuilder<BuilderType, out BuiltType>, out BuiltType> {
  fun userId(userId: String): BuilderType

  fun entityId(entityId: String): BuilderType

  fun dateUpdated(dateUpdated: Long): BuilderType

  fun build(): BuiltType
}
```

this is extended by two builders in autovalue classes, which look like this (back to Java):

```
  @AutoValue.Builder
  public interface Builder extends ExampleBaseBuilder<Builder, ExampleClass> {}
```

auto-value is able to generate both the class and builder just fine, but `auto-value-gson` checks for the `build` method in the `BuilderSpec` that's passed to it, and can't find it. That seems to be because `buildMethod()` is defined as follows:

```
    @Override
    public Optional<ExecutableElement> buildMethod() {
      return methodsIn(builderTypeElement.getEnclosedElements()).stream()
          .filter(
              m ->
                  m.getSimpleName().contentEquals("build")
                      && !m.getModifiers().contains(Modifier.PRIVATE)
                      && !m.getModifiers().contains(Modifier.STATIC)
                      && m.getParameters().isEmpty()
                      && erasedTypeIs(m.getReturnType(), autoValueClass))
          .findFirst();
    }
```

`TypeElement#getEnclosedElements()`, then, returns only the methods declared on the class itself, not any of its ancestors. I was wondering: should the `BuilderSpec` support finding builder methods on the builder's ancestors, or is this an intentional limitation of extensions?

Thanks a ton for looking into this!

**Comment by eamonnmcmanus** [comment]
Yes, clearly we should be looking for these methods in supertypes and not just the builder class itself.

**Comment by eamonnmcmanus** [comment]
A fix is in progress. Meanwhile, you should be able to work around the problem by redeclaring the `build()` method with its actual type. In the example:

```java
  @AutoValue.Builder
  public interface Builder extends ExampleBaseBuilder<Builder, ExampleClass> {
    @Override
    ExampleClass build();
  }
```

**Comment by eamonnmcmanus** [comment]
@caraesten are you able to check whether this change fixes your problem? You could clone this repo, then go into `value/` and do `mvn install`, then update your `auto-value` dependencies to use `HEAD-SNAPSHOT` instead of a version number.

**Comment by caraesten** [comment]
@eamonnmcmanus super impressed w/ the fast turnaround here! unfortunately, I left Slack and don't have access to the codebase where I was running into this, ha. Maybe @ZacSweers can verify?

Thanks, regardless!
