### ISSUE TITLE
AutoFactory generated code is mis-annotating parameters

### ISSUE THREAD

**Issue by wesalvaro** [google/auto#949]
When using the [Checker Framework's `TYPE_USE` Nullable annotation](https://checkerframework.org/api/org/checkerframework/checker/nullness/qual/Nullable.html),  
AutoFactory is generating code that changes the scoping (?) of the inner-class which causes the annotation to be placed in the wrong location.

```java
import com.my.package.Foo.Bar;
import com.my.package.Foo.Baz;
import org.checkerframework.checker.nullness.qual.Nullable;

@AutoFactory
class MyClass {
  MyClass(
    @Nullable Bar bar,
    @Nullable Baz baz,
    ...
  ) { ... }
}
```

The above seems to be generating:

```java
import com.my.package.Foo;
import org.checkerframework.checker.nullness.qual.Nullable;

class MyClassFactory {
  MyClassFactory(
    @Nullable Foo.Bar bar,
    @Nullable Foo.Baz baz,
    ...
  ) { ... }
}
```

Because the build dies with this error:

```
 scoping construct cannot be annotated with type-use annotation: @org.checkerframework.checker.nullness.qual.Nullable
      @Nullable Foo.Bar bar,
 scoping construct cannot be annotated with type-use annotation: @org.checkerframework.checker.nullness.qual.Nullable
      @Nullable Foo.Baz baz,
```

Why isn't the generated code using the same scoping setup as the source?

Issue #732 may be related?

**Comment by eamonnmcmanus** [comment]
FTR, issue #732 is not related. The problem here is that we're not putting `TYPE_USE` annotations in the right place when we use JavaPoet. Issue #732 concerns AutoValue, not AutoFactory as here, and AutoValue doesn't use JavaPoet.

I have a fix for this issue in the pipeline.

**Comment by wesalvaro** [comment]
Thank you for the quick fix!
