### ISSUE TITLE
Incorrectly formatted auto code

### ISSUE THREAD

**Issue by elharo** [google/auto#962]
Probably multiple bugs here, one of which is that gradle can't clean up after itself; but another is that autovalue seems to be generating source code that doesn't fit Google style. 

```
elharo-macbookpro1:gax-java elharo$ ./gradlew test

> Task :verifyGoogleJavaFormat FAILED


The following files are not formatted properly:

/Users/elharo/gax-java/gax-grpc/.apt_generated/com/google/api/gax/grpc/AutoValue_GrpcStatusCode.java
/Users/elharo/gax-java/gax-grpc/.apt_generated/com/google/api/gax/grpc/AutoValue_GrpcTransportChannel.java
/Users/elharo/gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/SettingsTest.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/tracing/AutoValue_SpanName.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/core/AutoValue_FixedCredentialsProvider.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/core/AutoValue_GoogleCredentialsProvider.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/core/AutoValue_InstantiatingExecutorProvider.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/retrying/AutoValue_RetrySettings.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/retrying/AutoValue_TimedAttemptSettings.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/batching/AutoValue_FlowControlSettings.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/batching/AutoValue_BatchEntry.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/batching/AutoValue_BatchingSettings.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/rpc/AutoValue_ClientContext.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/rpc/AutoValue_PageContext.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/rpc/testing/AutoValue_FakeOperationSnapshot.java
/Users/elharo/gax-java/gax/.apt_generated/com/google/api/gax/rpc/AutoValue_FixedHeaderProvider.java
/Users/elharo/gax-java/gax/src/main/java/com/google/api/gax/rpc/UnaryCallSettings.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_HttpJsonTransportChannel.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_ApiMethodDescriptor.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_HttpJsonCallOptions.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_ApiMessageHttpRequestFormatter.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_ApiMessageHttpResponseParser.java
/Users/elharo/gax-java/gax-httpjson/.apt_generated/com/google/api/gax/httpjson/AutoValue_HttpRequestRunnable.java
```

**Comment by cgdecker** [comment]
I'm just triaging this issue and can't speak authoritatively to this, but I don't _think_ AutoValue tries to guarantee that it generates perfectly GJF compliant code, particularly since it isn't generating code that should be checked in anywhere.

**Comment by elharo** [comment]
It's not checked in but it is read by humans in IDE, and that is one of the promises autovalue makes.. Popping op[ne AutoValue_BatchEntry in Eclipse, the code did look pretty good. However there were 1-2 style violations I noticed 

The class declaration was 106 characters and the hashCode() method contained a local variable named `h$`.

**Comment by JakeWharton** [comment]
If GJF is added please make it opt-in like Dagger. When Dagger had forced GJF it wasted 40% of the processor time on formatting for little gain (and arguably no practical gain). Thankfully it has since changed to be opt-in.

**Comment by eamonnmcmanus** [comment]
I'm not sure it's worth spending much time on this. If there are specific style violations then please list them so we can decide on a case-by-case basis whether it is worth addressing them. For example, identifiers with `$` are [explicitly](https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.8) reserved for mechanically generated code:

> The dollar sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems.

AutoValue uses `h$` to avoid conflicts with a possible identifier `h` in user code.

Likewise, lines over 100 characters are common in generated code.

To be clear, we are not ever going to guarantee that AutoValue generates GJF-compliant code, and if you have a GJF check then you should ensure that generated code is excluded from it.
