### ISSUE TITLE
Which setup is recommented for Auto project development?

### ISSUE THREAD

**Issue by frankbenoit** [google/auto#996]
HI

I try to work on an issue in the auto-value procesor.
For this I try to import the project into Eclipse, but there are many problems.
Can I use Eclipse for the "auto" project? Is there information how to setup a development environment?

Which IDE do you use?

Frank

**Comment by eamonnmcmanus** [comment]
I can't speak for others on the project, but personally I use NetBeans or IntelliJ. I'm pretty sure none of the current Google developers on the project uses Eclipse.

If there are changes that would make working on the project work better on Eclipse, we would probably accept them.

**Comment by kluever** [comment]
Generally, "how do i..." type of questions are better suited for stackoverflow.com
